LD4P/sinopia_editor

Gruntfile.js

The gruntfile from upstream code now works;  this just reformats per issue #9.
Closes #9

Gruntfile: reformatted whitespace so tasks line up

---

.circleci/config.yml
.gitignore
package-lock.json
package.json

Closes #37
See https://69-149367347-gh.circle-artifacts.com/0/static-analysis/index.html

add static analysis with es6-plato to circleci build

---

.eslintrc-todo.yml
.eslintrc.yml
package-lock.json
package.json

Unfortunately, the generated todo list is not read by eslint, so I'm not sure if we want to take this PR or not.
Closes #45

eslint-takeoff added with generated eslint todo list

---

README.md

Brings README up to date with current state of BFF.
Connected to #47 - it does NOT explain how to load profiles.

README updated for LD4P sinopia_editor

---

.eslintrc.js
__tests__/integration/profile-datatable.test.js

Tests for Profiles datatables, checks for Search, table columns, and pagination links
Fixes #59

Tests for Profiles datatable,

---

__mocks__/fileMock.js
__mocks__/styleMock.js
__tests__/components/App.test.js
__tests__/components/Header.test.js
package-lock.json
package.json
setupEnzyme.js
src/components/Header.jsx
src/components/LoginPanel.jsx
src/components/NewsPanel.jsx

React test setup

---

Dockerfile
package.json
src/components/App.jsx
src/components/DescPanel.jsx
src/components/NewsPanel.jsx
src/styles/main.css

connects LD4P/sinopia#111
Build Script creates dist/ folder w/ bundle.js and index.html
DescriptionPanel:

Add DescriptionPanel and Some Styling

---

__tests__/components/Header.test.js
src/components/App.jsx
src/components/Footer.jsx
src/components/Header.jsx
src/components/NewsPanel.jsx
src/styles/main.css

Added the Footer:
More menu drop down options:
Box Shadow for NewsPanel:

Add Footer with more Styling, and adding items to drop down menu

---

src/components/NewsItem.jsx

Update Latest News on Home Page

---

README.md
package-lock.json
package.json

Updated the documentation with the correct commands for building and running the Sinopia Editor with React and Docker. Moved `bfe` sections to later in the README. 
Leaving this **WIP** in case @SaravShah wants to add comments on the React portion of the README.
Fixes #105

Updating README with the latests command to run the Sinopia Editor.

---

src/components/App.jsx

Forgot to update route in App.jsx - when updating route from `/search` to `/editor`

update Editor route

---

server.js

Addressed two comments by @jermnelson on PR #110

server.js: better error messages when spoofing falls through

---

__tests__/components/CanvasMenu.test.js
__tests__/components/Header.test.js
__tests__/components/HomePage.test.js
package-lock.json
package.json
src/components/App.jsx
src/components/BFF.jsx
src/components/CanvasMenu.jsx
src/components/Header.jsx
src/components/HomePage.jsx
src/styles/main.css

- Canvas Menu integrated w/ `HomePage.jsx` NOT `App.jsx`
- Adds styling to canvas menu
- Basic Unit Tests
Before:
After clicking `Help and Resources`: 
closes LD4P/sinopia_editor#90

Homepage slide out menu

---

__tests__/components/Header.test.js
src/components/Header.jsx

Updates URL for Sinopia Profile Editor link on the Sinopia Home page header and adds test as well.

Changes link to Sinopia Profile Editor

---

__tests__/components/Footer.test.js
src/components/Footer.jsx
src/styles/main.css

update footer image and description

---

__tests__/components/editor/ResourceTemplate.test.js

Adds tests for rendering of PropertiesWrapper component

---

server.js

Fixed 404 when GET editor directly or refreshing page

---

README.md

Add more description on creating new docker build

---

README.md
package.json
src/components/editor/Editor.jsx
src/components/editor/PropertyTemplate.jsx
src/components/editor/ResourceTemplate.jsx

WIP - i think some of the "if" statements are rendering ...
- package scripts to compile without optimizing and otherwise speed up dev cycle
- README updated to reflect ^^ and also be clearer about diff between running webpack and running express
- some error handling on editor react component rendering

Minor improvements I stumbled into while working on sinopia server spoofing

---

__tests__/components/editor/StartingPoints.test.js
src/components/editor/Editor.jsx
src/components/editor/ResourceTemplate.jsx
src/components/editor/StartingPoints.jsx
src/styles/main.css

Adds a placeholder starting points menu

---

.eslintrc.js
__tests__/components/CanvasMenu.test.js
__tests__/components/Footer.test.js
__tests__/components/NewsItem.test.js
package.json
src/components/CanvasMenu.jsx
src/components/Footer.jsx
src/components/NewsItem.jsx

Adds rel="noopener noreferrer" to all target="_blank" anchor tags to fix security warning in eslint along with corresponding tests.
Closes #174

Updated anchors with target="_blank" to include security fix

---

__tests__/components/editor/Editor.test.js
__tests__/components/editor/FormWrapper.test.js
__tests__/components/editor/InputLiteral.test.js
__tests__/components/editor/PropertyTemplate.test.js
__tests__/components/editor/ResourceTemplate.test.js
__tests__/components/editor/StartingPoints.test.js
__tests__/components/editor/ValueConstraints.test.js
src/components/editor/FormWrapper.jsx
src/components/editor/InputLiteral.jsx
src/components/editor/StartingPoints.jsx

Add to the top of files `// Copyright 2018 Stanford University see Apache2.txt for license`

Add the copyright notice at the top of Stanford's files

---

package-lock.json
package.json

Also removes and removes **flatmap-stream** as a dependency.
Fixes #203

Downgrades event-stream to 3.3.4

---

__tests__/components/editor/InputLiteral.test.js
src/components/editor/InputLiteral.jsx
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/MonographInstance.json

- Did I add the propertyTemplate to `MonographInstance.json` correctly?
closes #198 
TODO: Create ticket to handle defaults that are set like this:
``` 
default: 
defaultLiteral: ""
defaultURI: ""
```

Default value constraint for type Literal

---

__tests__/components/editor/ResourceTemplateForm.test.js
src/components/editor/ResourceTemplateForm.jsx

Default Mandatory Repeatable and Editable values set

---

__tests__/actions/index.test.js
__tests__/components/editor/InputLiteral.test.js
__tests__/reducers/literal.test.js
src/actions/index.js
src/components/editor/InputLiteral.jsx
src/reducers/literal.js
src/store.js

closes #245 
When clicking on the X:

Remove item from redux

---

.eslintrc.js
src/components/editor/InputLiteral.jsx

Prop types lint

---

__tests__/components/editor/InputLookup.test.js
__tests__/components/editor/ResourceTemplateForm.test.js
__tests__/reducers/lookups.test.js
src/components/editor/InputList.jsx
src/components/editor/InputLookup.jsx
src/reducers/index.js
src/reducers/lookups.js

Fixes #261
- Combined reducer includes lookup component
- Changes InputLookup component to dispatch state to reducer action
- Tests for modified component and lookup reducer

Input lookup redux

---

__tests__/components/editor/InputLiteral.test.js
src/components/editor/InputList.jsx
src/components/editor/InputLiteral.jsx
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/MonographInstance.json

Use propertyURI for react store id

---

__tests__/components/editor/InputList.test.js

@jermnelson this addresses @SaravShah 's concern with the closed PR #260

Adds test for mock formData function call

---

src/store.js

See http://extension.remotedev.io/ for more information. Able to see state, actions, and more from Chrome dev tools and Firefox Web Developer tools.

Added support for the Redux Chrome and Firefox extensions

---

__tests__/components/editor/InputList.test.js
src/components/editor/InputList.jsx

Set default values for InputList component if they exist

---

__tests__/components/editor/InputLiteral.test.js
src/components/editor/InputLiteral.jsx
src/components/editor/ResourceTemplateForm.jsx

Fixes #238 
Fixed bug by passing a property to the component as an "id" and then using that id to set a unique id for the input field, and making a handleFocus method to call when the field is clicked.

Fix input bug

---

.circleci/config.yml

Basically a copy of the config from sinopia_profile_editor, with
only changes to the working directory and the name of the
AWS ECS service (sinopia-homepage).  The rest is unchanged.

Update circleci with AWS deploy information

---

__tests__/components/editor/Editor.test.js

Dunno if this will help with coverage for #319, but it was easy and seemed worth doing.

Editor unit tests: beefed up a wee bit

---

static/spoofedFilesFromServer/fromSinopiaServer/lookupConfig.json
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/DDC.json
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/LCCN.json
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/MonographInstance.json
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/MonographWork.json

Fixes #333 
Relates to https://github.com/LD4P/sinopia_profile_editor/pull/181

LOC uris for List components need to be https to avoid mixed content errors

---

static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/MonographInstance.json

update spoofed MonographInstance resourceTemplate to be schemaValid

---

__tests__/components/editor/InputLiteral.test.js
package.json
src/components/App.jsx
src/components/editor/InputLiteral.jsx
src/components/editor/InputLookupQA.jsx
src/components/editor/ModalToggle.jsx
src/components/editor/RequiredSuperscript.jsx
src/components/editor/ResourceTemplateForm.jsx
src/components/editor/ResourceTemplateModal.jsx
src/components/editor/StartingPoints.jsx

A bunch of small things that could improve productivity a teeny tiny smidge:
- should help us run tests locally 
- should help us debug test errors more easily
- remove some noise lines from components

Little tweaks

---

__tests__/reducers/literal.test.js
src/components/editor/InputLiteral.jsx
src/reducers/literal.js

Make sure reducer for literal matches on formData object id

---

__tests__/components/editor/Browse.test.js
__tests__/components/editor/Header.test.js
__tests__/components/editor/ImportResourceTemplate.test.js
package-lock.json
src/components/App.jsx
src/components/editor/Browse.jsx
src/components/editor/Header.jsx
src/components/editor/ImportResourceTemplate.jsx
src/styles/main.css

For issue #113 , added tabs to the editor page and some styling.  Browse and Import Resource Template pages are quite empty (except for the section I copied over to import resource template from the main editor page).

Tabstubs 113

---

__tests__/components/editor/InputLiteral.test.js
package-lock.json
package.json
src/components/editor/InputLiteral.jsx
src/components/editor/ResourceTemplateForm.jsx
src/reducers/literal.js

Fixes #341 
- Use Lodash to check whether something exists in the store before adding a new content item
- Check for either propPredicate or propURI when setting defaults because the modal will have a different propURI.

Dedupe defaults

---

package.json

Upped version to match `0.2.0` tag.

Version for Milestone 2

---

src/components/editor/StartingPoints.jsx

stumbled into when discovering #367 isn't a problem anymore ...

StartingPoints: remove commented out code no longer used

---

package-lock.json
package.json

Github security alert for `event-stream` dependancy, upgrades version to **4.0.1**
see https://github.com/dominictarr/event-stream/issues/116

event-stream has an unsafe dependency flatmap-stream

---

__tests__/Config.test.js
__tests__/components/Header.test.js
src/Config.js
src/components/Header.jsx

 Make header links interpolated based on config

---

src/components/DescPanel.jsx
src/components/NewsItem.jsx

update newspanel to announce release 0.2.0
update descpanel with correct wording for U of Iowa

added new text

---

__tests__/components/App.test.js
src/components/App.jsx

This fixes the bug identified before doing the demo.

Add missing location prop

---

__tests__/Config.test.js
src/Config.js

Updating with new Cognito client id: `543cav95u0q1rqcags1nedc68a ` after running `terraform apply` with changes to email length limit.

Update Config.js with new Cognito client id

---

README.md

As a reminder for developers to update the Config when needed.

Update Readme with info about Cognito AWS

---

__tests__/components/Header.test.js
src/components/Header.jsx

Fix header URL to use proper config getter

---

__tests__/components/editor/ImportFileZone.test.js
src/components/editor/ImportFileZone.jsx

Restyle ImportFileZone to match designs

---

static/spoofedFilesFromServer/fromSinopiaServer/lookupConfig.json

Fix URN for All LOC Subjects in QA config

---

package-lock.json
src/components/CanvasMenu.jsx

-revised sidebar links according to latest user designs
-made the link headings non-clickable

revised sidebar links

---

README.md
docker-compose.yml

And update the README.
connects to LD4P/sinopia#196

Create containers and ACLs in Trellis when spinning up docker-compose

---

__tests__/Config.test.js
src/Config.js

Fixes #456 
Rearrange config a bit, and add trellis static and env values. Fill in missing test descriptions.

Update config with new trellis base url

---

docker-compose.yml

connects to https://github.com/LD4P/sinopia_acl/issues/63

Use 0.2 tag of ACL docker image

---

.gitignore
README.md
docker-compose.yml

Pass Cognito credentials to the platformdata service via env variables

---

.circleci/config.yml

Env vars referenced are already set in Circle UI

Build stage and prod images in CI

---

__tests__/components/App.test.js
__tests__/components/Header.test.js
__tests__/components/Login.test.js
__tests__/components/editor/Header.test.js
__tests__/integration/schemaValidation.test.js
src/components/App.jsx
src/components/Header.jsx
src/components/Login.jsx
src/components/editor/Header.jsx

Replaces the /import path name with the path name /templates

---

README.md
__tests__/components/editor/Editor.test.js
__tests__/components/editor/RDFModal.test.js
src/components/editor/Editor.jsx
src/components/editor/RDFModal.jsx
src/reducers/index.js

🎩 off to @jgreben for his help.
Hooks up interaction with RDFModal component.  Clicking "Preview RDF" button gives:
and clicking close in the modal does the obvious.
Note that this does NOT produce correct RDF -- that is ticketed separately as #481
Closes #404

Preview modal

---

__tests__/Config.test.js
__tests__/components/CanvasMenu.test.js
__tests__/integration/landingPage.test.js
src/Config.js
src/components/App.jsx
src/components/CanvasMenu.jsx

Partially fixes https://github.com/LD4P/sinopia_profile_editor/issues/208 on the sinopia_editor side.

Fetch Help and Resources menu items from github pages

---

src/components/HomePage.jsx
src/reducers/index.js

Bumped into these while I was learning about react-redux ...

two comment tweaks

---

__tests__/components/editor/InputLiteral.test.js
__tests__/components/editor/PropertyTemplateOutline.test.js
package.json
src/components/editor/PropertyTemplateOutline.jsx

Refactored PropertyTemplateOutline prior to working on #346 - make property with type resource repeatable.
Tried to clean up some variable and method names and so on for the code to be more readable.

Refactoring

---

README.md

Fixes LD4P/sinopia#209
This can be run from any branch at any time to refresh the dev instance of the editor.

Document how to deploy the editor to the AWS development environment

---

README.md

(found it while working with same info for profile editor)

fix README typo in docker section

---

__tests__/Utilities.test.js
__tests__/components/editor/PropertyComponent.test.js
__tests__/components/editor/PropertyTemplateOutline.test.js

Per Naomi's post-merge review https://github.com/LD4P/sinopia_editor/pull/546.

Make tests and test descriptions better

---

__tests__/components/editor/InputLookupQA.test.js
src/components/editor/InputListLOC.jsx
src/components/editor/InputLookupQA.jsx
src/components/editor/PropertyComponent.jsx

Fixes #516 
@hudajkhan I looked over the `429_qaselector` branch and there were some massive refactor changes that happened that impacted that branch. I re-applied the changes you made in that branch to this new branch. Can you look it over and give your stamp of approval?

InputLookupQA fixes and redux connection

---

__tests__/CognitoUtils.test.js
src/CognitoUtils.js

Add unit tests for CognitoUtils class

---

__tests__/Utilities.test.js
__tests__/components/editor/InputListLOC.test.js
__tests__/components/editor/InputLookupQA.test.js
__tests__/components/editor/PropertyComponent.test.js
src/Utilities.js
src/components/editor/InputListLOC.jsx
src/components/editor/InputLookupQA.jsx
src/components/editor/PropertyComponent.jsx

Fixes #568
Includes some refactoring of PropertyComponent and InputListLOC components

Extract and pass along property template defaults from InputLookupQA component to typeahead

---

README.md

Without this step you get a syntax error when running the server

Add instructions about building the distribution

---

__tests__/components/editor/PropertyComponent.test.js

Fix malformed URI in PropertyComponent test

---

__tests__/components/LoginPanel.test.js
src/components/LoginPanel.jsx

Create a test for display of authentication errors

---

__tests__/CognitoUtils.test.js
__tests__/components/App.test.js

this fixes the `App` component tests skipped to get #460 merged more quickly, and in the process of that, does a bit of restructuring (in hope that the new organization of the tests is a bit simpler and more regular).
* providing only the supporting components needed to get `App` to have a working redux store and a working react router allowed for faking specific redux states and URI visits (to exercise particular authentication-related behavior in combo with particular URI renderings).  this meant using `Provider` with a fake store to wrap `App`, instead of relying on `RootContainer` (which will already have its own redux store).
* a couple of components included by `App` are also mocked, to prevent their implementation details from interfering with specific unit testing of `App` (since …

Fix skipped app tests

---

__tests__/components/editor/Editor.test.js
src/components/editor/Editor.jsx
src/components/editor/ImportResourceTemplate.jsx
src/sinopiaServer.js

Remove indirection

---

__tests__/Config.test.js

i forgot to add this to #528 (or any of the tix it spawned), but this was simple enough that it didn't feel worth ticketing (it was in my TODO list, though).

a couple simple tests for Config.awsCognitoUserPoolId

---

index.html

Set page title to Sinopia Linked Data Editor.

---

src/reducers/index.js

The refreshResourceTemplate already does the same to the received argument

Remove unnecessary Object.create

---

.eslintrc.js
__tests__/GraphBuilder.test.js
src/GraphBuilder.js

Convert the state to RDF

---

__tests__/GraphBuilder.test.js
__tests__/reducers/index.test.js
src/GraphBuilder.js
src/reducers/index.js

Set the RDF class in the graph

---

__tests__/components/editor/InputLookupQA.test.js
src/components/editor/InputLookupQA.jsx

Fixes configuration of non-repeatable lookups.

---

__tests__/components/editor/PropertyActionButtons.test.js
__tests__/components/editor/PropertyResourceTemplate.test.js
__tests__/components/editor/ResourceProperty.test.js
__tests__/integration/repeatableResources.test.js
src/components/editor/PropertyActionButtons.jsx
src/components/editor/PropertyResourceTemplate.jsx
src/components/editor/PropertyTemplateOutline.jsx
src/components/editor/PropertyTypeRow.jsx
src/components/editor/ResourceProperty.jsx

Removes mint uri button.

---

__tests__/components/editor/Editor.test.js
__tests__/components/editor/ImportFileZone.test.js
__tests__/components/editor/RDFModal.test.js
__tests__/sinopiaServer.test.js
src/components/editor/Editor.jsx
src/components/editor/RDFModal.jsx
src/sinopiaServer.js

Also adds skeleton server function to handle save

Adds save and cancel buttons to RDF Modal

---

src/GraphBuilder.js
src/reducers/index.js

This removes an invalid Literal set as the rdf:type
Ref #614

Omit type assertion since the permission template doesn't support it

---

.eslintrc.js
__tests__/components/editor/InputLiteral.test.js
src/components/editor/InputLiteral.jsx

Allows re-editing of literals.

---

package.json

Updates to `0.3.1` in package.json.

Bug fixes and new feature additions in release.

---

README.md
package-lock.json

Updates package-lock.json with the latest version. Directions in README now include step for package-lock.json in the tagged release section

Updated README with directions for tagged release, updates package-lock.json

---

__tests__/components/editor/GroupChoiceModal.test.js
src/components/editor/Editor.jsx
src/components/editor/GroupChoiceModal.jsx

the ld4p container is just for templates (not for resources)

Filter ld4p out of the list of groups you can save into

---

__tests__/components/editor/GroupChoiceModal.test.js
__tests__/components/editor/RDFModal.test.js
__tests__/reducers/index.test.js
src/components/editor/Editor.jsx
src/components/editor/GroupChoiceModal.jsx
src/components/editor/RDFModal.jsx
src/reducers/index.js

Also changed the UI a bit.  Before:
After:

Only generate the RDF when the button is pressed to preview

---

__tests__/GraphBuilder.test.js
__tests__/reducers/index.test.js
__tests__/reducers/inputs.test.js
__tests__/sinopiaServer.test.js
src/GraphBuilder.js
src/actions/index.js
src/components/editor/Editor.jsx
src/reducers/index.js
src/reducers/inputs.js
src/sinopiaServer.js

Save resource to Trellis

---

__tests__/GraphBuilder.test.js
__tests__/actions/index.test.js
__tests__/components/editor/property/ResourceProperty.test.js
__tests__/reducers/index.test.js
src/GraphBuilder.js
src/actions/index.js
src/components/editor/property/PropertyTemplateOutline.jsx
src/components/editor/property/ResourceProperty.jsx
src/reducers/index.js

Adds rdfClass for children.

---

__tests__/integration/unauthenticatedNavigation.test.js
package.json

This should fix the master build

Fix the copy pasta linter comment error

---

__tests__/GraphBuilder.test.js
__tests__/components/editor/property/PropertyTemplateOutline.test.js
__tests__/components/editor/property/ResourceProperty.test.js
__tests__/integration/repeatableResources.test.js
src/GraphBuilder.js
src/components/editor/property/PropertyResourceTemplate.jsx
src/components/editor/property/PropertyTemplateOutline.jsx
src/components/editor/property/ResourceProperty.jsx

Fixed add buttons.

---

__tests__/components/editor/Editor.test.js
__tests__/components/editor/RDFModal.test.js
__tests__/integration/previewSaveRDF.test.js
src/components/editor/Editor.jsx
src/components/editor/RDFModal.jsx
src/styles/main.css

Add editor save button

---

__tests__/GraphBuilder.test.js
__tests__/actions/index.test.js
__tests__/components/editor/ResourceTemplateForm.test.js
__tests__/components/editor/property/ResourceProperty.test.js
__tests__/reducers/index.test.js
src/GraphBuilder.js
src/actions/index.js
src/components/editor/ResourceTemplateForm.jsx
src/components/editor/property/PropertyTemplateOutline.jsx
src/components/editor/property/ResourceProperty.jsx
src/reducers/index.js
src/store.js

This will allow us to validate the redux state without having to reload resouce templates.

Record the resource template responses into the Redux state

---

__tests__/actions/index.test.js
__tests__/components/editor/Editor.test.js
__tests__/reducers/inputs.test.js
src/actions/index.js
src/components/editor/Editor.jsx
src/components/editor/ResourceTemplate.jsx
src/components/editor/ResourceTemplateForm.jsx
src/components/editor/property/InputListLOC.jsx
src/components/editor/property/InputLiteral.jsx
src/components/editor/property/InputLookupQA.jsx
src/components/editor/property/PropertyComponent.jsx
src/reducers/index.js
src/reducers/inputs.js

Moves display validations to state from prop.

---

__tests__/reducers/inputs.test.js
src/reducers/index.js
src/reducers/inputs.js

Updated the tests to use the correct redux paths.
Exposed findNode to make it easier to access the redux state

Fixed a bug where setBaseURI was not in the right redux path.

---

__tests__/components/editor/property/InputLiteral.test.js

Then we don't have to worry about leaky state

Create a new mock for each test

---

__tests__/integration/nestedResources.test.js

A quick integration test addition to verify that interacting with the nested Resource Template works.

Add an integration test for interacting with the input form

---

.eslintrc.js
src/components/editor/ResourceTemplateForm.jsx

rebased on master.  paired w/ @ndushay and @aaron-collier (left the original get-rt-from-store branch alone, just so you guys can make sure the rebase and linting didn't mess anything up).
lays a little ground work for making #693 easier, but doesn't actually resolve it.

Get resource template from redux store

---

__tests__/integration/nestedResources.test.js

Add an intergration test for non-roman entry into a literal

---

__tests__/integration/nestedResources.test.js

Whoops, this screenshot call accidentally got in there.

Remove test screenshot

---

src/components/editor/Editor.jsx

This was first introduced in https://github.com/LD4P/sinopia_editor/commit/30f49b0d1940a15e9c103aacdbe0307c54a5174c

Remove unused variable tempRtState

---

__tests__/Utilities.test.js
__tests__/components/editor/property/PropertyResourceTemplate.test.js
__tests__/components/editor/property/PropertyTemplateOutline.test.js
__tests__/components/editor/property/ResourceProperty.test.js
src/Utilities.js
src/components/editor/property/PropertyResourceTemplate.jsx
src/components/editor/property/PropertyTemplateOutline.jsx
src/components/editor/property/ResourceProperty.jsx

bumped into this when I started to write a new Utilities method

use Utilities.booleanPropertyFromTemplate and remove  .templateBoolean()

---

__tests__/components/editor/property/InputLiteral.test.js
src/components/editor/property/InputLiteral.jsx

Items must be properties or removing them doesn't cause re-render

---

__tests__/components/editor/property/InputListLOC.test.js
src/components/editor/property/InputListLOC.jsx

InputListLOC component should use propertyTemplate.repeatable

---

src/components/editor/Editor.jsx

Editor does not need to maintain a local state

---

__tests__/components/editor/GroupChoiceModal.test.js
src/components/editor/Editor.jsx
src/components/editor/GroupChoiceModal.jsx
src/components/editor/RDFModal.jsx

This reduces coupling between the components and Editor doesn't have to know how to save

Move logic for saving to GroupChoiceModal from Editor

---

__tests__/actionCreators.test.js
__tests__/components/editor/Editor.test.js
__tests__/integration/previewSaveRDF.test.js
__tests__/selectors/resourceSelectors.test.js
package-lock.json
package.json
src/actionCreators.js
src/actions/index.js
src/components/editor/Editor.jsx
src/selectors/resourceSelectors.js
src/sinopiaServer.js
src/store.js

Allow resources to be updated 

---

__tests__/components/editor/property/InputLookupQA.test.js
src/components/editor/property/InputLookupQA.jsx

kinda noisy, easy to add back if we want it again
supersedes #767

don't bother logging to console when there are no defaults defined for a property template

---

src/reducers/inputs.js

@jermnelson please have a look and make sure that I described this all correctly.

Document the setItemsOrSelections reducer function

---

src/selectors/resourceSelectors.js

Copyright statement for resourceSelectors.js

---

__tests__/reducers/index.test.js
src/reducers/index.js

refreshResourceTemplate fix for when no resource is selected

---

__tests__/sinopiaServerSpoof.test.js

Because adding another fixture resource shouldn't break the tests

Test for structure not for equality

---

__tests__/actions/index.test.js
src/actions/index.js
src/components/editor/property/InputLiteral.jsx

We only need to pass reduxPath and item ID

Simplify removing an item.

---

__tests__/GraphBuilder.test.js
src/GraphBuilder.js

Add generatedBy triples to the graph

---

__tests__/components/editor/RDFModal.test.js
__tests__/components/editor/property/InputURI.test.js
__tests__/components/editor/property/PropertyComponent.test.js
src/components/editor/property/InputURI.jsx
src/components/editor/property/PropertyComponent.jsx
src/reducers/inputs.js
src/sinopiaServerSpoof.js
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/Item.json
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/OnlyEquivalent.json

Add a uri component for entering in resources directly

---

package-lock.json
package.json

Tagged version for ALA BIBFRAME Update and LD4P Cohort and Partners meetings.

Version 0.3.3

---

.circleci/config.yml

fix circleci config typos

---

__tests__/actions/index.test.js
__tests__/components/Footer.test.js
__tests__/components/LoginPanel.test.js
__tests__/components/RootComponent.test.js
__tests__/components/editor/ResourceTemplate.test.js
__tests__/components/editor/ResourceTemplateForm.test.js
__tests__/integration/loginHelper.js
__tests__/reducers/authenticate.test.js
__tests__/reducers/lookups.test.js
src/components/home/Header.jsx

noticed the one in `loginHelper.js` while working on #820 and was going to fix it in a second commit.  but then decided to fix it across the board, since that was easy.
done in a separate PR in case anyone objects, or in case this'll create rebase headaches for someone and we should hold off on merging.

cleanup imports to make them consistent across codebase

---

__tests__/components/editor/ResourceTemplate.test.js
__tests__/components/editor/ResourceTemplateForm.test.js
src/components/editor/ResourceTemplate.jsx
src/components/editor/ResourceTemplateForm.jsx

This is needed so that we can load RDF from the server into the form

Make ResourceTemplateForm a connected component

---

__tests__/components/editor/ResourceTemplate.test.js
src/actionCreators.js
src/actions/index.js
src/components/editor/ResourceTemplate.jsx
src/components/editor/ResourceTemplateForm.jsx
src/reducers/index.js

When we load the resource from Trellis, we need a way to load resourceTemplates
So first we'll convert the existing system to use thunks
Thunks take the loading logic out of the components

Use thunks for loading the root resource template

---

src/actions/index.js
src/components/editor/ResourceTemplate.jsx
src/components/editor/ResourceURIMessage.jsx

a couple small touchups that were as easy to make as they were to comment on, so PR to the PR, for your convenience if you like the suggestions
spawned by #833

Amcollie 766 jmartin followon

---

src/actionCreators.js

I left comments on PR #815 after it got merged, and I have been looking at the PR changes as part of doing other work, so I figured I'd just ... do it.

actionCreators: tweak thunk comments

---

__tests__/GraphBuilder.test.js
src/GraphBuilder.js

Omits blank nodes when items arrays are empty.

---

__tests__/components/templates/Download.test.js
__tests__/components/templates/SinopiaResourceTemplates.test.js
package-lock.json
package.json
src/components/templates/Download.jsx
src/components/templates/SinopiaResourceTemplates.jsx
src/styles/main.css

Adds ability to download resource templates.

---

src/components/editor/property/PropertyResourceTemplate.jsx

Previously each property was assigned to its own resource.

All the properties should be on the same resource

---

__tests__/components/App.test.js
__tests__/components/Header.test.js
src/actions/index.js
src/components/App.jsx
src/components/Header.jsx
src/reducers/index.js
src/store.js
src/styles/main.css

882 show version

---

__tests__/ResourceStateBuilder.test.js
package-lock.json
package.json
src/ResourceStateBuilder.js
src/Utilities.js

Creates resource state builder, for transforming RDF to resource state.

---

__tests__/components/editor/property/ResourceProperty.test.js
__tests__/integration/nestedResources.test.js
src/components/editor/property/ResourceProperty.jsx

This introduces a UI regression, where entering a value in a collapsable component, collapses the component rather than keeping it open.

Extract the model from the view logic

---

__tests__/components/editor/property/InputListLOC.test.js
src/components/editor/property/InputListLOC.jsx

Show all authoratative labels

---

Dockerfile
docker-compose.yml

Otherwise the server ends up using the default value in here: https://github.com/LD4P/sinopia_editor/blob/master/src/Config.js#L44

INDEX_URL has to be set as an environment variable

---

__tests__/actionCreators/resources.test.js
__tests__/reducers/index.test.js
src/actionCreators/resources.js
src/actions/index.js
src/reducers/index.js

Clears resource templates when loading resource.

---

__tests__/__fixtures__/SinopiaLookup.json
__tests__/components/editor/property/InputLookupSinopia.test.js
__tests__/components/editor/property/PropertyComponent.test.js
__tests__/fixtureLoaderHelper.js
src/Config.js
src/Utilities.js
src/components/editor/property/InputLookupSinopia.jsx
src/components/editor/property/PropertyComponent.jsx
src/reducers/inputs.js
static/lookupConfig.json

Sinopia element

---

server.js

Pass parameters to ElasticSearch

---

__tests__/components/editor/property/OutlineHeader.test.js
__tests__/components/editor/property/PropertyTemplateOutline.test.js
__tests__/integration/addRemoveButtons.test.js
__tests__/integration/nestedResources.test.js
__tests__/integration/previewRDFHelper.js
__tests__/integration/repeatableResources.test.js
__tests__/reducers/index.test.js
src/components/editor/property/OutlineHeader.jsx
src/components/editor/property/PropertyActionButtons.jsx
src/components/editor/property/PropertyTemplateOutline.jsx
src/reducers/index.js

Adds add and remove buttons for toggling properties.

---

__tests__/actionCreators/resourceTemplates.test.js
__tests__/components/App.test.js
__tests__/components/templates/Download.test.js
__tests__/components/templates/ImportResourceTemplate.test.js
__tests__/components/templates/SinopiaResourceTemplates.test.js
src/actionCreators/resourceTemplates.js
src/actionCreators/resources.js
src/actions/index.js
src/components/App.jsx
src/components/templates/Download.jsx
src/components/templates/ImportResourceTemplate.jsx
src/components/templates/SinopiaResourceTemplates.jsx
src/reducers/index.js
src/store.js

Moves resource template summaries to redux state and loading to a thunk.

---

__tests__/components/editor/GroupChoiceModal.test.js
src/components/editor/GroupChoiceModal.jsx

Sets correct container when saving rdf.

---

.github/ISSUE_TEMPLATE/tagged-release.md
README.md

Creates a checklist issue template for doing a tagged release.

Adds Tagged Release Checklist Github Issue Template

---

.dockerignore
.eslintignore
.gitignore
README.md
package-lock.json
package.json

This also removes a version of lodash with a high security vulnerability
Reverts much of https://github.com/LD4P/sinopia_editor/commit/e7ec91e4624d163b3d32734c72826b10a5122d33
Fixes #991

Remove static analysis tool

---

.circleci/config.yml
Dockerfile
package.json

Upgrade to node 12.6

---

__tests__/ResourceStateBuilder.test.js
src/ResourceStateBuilder.js
src/Utilities.js

Fixes loading of existing resources.

---

__tests__/reducers/inputs.test.js
src/actions/index.js
src/components/editor/ResourceTemplateForm.jsx
src/reducers/index.js
src/reducers/inputs.js

There is no way to activate this code in the UI.

Remove unused code

---

__tests__/reducers/index.test.js
src/reducers/index.js

Clear errors when loading a resource template

---

__tests__/actionCreators/resources.test.js
src/actionCreators/resources.js

Loading an existing resource sets the resource URI

---

__tests__/components/editor/property/PropertyLabel.test.js
__tests__/components/editor/property/PropertyPanel.test.js
src/components/editor/ResourceTemplateForm.jsx
src/components/editor/property/OutlineHeader.jsx
src/components/editor/property/PropertyLabel.jsx
src/components/editor/property/PropertyPanel.jsx

rename 'pt' to 'propertyTemplate'

Remove unnecessary properties

---

__tests__/actions/index.test.js
__tests__/reducers/inputs.test.js
src/actions/index.js
src/components/editor/property/InputLiteral.jsx
src/components/editor/property/InputURI.jsx
src/reducers/index.js
src/reducers/inputs.js

In reactive programming the events should describe what the user did, not what should happen.

Rename actions to better describe the action the user took

---

__tests__/components/editor/property/InputLiteral.test.js
__tests__/components/editor/property/InputURI.test.js
src/components/editor/property/InputLiteral.jsx
src/components/editor/property/InputURI.jsx

It's already encoded in the reduxPath

Passing uri to setItems is unnecessary

---

__tests__/components/editor/property/InputLookupQA.test.js
src/components/editor/property/InputLookupQA.jsx

Links tokens in InputLookupQA component.

---

.github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/tagged-release.md

Updated description for the Product Owner in the Tagged Release template

Update language 

---

src/reducers/index.js
src/reducers/inputs.js
src/reducers/search.js

Following the pattern in #1011 to clarify the search code.

Extract the reducer related to search into a separate file

---

__tests__/components/editor/property/InputLang.test.js
__tests__/reducers/entities.test.js
src/actionCreators/languages.js
src/actions/entities.js
src/actions/index.js
src/components/editor/property/InputLang.jsx
src/components/editor/property/LanguageButton.jsx
src/reducers/entities.js
src/reducers/index.js

Previously it was loaded every time the language popup was activated.

Load the language data once into entities 

---

__tests__/ResourceStateBuilder.test.js
src/ResourceStateBuilder.js

This fixes a regression from #1005

Update ResourceStateBuilder to build the simpler language

---

__tests__/components/editor/property/InputLookupQA.test.js
src/Utilities.js
src/components/editor/property/InputLookupQA.jsx
src/components/editor/property/InputURI.jsx

Adds option for new uri to InputLookupQA.

---

src/components/templates/SinopiaResourceTemplates.jsx

Add default sorting to the sinopia resource templates table

---

__tests__/integration/loadRDF.test.js
src/components/Header.jsx

Changle tab text to "Load RDF"

---

package-lock.json
package.json
src/components/home/NewsItem.jsx

Along with Release notes in NewsItem component

Patch Release 0.3.5 

---

static/lookupConfig.json

Use the correct authority for MESH

---

__tests__/components/editor/property/InputURI.test.js
src/components/editor/property/InputURI.jsx

Adds error message when user enters a literal in InputURI.

---

__tests__/components/editor/GroupChoiceModal.test.js
__tests__/components/editor/SaveAlert.test.js
__tests__/reducers/index.test.js
src/components/editor/GroupChoiceModal.jsx
src/components/editor/ResourceTemplate.jsx
src/components/editor/SaveAlert.jsx
src/reducers/index.js

Adds notification when saving and publishing a resource.

---

src/components/templates/SinopiaResourceTemplates.jsx

adjust css style of component to make react happy

---

__tests__/components/editor/property/InputLookupQA.test.js
__tests__/integration/previewRDFHelper.js
src/components/editor/property/InputLookupQA.jsx

Allows literal in InputLookupQA.

---

.circleci/config.yml
Dockerfile

I believe this is the search problem in dev.

Set SEARCH_HOST in circle so it is available in the build

---

webpack.config.js

Need to put SEARCH_HOST in webpack config.

Follow up on search URL

---

Dockerfile

This may be a temporary fix while we investigate a better way to handle these variables. But this fixed search in dev.

Set INDEX_URL into the env so it is available

---

__tests__/actionCreators/resources.test.js
__tests__/components/editor/ResourceTemplateForm.test.js
__tests__/components/editor/property/OutlineHeader.test.js
__tests__/components/editor/property/PropertyPanel.test.js
__tests__/integration/nestedResources.test.js
__tests__/integration/previewRDFHelper.js
__tests__/integration/repeatableResources.test.js
src/actionCreators/resources.js
src/components/editor/ResourceTemplateForm.jsx
src/components/editor/property/OutlineHeader.jsx
src/components/editor/property/PropertyPanel.jsx

 Adds add/remove functionality to properties of root resource template.

---

__tests__/components/editor/property/PropertyActionButtons.test.js
__tests__/integration/addRemoveButtons.test.js
__tests__/integration/repeatableResources.test.js
src/components/editor/property/PropertyActionButtons.jsx
src/components/editor/property/PropertyResourceTemplate.jsx
src/components/editor/property/ResourceProperty.jsx

Changes add buttons to add another.

---

static/lookupConfig.json

Lookups must have a unique URI. Fixes #1035

Removed duplicate lookups

---

__tests__/components/editor/property/OutlineHeader.test.js
src/components/editor/property/OutlineHeader.jsx
src/styles/main.css

Changes to adding / toggling of properties.

---

__tests__/components/editor/GroupChoiceModal.test.js
src/components/editor/GroupChoiceModal.jsx
src/components/editor/SaveAndPublishButton.jsx

Otherwise the text becomes unreadable as two different classes are applied

Use the Button attributes rather than class

---

__tests__/components/editor/property/OutlineHeader.test.js
src/components/editor/property/OutlineHeader.jsx

Switches to a right chevron for contracted toggle.

---

__tests__/integration/nestedResources.test.js
src/components/editor/property/PropertyPanel.jsx

Added + before blue Add button on property panel.

---

__tests__/components/editor/property/PropertyPanel.test.js
src/components/editor/property/PropertyPanel.jsx

Only render property panel body when it has been added.

---

__tests__/components/editor/property/InputLiteral.test.js
src/components/editor/property/InputLiteral.jsx
src/components/editor/property/LanguageButton.jsx
src/styles/main.css

Aligned InputLiteral and InputLookup.

---

__tests__/components/editor/SaveAndPublishButton.test.js
src/components/editor/SaveAndPublishButton.jsx

Fixes PropType for current user for SaveAndPublishButton.

---

__tests__/components/editor/property/InputLiteral.test.js
src/components/editor/property/InputLiteral.jsx

This property is no longer used

Remove unnecessary property formData from InputLiteral

---

__tests__/GraphBuilder.test.js
__tests__/actionCreators/resources.test.js
__tests__/components/editor/property/InputLiteral.test.js
__tests__/selectors/resourceSelectors.test.js
src/GraphBuilder.js
src/Utilities.js
src/components/editor/property/InputLang.jsx
src/components/editor/property/InputLiteral.jsx
src/components/editor/property/LanguageButton.jsx

Language is now an entity, we only use its identifier

Remove language label from the resource state

---

src/styles/main.css

Also styled the remove button to match
Fixes #1099 
Before:
After:

Right align the add/remove panel header buttons

---

__tests__/ResourceStateBuilder.test.js
src/ResourceStateBuilder.js

This fixes a regression from #1096

Resource builder should set the language correctly

---

src/styles/main.css

Don't break across a panel when there is only one

---

__tests__/components/editor/property/OutlineHeader.test.js
__tests__/components/editor/property/PropertyLabel.test.js
__tests__/components/editor/property/PropertyLabelInfo.test.js
__tests__/components/editor/property/PropertyLabelInfoLink.test.js
__tests__/components/editor/property/PropertyLabelInfoTooltip.test.js
__tests__/components/editor/property/PropertyPanel.test.js
__tests__/components/editor/property/RequiredSuperscript.test.js
__tests__/integration/previewRDFHelper.js
src/components/editor/property/OutlineHeader.jsx
src/components/editor/property/PropertyLabel.jsx
src/components/editor/property/PropertyLabelInfo.jsx
src/components/editor/property/PropertyLabelInfoLink.jsx
src/components/editor/property/PropertyLabelInfoTooltip.jsx
src/components/editor/property/PropertyPanel.jsx
src/components/editor/property/RequiredSuperscript.jsx
src/styles/main.css

Moves property info to icon. Bolds property labels.

---

__tests__/GraphBuilder.test.js
__tests__/ResourceStateBuilder.test.js
__tests__/Utilities.test.js
__tests__/actionCreators/resources.test.js
__tests__/components/editor/property/InputLang.test.js
__tests__/components/editor/property/InputLiteral.test.js
__tests__/components/editor/property/LanguageButton.test.js
__tests__/reducers/inputs.test.js
src/GraphBuilder.js
src/ResourceStateBuilder.js
src/Utilities.js
src/components/editor/property/InputLang.jsx
src/components/editor/property/InputListLOC.jsx
src/components/editor/property/InputLiteral.jsx
src/components/editor/property/InputLookupQA.jsx
src/components/editor/property/LanguageButton.jsx
src/reducers/inputs.js

so that the items can be addressed by redux path
Fixes #886

Convert items to a hash instead of an array

---

__tests__/components/editor/property/InputLang.test.js
src/components/editor/property/InputLang.jsx

Please merge #1108 first as this would otherwise result in a complicated rebase.

Make InputLang a functional component

---

__tests__/actions/index.test.js
__tests__/components/editor/property/InputLiteral.test.js
__tests__/components/editor/property/InputURI.test.js
__tests__/components/editor/property/InputValue.test.jsx
__tests__/reducers/inputs.test.js
src/actions/index.js
src/components/editor/property/InputLiteral.jsx
src/components/editor/property/InputURI.jsx
src/components/editor/property/InputValue.jsx
src/reducers/inputs.js

[Refactor] extract Literal from InputLiteral

---

__tests__/components/editor/property/InputLiteral.test.js
__tests__/components/editor/property/InputURI.test.js
src/components/editor/property/InputLiteral.jsx
src/components/editor/property/InputURI.jsx

So the tests were not working as expected

The exist method does not take a second argument

---

.github/ISSUE_TEMPLATE/tagged-release.md
README.md
package-lock.json
package.json

Adjusted README and issue template to reflect changes to process.

Tagged Release 0.3.9

---

src/components/editor/property/InputLookupSinopia.jsx

closes #1138
And now the InputLookupSinopia component will render ...

Fixes InputLookupSinopia to handle items as object rather than array.

---

__tests__/ResourceStateBuilder.test.js
__tests__/actionCreators/resources.test.js
src/ResourceStateBuilder.js
src/components/editor/property/InputListLOC.jsx
src/components/editor/property/InputLookupQA.jsx
src/components/editor/property/InputLookupSinopia.jsx
src/selectors/resourceSelectors.js

Create default labels in the ResourceStateBuilder

---

__tests__/selectors/resourceSelectors.test.js
src/components/editor/property/InputListLOC.jsx
src/components/editor/property/InputLookupQA.jsx
src/components/editor/property/InputLookupSinopia.jsx
src/selectors/resourceSelectors.js

Fix typo in itemsForProperty

---

static/lookupConfig.json

QAServer commit:  https://github.com/cul-it/qa_server/pull/82
LD4P Issue: https://github.com/LD4P/qa_server/issues/50
Ref: [Indexing of External Data for Look-ups: LCGFT tab](https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit#gid=696491968)

set loc genre subauths to active/deprecated

---

src/styles/main.css

Per @astridu, these should be solid.

Make Add / Remove buttons have solid borders on panel.

---

__tests__/GraphBuilder.test.js
__tests__/ResourceStateBuilder.test.js
__tests__/actionCreators/resources.test.js
__tests__/integration/correctRdfInPreview/literalPropertyTemplates.test.js
__tests__/integration/loadRDF.test.js
__tests__/selectors/resourceSelectors.test.js
src/GraphBuilder.js
src/ResourceStateBuilder.js

using http://sinopia.io/vocabulary/hasResourceTemplate now.
Fixes #1144

Switch from prov:wasGeneratedBy

---

__tests__/components/editor/property/InputLookupQA.test.js

These assertions are just checking the actions in the test setup.

Remove bad tests

---

__tests__/components/editor/property/InputLookupQA.test.js
src/components/editor/property/InputLookupQA.jsx

 Make InputLookupQA a functional component 

---

__tests__/components/editor/property/InputLookupSinopia.test.js
package-lock.json
src/components/editor/property/InputLookupSinopia.jsx
src/sinopiaServer.js

Changes label and uri fields expected from ES.

---

src/sinopiaServer.js

After deploying the indexing pipeline and reindex, label should now be correct.

Label is now the correct field to grab from the search results

---

__tests__/GraphBuilder.test.js
__tests__/actionCreators/resources.test.js
src/GraphBuilder.js
src/actionCreators/resources.js

Builds graph with relative URI rather than absolute URI.

---

src/components/App.jsx
src/components/editor/Editor.jsx

Fixes prompt when toggling help.

---

src/actionCreators/resourceTemplates.js

Provides reason when calling retrieveError.

---

__tests__/components/editor/property/InputLookupSinopia.test.js
src/components/editor/property/InputListLOC.jsx
src/components/editor/property/InputLiteral.jsx
src/components/editor/property/InputLookupQA.jsx
src/components/editor/property/InputLookupSinopia.jsx
src/components/editor/property/InputURI.jsx
src/components/editor/property/OutlineHeader.jsx
src/components/search/Search.jsx

Added wildcard help text to InputLookupSinopia and Search.

---

__tests__/integration/propertyTemplateMisconfigured.test.js
__tests__/utilities/propertyTemplates.test.js
src/components/editor/property/PropertyComponent.jsx
src/utilities/propertyTemplates.js

Give a more clear error when the lookup is misconfigured

---

package-lock.json
package.json

New version 0.3.10

---

__tests__/components/home/NewsItem.test.js
package-lock.json
package.json
src/components/home/NewsItem.jsx

Sinopia MVP 1.0.0 Release

---

__tests__/reducers/index.test.js
src/reducers/index.js

Resets Editor Validations

---

src/components/home/NewsItem.jsx

Add 1.0.1 release notes to homepage

---

static/lookupConfig.json

adding lc's playing speed vocabulary

Adding Playing Speed

---

.eslintrc.js
__tests__/components/search/Search.test.js
__tests__/components/search/SearchResultsMessage.test.jsx
src/actionCreators/search.js
src/actions/index.js
src/components/search/Search.jsx
src/components/search/SearchResultsMessage.jsx
src/reducers/search.js
src/sinopiaServer.js

Pass error message and zero search results to redux search state when search fetch fails in order to display a failed search connection message. UPDATED GIF!:

Pass search error message from sinopiaServer function to view

---

src/components/editor/property/InputLiteral.jsx
src/components/menu/CanvasMenu.jsx

Rewrote CanvasMenu as a functional component.

---

__tests__/utilities/qa.test.js
src/actions/index.js
src/components/editor/property/InputLookupQA.jsx
src/utilities/qa.js

Handle QA searches async and independently.

---

__tests__/components/search/Search.test.js
src/actions/index.js
src/components/search/Search.jsx
static/searchConfig.json

Added QA authorities as search options.

---

src/actions/index.js
src/components/load/LoadByRDFForm.jsx

Clarified Load by RDF page.

---

__tests__/components/editor/property/InputListLOC.test.js
src/components/editor/property/InputListLOC.jsx

Make reduxPath a required property of InputListLOC

---

src/components/menu/CanvasMenu.jsx

Adds catch to fetch for help and resource menu content.

---

.eslintrc.js
__tests__/ResourceStateBuilder.test.js
__tests__/Utilities.test.js
__tests__/actionCreators/resources.test.js
__tests__/components/editor/ResourceTemplate.test.js
__tests__/components/editor/property/InputLiteral.test.js
__tests__/components/load/LoadByRDFForm.test.js
src/ResourceStateBuilder.js
src/Utilities.js
src/actionCreators/resources.js
src/actions/index.js
src/components/editor/CopyToNewButton.jsx
src/components/editor/ResourceTemplate.jsx
src/components/load/LoadByRDFForm.jsx
src/reducers/index.js

Loads resource based on resource template and returns unmatched triples

---

__tests__/components/editor/property/InputListLOC.test.js
__tests__/components/editor/property/InputLookupQA.test.js
__tests__/components/editor/property/InputLookupSinopia.test.js
__tests__/components/editor/property/renderTypeaheadFunctions.test.js
src/components/editor/property/InputListLOC.jsx

Add ability to use literal value on InputListLOC component; DRY tests

---

__tests__/GraphBuilder.test.js
src/GraphBuilder.js

Only include the top level hasResourceTemplate assertion in the graph

---

src/components/search/Search.jsx

Change help working for search.

---

static/searchConfig.json

Add discogs as search authority

---

__tests__/components/editor/CopyToNewButton.test.js
__tests__/components/editor/Editor.test.js
__tests__/components/editor/PreviewButton.test.js
__tests__/components/editor/SaveAndPublishButton.test.js
__tests__/integration/previewSaveIncompleteResource.test.js
__tests__/integration/previewSaveResource.test.js
__tests__/integration/validationErrors.ppt.js
src/components/editor/CopyToNewButton.jsx
src/components/editor/Editor.jsx
src/components/editor/PreviewButton.jsx
src/components/editor/RDFModal.jsx
src/components/editor/SaveAndPublishButton.jsx
src/styles/main.css

Improve editor actions design

---

__tests__/components/editor/SaveAlert.test.js
src/components/editor/SaveAlert.jsx

Hooks  are the new react-redux way

Use selector hook rather than higher order component

---

__tests__/components/menu/CanvasMenu.test.js
src/components/menu/CanvasMenu.jsx

Adds aria-label for close button on CanvasMenu

---

__tests__/components/editor/CopyToNewButton.test.js
__tests__/components/editor/CopyToNewMessage.test.js
__tests__/components/editor/ExpiringMessage.test.js
__tests__/components/editor/SaveAlert.test.js
__tests__/integration/previewSaveIncompleteResource.test.js
__tests__/integration/previewSaveResource.test.js
__tests__/reducers/inputs.test.js
src/components/editor/CopyToNewButton.jsx
src/components/editor/CopyToNewMessage.jsx
src/components/editor/ExpiringMessage.jsx
src/components/editor/SaveAlert.jsx
src/reducers/index.js
src/reducers/inputs.js
src/store.js

This aligns CopyToNewMessage and SaveAlert
Fixes #1398

Extract ExpireMessage

---

__tests__/components/load/LoadByRDFForm.test.js
__tests__/integration/loadRDF.ppt.js
src/components/editor/property/InputLookupQA.jsx
src/components/load/LoadByRDFForm.jsx

Clarifies what types of RDF can be loaded.

---

README.md

Requirement for open source accounts, see https://www.browserstack.com/open-source

Update readme to add browserstack logo

---

static/authorityConfig.json

Adding Cultural Heritage Organizations as Direct Lookup

Adding Cultural Heritage Organizations

---

__tests__/components/editor/ResourceURIMessage.test.js
src/components/editor/ResourceURIMessage.jsx

Adds copy uri button.

---

__tests__/components/editor/SaveAndPublishButton.test.js
__tests__/components/editor/property/InputListLOC.test.js
__tests__/components/editor/property/InputLiteral.test.js
__tests__/integration/previewSaveIncompleteResource.test.js
__tests__/integration/previewSaveResource.test.js
__tests__/reducers/index.test.js
__tests__/reducers/inputs.test.js
__tests__/test_utilities/testUtils.js
src/actions/index.js
src/components/editor/SaveAndPublishButton.jsx
src/reducers/index.js
src/reducers/inputs.js

Fixes display of validation errors and availability of save button.

---

__tests__/components/editor/Alert.test.js
__tests__/components/editor/Editor.test.js
src/components/Alert.jsx
src/components/editor/Editor.jsx
src/components/editor/ErrorMessages.jsx
src/components/editor/property/PropertyComponent.jsx
src/components/load/LoadByRDFForm.jsx
src/components/search/QASearchResults.jsx
src/components/search/Search.jsx
src/components/search/SinopiaSearchResults.jsx

Extract an Alert component

---

__tests__/ResourceStateBuilder.test.js
__tests__/__fixtures__/genreForm.json
__tests__/fixtureLoaderHelper.js
src/ResourceStateBuilder.js

Rather than guessing based on triples.
closes #1516

For building resource state, determine property type from property template

---

__tests__/components/editor/property/InputURI.test.js
src/components/editor/property/InputURI.jsx

Fix for embedding InputURI.

---

package-lock.json
package.json
src/components/App.jsx

Add the environment to the page title

---

__tests__/components/search/Search.test.js
src/components/search/SinopiaSearchResults.jsx

Fixes display table of Sinopia search results in Development.

Use label instead of title in Sinopia Search Results

---

__tests__/components/editor/property/InputLang.test.js

This is failing for me locally.

Fix to InputLang test.

---

__tests__/__fixtures__/multiple_valuetemplaterefs.json
__tests__/actionCreators/resourceTemplates.test.js
__tests__/actionCreators/resources.test.js
__tests__/reducers/index.test.js
src/actionCreators/resourceTemplates.js
src/actionCreators/resources.js
src/reducers/index.js

* Changes fetchResourceTemplate to try to get RT from state before retrieving from server.
* Changes reducers to add new RT to state rather than overwriting all.

fetchResourceTemplate and reducer changes

---

__tests__/components/editor/RDFDisplay.test.js
__tests__/components/editor/property/InputListLOC.test.js
__tests__/components/editor/property/InputLiteral.test.js
__tests__/components/editor/property/InputURI.test.js
__tests__/integration/copyQASearchResult.test.js
__tests__/integration/previewSaveIncompleteResource.test.js
__tests__/integration/previewSaveResource.test.js
__tests__/test_utilities/testUtils.js
src/components/editor/RDFDisplay.jsx
src/components/editor/RDFModal.jsx
src/components/editor/ResourceTemplate.jsx

Adds component for rendering RDF in pleasing formats.

---

src/components/Header.jsx
src/styles/main.css

This gets it looking like it did in BS3. Fixes #1567

Update header for bootstrap 4

---

__tests__/components/editor/Editor.test.js

Should fix currently failing test on master

Adding setupModal to Editor test

---

src/components/templates/SinopiaResourceTemplates.jsx

Changed rt messages from comma separated to ul.

---

__tests__/components/templates/SinopiaResourceTemplates.test.js
src/components/templates/ResourceTemplateRow.jsx
src/components/templates/SinopiaResourceTemplates.jsx

Add sorting to the ResourceTemplate table

---

src/components/templates/ImportResourceTemplate.jsx

Remove unnecessary )

---

__tests__/actionCreators/search.test.js
__tests__/components/search/Search.test.js
__tests__/components/search/SinopiaSearchResults.test.js
__tests__/components/search/SinopiaSort.test.js
__tests__/sinopiaSearch.test.js
src/actionCreators/search.js
src/actions/index.js
src/components/search/SinopiaSearchResults.jsx
src/components/search/SinopiaSort.jsx
src/reducers/search.js
src/sinopiaSearch.js
src/store.js

Adds SinopiaSort component to support sorting Sinopia search results.

---

__tests__/components/templates/ImportResourceTemplate.test.js
src/components/templates/ImportResourceTemplate.jsx

suppress flash error message on re-upload of existing profile

---

__tests__/ResourceTemplateValidator.test.js
__tests__/__fixtures__/ld4p_RT_bf2_RareMat_RBMS.json
__tests__/__fixtures__/nonUniqueValueTemplateRefs.json
__tests__/actionCreators/resources.test.js
__tests__/fixtureLoaderHelper.js
__tests__/fixtureLoaderHelper.test.js
__tests__/sinopiaServer.test.js
src/ResourceTemplateValidator.js

Validates that value template refs must have unique property URIs.

---

src/components/templates/SinopiaResourceTemplates.jsx

Scroll to top to when resource template error.

---

__tests__/sinopiaSearch.test.js
src/sinopiaSearch.js

Adds searching text field and weights fields.

---

__tests__/components/editor/property/PropertyLabelInfoTooltip.test.js
__tests__/integration/nestedResources.test.js
src/components/editor/property/PropertyLabelInfoTooltip.jsx

Fixes popovers.

---

__tests__/components/search/Search.test.js
__tests__/components/search/SinopiaSearchResults.test.js
cypress/integration/end2end.spec.js
src/components/editor/CopyToNewButton.jsx
src/components/search/SinopiaSearchResults.jsx
src/reducers/entities.js
src/sinopiaSearch.js
src/styles/main.css

Implements design of new Sinopia Search Results table as illustrated in #1412 
Fixes #1412

Sinopia Search Results Improvments

---

src/components/search/SinopiaSearchResults.jsx

Re: @justinlittman comment https://github.com/LD4P/sinopia_editor/pull/1612#discussion_r338733789 on merged PR.

Replaces shortid for row uri in Sinopia search results row

---

__tests__/components/ResourceTemplateChoiceModal.test.js
__tests__/components/load/LoadByRDFForm.test.js
__tests__/components/search/QASearchResults.test.js
__tests__/components/search/Search.test.js
__tests__/integration/copyQASearchResult.test.js
__tests__/reducers/inputs.test.js
src/actions/index.js
src/components/ResourceTemplateChoiceModal.jsx
src/reducers/index.js
src/reducers/inputs.js
src/store.js

Because I like throwing away code.

Cleans up modal state.

---

src/components/editor/RDFModal.jsx

RDF Modal's body is now scrollable for a resource with many triples

---

__tests__/components/editor/RDFModal.test.js

Tests Save button for RDFModal

---

src/components/editor/ResourceTemplate.jsx

Fixes alert overlap in editor.

---

__tests__/components/ModalWrapper.test.js
src/components/ModalWrapper.jsx
src/components/ResourceTemplateChoiceModal.jsx
src/components/editor/GroupChoiceModal.jsx
src/components/editor/RDFModal.jsx
src/components/templates/UpdateResourceModal.jsx

New useModalCss hook for Modals

---

__tests__/components/templates/ImportFileZone.test.js
__tests__/integration/schemaValidation.test.js
src/components/templates/ImportFileZone.jsx

Changed text of Import button

---

src/components/App.jsx

Clicking on the "Help and Resources" does not open the offset menu on some pages.
I attempted to write a useful test for this, but was not able to because the offset menu handling is in the root component.

Fixes help menu rendering.

---

__tests__/ResourceTemplateValidator.test.js
__tests__/__fixtures__/blankValueTemplateRefs.json
__tests__/fixtureLoaderHelper.js
src/ResourceTemplateValidator.js

ignore blank resource template IDs in profile files when validating

---

src/components/search/Search.jsx

Update help text for Sinopia search

---

package-lock.json

Ran `npm audit fix` to get this.

Upgrade handlebars to 4.5.1

---

src/components/search/Search.jsx

similar to #1607 but for search results page (so the user can see the error message if it occurs on a page with lots of search results)

scroll to top of page on a search error

---

__tests__/components/App.test.js
__tests__/components/templates/ImportResourceTemplate.test.js
__tests__/components/templates/UpdateResourceModal.test.js
__tests__/integration/copyQASearchResult.test.js
__tests__/integration/misconfiguredPropertyTemplate.test.js
__tests__/integration/nestedResources.test.js
__tests__/integration/previewSaveIncompleteResource.test.js
__tests__/integration/previewSaveResource.test.js
__tests__/integration/schemaValidation.test.js
src/actions/flash.js
src/components/search/Search.jsx
src/components/templates/CreateResourceMessages.jsx
src/components/templates/ImportResourceTemplate.jsx
src/components/templates/UpdateResourceModal.jsx
src/reducers/flash.js
src/reducers/index.js
src/reducers/modals.js
src/selectors/flashSelectors.js
src/store.js

This will enable ImportResourceTemplate to be made functional.

 Move flash messages to redux state 

---

cypress/integration/helpAndResources.spec.js

Add a Cypress spec for the help and resources tab

---

__tests__/actionCreators/resourceTemplates.test.js
__tests__/components/templates/ImportFileZone.test.js
__tests__/components/templates/ImportResourceTemplate.test.js
__tests__/components/templates/UpdateResourceModal.test.js
__tests__/integration/previewSaveResource.test.js
__tests__/integration/schemaValidation.test.js
src/actionCreators/resourceTemplates.js
src/components/templates/ImportFileZone.jsx
src/components/templates/ImportResourceTemplate.jsx
src/components/templates/UpdateResourceModal.jsx

Move importing logic to a thunk

Make ImportResourceTemplate a functional component

---

package-lock.json
package.json
src/components/search/SinopiaSearchResults.jsx
src/components/templates/ResourceTemplateRow.jsx
src/index.js

Add relative time

---

__tests__/components/editor/property/InputListLOC.test.js
__tests__/components/editor/property/InputLookupSinopia.test.js
src/components/ResourceTemplateChoiceModal.jsx
src/components/editor/property/InputListLOC.jsx
src/components/editor/property/InputLookupQA.jsx
src/components/editor/property/InputLookupSinopia.jsx

Remove 'required' prop from Typeahead components

---

__tests__/ResourceTemplateValidator.test.js
__tests__/__fixtures__/notFoundValueTemplateRefsURI.json
__tests__/fixtureLoaderHelper.js
src/ResourceTemplateValidator.js

fixes (or rather prevents from happening again) #1670

add new validator for authority lookup uri existence

---

__tests__/actionCreators/resourceTemplates.test.js
src/actionCreators/resourceTemplates.js

Update the resource template cache on overwrite

---

src/ResourceTemplateValidator.js

Add missing comma dangle

---

__tests__/sinopiaSearch.test.js
src/sinopiaSearch.js

Returns better error message if client cannot connect to backend

---

__tests__/actionCreators/resourceTemplates.test.js
__tests__/actionCreators/resources.test.js
__tests__/components/templates/SinopiaResourceTemplates.test.js
__tests__/reducers/resourceTemplates.test.js
cypress/integration/end2end.spec.js
src/actionCreators/resourceTemplates.js
src/actions/index.js
src/components/templates/ImportResourceTemplate.jsx
src/components/templates/ResourceTemplateSearchResult.jsx
src/components/templates/SinopiaResourceTemplates.jsx
src/reducers/index.js
src/reducers/resourceTemplates.js
src/store.js
src/styles/main.css

List most recently used resource templates

---

__tests__/components/search/Search.test.js
__tests__/components/search/SinopiaSort.test.js
__tests__/sinopiaSearch.test.js
src/actionCreators/search.js
src/sinopiaSearch.js

Rather than a large number of individual params.

Switches Sinopia search to take options param.

---

__tests__/actionCreators/resourceTemplates.test.js
__tests__/actionCreators/resources.test.js
src/actionCreators/resourceTemplates.js
src/actionCreators/resources.js

Switches to only add template to history when opened by user.

---

__tests__/components/ModalWrapper.test.js
__tests__/components/editor/property/LanguageButton.test.js
src/components/ModalWrapper.jsx
src/components/editor/property/InputLang.jsx
src/components/editor/property/LanguageButton.jsx

T1739 fix language selection

---

__tests__/ResourceStateBuilder.test.js
__tests__/ResourceTemplateValidator.test.js
__tests__/actionCreators/resources.test.js
src/ResourceStateBuilder.js
src/ResourceTemplateValidator.js
src/actionCreators/resourceTemplates.js
src/actionCreators/resources.js
src/hooks/useResource.js

and handles the raised errors.

Adds resource template validation to Resource State Builder

---

__tests__/components/editor/property/InputLang.test.js
__tests__/components/editor/property/LanguageButton.test.js
src/components/editor/property/InputLang.jsx
src/components/editor/property/LanguageButton.jsx

Allow no language to be selected

---

src/components/search/Search.jsx

Added `marginTop` value to css.
Fixes #1761

CSS Fix for Search box

---

__tests__/GraphBuilder.test.js
__tests__/ResourceStateBuilder.test.js
__tests__/Utilities.test.js
__tests__/actionCreators/resources.test.js
__tests__/components/App.test.js
__tests__/components/editor/RDFDisplay.test.js
__tests__/components/editor/actions/CloseButton.test.js
__tests__/components/editor/actions/SaveAndPublishButton.test.js
__tests__/components/editor/property/InputLang.test.js
__tests__/components/editor/property/InputLiteral.test.js
__tests__/components/editor/property/InputValue.test.jsx
__tests__/components/load/LoadByRDFForm.test.js
__tests__/integration/loadRDF.ppt.js
__tests__/integration/previewSaveResource.test.js
__tests__/reducers/entities.test.js
__tests__/reducers/index.test.js
__tests__/selectors/resourceSelectors.test.js
cypress/integration/end2end.spec.js
src/Utilities.js
src/actionCreators/languages.js
src/components/load/LoadByRDFForm.jsx
src/reducers/entities.js
src/reducers/index.js
src/selectors/entitySelectors.js

Still need to see about how this handles old data.
Fixes #1230

Switch to using iso-639-2

---

__tests__/components/editor/property/OutlineHeader.test.js
__tests__/components/editor/property/PropertyActionButtons.test.js
__tests__/components/editor/property/PropertyTemplateOutline.test.js
__tests__/integration/addRemoveButtons.ppt.js
__tests__/integration/nestedResources.test.js
__tests__/integration/validationErrors.ppt.js
src/components/editor/property/OutlineHeader.jsx
src/components/editor/property/PropertyActionButtons.jsx
src/components/editor/property/PropertyPanel.jsx
src/styles/main.css

fixes #1457 and #1718 and #1455

changes to ui panel add and remove links

---

__tests__/components/search/SinopiaSearchResults.test.js
src/components/search/SinopiaSearchResults.jsx

Fixes display of institution in Sinopia search results.

---

__tests__/components/search/Search.test.js
src/components/search/Search.jsx
src/components/search/SinopiaSort.jsx

Retains sort order when paging search results.

---

__tests__/components/editor/RDFDisplay.test.js
src/components/editor/RDFDisplay.jsx

Adds language to RDF table preview.

---

src/components/Alert.jsx
src/components/Header.jsx
src/components/LoginPanel.jsx
src/components/editor/EditorActions.jsx
src/components/editor/ResourcesNav.jsx
src/components/search/QASearchResults.jsx
src/components/search/Search.jsx
src/components/search/SearchResultsMessage.jsx
src/components/search/SearchResultsPaging.jsx
src/components/search/SinopiaSearchResults.jsx
src/components/templates/DropZone.jsx
src/components/templates/ResourceTemplateSearchResult.jsx
src/components/templates/TemplateSearch.jsx
src/index.js

closes #1787
closes #1788
closes #1780

Set to fluid container and various layout related fixes.

---

__tests__/components/search/QASearchResults.test.js
src/components/search/QASearchResults.jsx

Adds context to QA search results.

---

src/styles/main.css

For some reason this branch was not correctly merged.

add underlines to all links

---

src/components/Footer.jsx

fix footer spacing

---

__tests__/components/search/QASearchResults.test.js
__tests__/components/search/SinopiaSearchResults.test.js
src/components/search/QASearchResults.jsx
src/components/search/SinopiaSearchResults.jsx

Normalize Class Column Names for Sinopia and QA search results

---

cypress/integration/helpAndResources.spec.js
src/components/RootContainer.jsx
src/styles/main.css

This allows us to use more screen real estate

Make the body margin fixed

---

src/components/search/SinopiaSearchResults.jsx

Fixed resource URI when loading resource from Sinopia search results.

---

__tests__/components/App.test.js
__tests__/components/editor/ResourceTemplate.test.js
__tests__/components/editor/property/PropertyResourceTemplate.test.js
__tests__/components/exports/Exports.test.js
__tests__/integration/addRemoveButtons.ppt.js
__tests__/integration/multipleResources.test.js
__tests__/integration/verifyTemplateTitle.ppt.js
cypress/integration/end2end.spec.js
src/components/Header.jsx
src/components/editor/ResourceTemplate.jsx
src/components/editor/ResourceURIMessage.jsx
src/components/editor/property/PropertyResourceTemplate.jsx
src/components/exports/Exports.jsx
src/components/home/DescPanel.jsx
src/components/home/NewsItem.jsx
src/components/load/LoadByRDFForm.jsx
src/styles/main.css

Adjust font sizes.

---

src/components/templates/SinopiaResourceTemplates.jsx

Result list header

---

src/components/editor/ResourcesNav.jsx
src/styles/main.css

Styles resource tabs.

---

__tests__/components/App.test.js
__tests__/components/Header.test.js
__tests__/components/LoginPanel.test.js
__tests__/integration/loginHelper.js
cypress/integration/end2end.spec.js
cypress/integration/helpAndResources.spec.js
src/components/Header.jsx
src/components/LoginPanel.jsx
src/styles/main.css

Implements new header design.

---

__tests__/components/templates/SinopiaResourceTemplates.test.js
index.html
package-lock.json
package.json
src/components/App.jsx
src/components/editor/actions/CloseButton.jsx
src/components/templates/Download.jsx
src/index.js
src/styles/main.scss
webpack.config.js

Change button style

---

__tests__/components/editor/ResourceTemplate.test.js
__tests__/components/editor/property/ResourceList.test.js
src/components/editor/ResourceTemplate.jsx
src/components/editor/property/InputLookupSinopia.jsx
src/components/editor/property/ResourceList.jsx

Creates links to new resources for InputLookupSinopia Components

---

__tests__/components/editor/ResourcesNav.test.js
src/components/editor/ResourcesNav.jsx
src/components/editor/actions/CloseButton.jsx

Close button for Resource Templates Tab

---

__tests__/components/templates/Download.test.js
__tests__/components/templates/SinopiaResourceTemplates.test.js
src/components/editor/actions/CopyToNewButton.jsx
src/components/editor/actions/PreviewButton.jsx
src/components/search/QASearchResults.jsx
src/components/search/SinopiaSearchResults.jsx
src/components/templates/Download.jsx
src/components/templates/ResourceTemplateSearchResult.jsx
src/styles/main.scss

Changed icon size. Added download icon.

---

__tests__/__fixtures__/DiscogsLookup.json
__tests__/components/editor/property/RenderLookupContext.test.js
__tests__/components/search/QASearchResults.test.js
__tests__/fixtureLoaderHelper.js
src/components/editor/property/RenderLookupContext.jsx
src/components/search/QASearchResults.jsx
src/utilities/QuestioningAuthority.js

QA is switching to use the same context format in non-LD result as LD results.

Removes special handling of non-LD QA results.

---

__tests__/components/editor/property/InputListLOC.test.js
src/components/editor/property/InputListLOC.jsx

Tokenize a single non-repeatable InputListLOC value

---

src/components/editor/property/PropertyPanel.jsx

Allow 3 column layout if on an extra large (>1140px) screen)

---

__tests__/components/editor/property/ResourceList.test.js
src/components/editor/property/ResourceList.jsx

ResourceList returns null if newResourceList is empty

---

__tests__/Utilities.test.js
src/Utilities.js
src/components/search/SearchResultRows.jsx
src/components/search/SinopiaSearchResults.jsx

Do this to remove a TODO from the codebase and to gain more experience doing this sort of work in React.

Extract a functional component for rendering search result rows

---

__tests__/components/editor/property/ResourceList.test.js
src/components/editor/property/RequiredSuperscript.jsx
src/components/editor/property/ResourceList.jsx
src/styles/main.scss

Also generalize and rename/reuse a class that adds margin-left to element.

Adds resource template ID after link label

---

__tests__/__fixtures__/multiple_loc.json
__tests__/components/editor/property/InputListLOC.test.js
__tests__/components/editor/property/InputLookup.test.js
__tests__/components/editor/property/renderTypeaheadFunctions.test.js
__tests__/utilities/QuestioningAuthority.test.js
package-lock.json
src/components/editor/property/InputListLOC.jsx
src/components/editor/property/InputLookup.jsx
src/components/editor/property/renderTypeaheadFunctions.js
src/utilities/QuestioningAuthority.js

Allow user to select lookups

---

src/components/search/QASearchResults.jsx

Handle when no QA results without erroring.

---

src/components/search/SinopiaSort.jsx

Switched sinopia sort to a right-alinged dropdown.

---

src/components/editor/ExpiringMessage.jsx

Scroll alert into view when saving

---

__tests__/sinopiaSearch.test.js
src/sinopiaSearch.js

Fixes InputLookupSinopia.

---

__tests__/components/editor/property/ResourceList.test.js
cypress/integration/end2end.spec.js
src/components/editor/property/ResourceList.jsx

Changes link list to dropdown list.

Change link list to dropdown list

---

__tests__/components/search/Search.test.js
__tests__/sinopiaSearch.test.js
src/components/search/GroupFilter.jsx
src/components/search/Search.jsx
src/components/search/TypeFilter.jsx
src/sinopiaSearch.js

Fixes for filtering Sinopia searches.

---

__tests__/components/templates/ImportFileZone.test.js
src/components/templates/ImportFileZone.jsx

Make import icon blue

---

__tests__/utilities/QuestioningAuthority.test.js

Mocked out QA in QuestioningAuthority.test.js.

---

src/Config.js

Increased the number of template results.

---

__tests__/components/editor/property/ResourceList.test.js
src/components/editor/property/ResourceList.jsx

Displays rt id instead of resource URI in Create New.

---

src/styles/main.scss

Changes secondary button style.

---

__tests__/components/home/LoginPanel.test.js
src/components/home/LoginPanel.jsx

Makes login error an alert.

---

src/components/editor/ResourceURIMessage.jsx

Cleanup timer in ResourceURIMessage.

---

__tests__/components/editor/RDFModal.test.js
src/components/editor/RDFModal.jsx

Increases width of RDF preview modal.

---

src/styles/main.scss

Changes active nav style.

---

__tests__/components/App.test.js
__tests__/components/home/Header.test.js
__tests__/test_utilities/testUtils.js
src/components/home/Header.jsx

Correctly limit header when no user session.

---

src/styles/main.scss

Allow multi typeaheads to resize.

---

src/components/editor/property/PropertyLabelInfoTooltip.jsx

Tighten up popovers.

---

src/components/search/QASearchResults.jsx

Fixes width of QA results table.

---

__tests__/components/search/QASearchResults.test.js
__tests__/components/search/Search.test.js
__tests__/components/search/SinopiaSearchResults.test.js
__tests__/integration/copyQASearchResult.test.js
src/components/search/QASearchResults.jsx
src/components/search/SearchResultRows.jsx
src/components/search/SinopiaSearchResults.jsx

Adds URI to Sinopia and QA results.

---

__tests__/components/search/QASearchResults.test.js
src/components/search/QASearchResults.jsx

Adds images for QA results.

---

__tests__/components/editor/property/InputLookupQA.test.js
src/components/editor/property/InputLookupQA.jsx

Fix InputLookQA for new QA result format.

---

__tests__/GraphBuilder.test.js
src/GraphBuilder.js

Adds testing for content in GraphBuilder when items is an empty object

---

src/components/editor/property/InputLang.jsx

Makes language selection buttons consistent with other modals.

---

__tests__/actionCreators/search.test.js
src/actionCreators/search.js

Fixes QA error message.

---

__tests__/actionCreators/resources.test.js
__tests__/components/editor/actions/CloseButton.test.js
__tests__/components/editor/actions/SaveAndPublishButton.test.js
__tests__/selectors/resourceSelectors.test.js
src/actionCreators/resources.js
src/selectors/resourceSelectors.js

Revert to using toCanonical() resource changed checking

---

__tests__/integration/tabsContentChanges.test.js
src/components/editor/actions/CloseButton.jsx

Think this Fixes #2052 (but needs additional testing to confirm)

Close Button sets resourceKey based on props or currentResource 

---

package-lock.json
package.json

Tagged version bump to 2.0.6

---

__tests__/components/editor/property/InputLang.test.js

InputLang.test.js now passing

---

package-lock.json
package.json

Version 2.0.14

---

src/components/templates/ImportFileZone.jsx

Checks for indexOf property

---

package-lock.json
package.json

Version 2.0.17

---

package-lock.json
package.json

Fixes #2147 at least until bootstrap 4.4.2 is released.

Set jquery to version 3.4.1

---

package-lock.json
package.json

Bug fix by setting `jquery` to version 3.4.1.

Version 2.0.18

---

package-lock.json
package.json

Version bump 2.0.19

---

package-lock.json
package.json

Fixed regression bug by upgrading to jquery 3.5.1

---

__tests__/actionCreators/resources.test.js
src/actionCreators/resources.js

Use Canonical RDF for generating checksum

---

__tests__/components/editor/actions/CloseResourceModal.test.js
__tests__/integration/multipleResources.test.js
src/components/editor/actions/CloseButton.jsx
src/components/editor/actions/CloseResourceModal.jsx

Refactor CloseResourceModal to use state for clearing resource

---

static/authorityConfig.json

Brings fix for https://github.com/LD4P/sinopia_profile_editor/issues/345 into Sinopia's config as well.

add subauths to uri’s for CERL

---

package-lock.json
package.json

Version 2.0.23

---

package-lock.json
package.json

Dependency and security updates

Version 2.0.25

---

package-lock.json
package.json

Version 2.0.26 

---

package-lock.json
package.json

Updated version to 2.0.27

---

package.json

To force circle-ci cache refreshing

Added email to contributor

---

Dockerfile.cypress
package-lock.json
package.json

Should fix errors we've been seeing in failing Circle-CI builds.

Update puppeteer to latest and pins Cypress Image

---

package-lock.json
package.json

Version bump to 2.0.28

---

package-lock.json
package.json

Version bump for dependency updates

Version 2.0.29

---

__tests__/__fixtures__/uber_template1.json
__tests__/feature/editing/editingUri.test.js
src/components/editor/property/InputURI.jsx

Added test for editing URI.

---

__tests__/matchers/templates.js
__tests__/selectors/templates.test.js
package.json

Added test for template selectors.

---

__tests__/reducers/messages.test.js

Adds tests for `reducer/messages.js` fixes #2248

Adds tests for reducer/messages module

---

src/components/editor/ResourceComponent.jsx
src/components/editor/property/InputLang.jsx
src/components/editor/property/InputListLOC.jsx
src/components/editor/property/InputLiteral.jsx
src/components/editor/property/InputLookup.jsx
src/components/editor/property/InputLookupQA.jsx
src/components/editor/property/InputLookupSinopia.jsx
src/components/editor/property/InputURI.jsx
src/components/editor/property/InputValue.jsx
src/components/editor/property/LanguageButton.jsx
src/components/editor/property/NestedProperty.jsx
src/components/editor/property/NestedPropertyHeader.jsx
src/components/editor/property/NestedResource.jsx
src/components/editor/property/NestedResourceActionButtons.jsx
src/components/editor/property/PanelProperty.jsx
src/components/editor/property/PanelResource.jsx
src/components/editor/property/PropertyComponent.jsx
src/components/editor/property/PropertyLabel.jsx
src/components/editor/property/ResourceList.jsx

As getting them from state is now kinda expensive.

Push properties rather than get from state.

---

__tests__/reducers/resources.test.js

Tests `reducers/resources.js`, fixes #2250

Tests for Resource Reducers

---

src/actionCreators/resourceHelpers.js

Fix to loading resources.

---

__tests__/TemplatesBuilder.test.js
__tests__/__template_fixtures__/uber_template1.json
__tests__/feature/loadNewResource.test.js
src/components/editor/property/InputValue.jsx

Fix display of URI labels

---

__tests__/feature/editing/addRemove.test.js
src/components/editor/property/PanelProperty.jsx

Removes remove button for required panel properties.

---

__tests__/GraphBuilder.test.js
__tests__/TemplatesBuilder.test.js
__tests__/__action_fixtures__/newResource-ADD_SUBJECT.json
__tests__/__action_fixtures__/newResourceFromN3-ADD_SUBJECT.json
__tests__/__template_fixtures__/uber_template1.json
__tests__/__template_fixtures__/uber_template4.json
__tests__/actionCreators/resources.test.js
__tests__/feature/editing/editingLiteral.test.js
__tests__/feature/editing/editingUri.test.js
__tests__/feature/loadNewResource.test.js
__tests__/feature/loadRDF.test.js
__tests__/testUtilities/fixtureLoaderHelper.js
src/GraphBuilder.js
src/actionCreators/resourceHelpers.js
src/actionCreators/resources.js

Also, stops adding empty nested resources to graph.
closes #2305

Fixes expanding of required properties.
