LD4P/sinopia_editor

.eslintrc.js
Gruntfile.js
package-lock.json
package.json

~~WIP:  please merge #11 first!~~
This adds the eslint task to the Grunt file.
I think we will have grunt tasks like:
- `ci` (runs linter and tests)
- `build` - prepares code for deployment
- ...
so I am not adding eslint to the default task.
Connects to #2

add eslint task and packages

---

.gitignore
Gruntfile.js
package-lock.json
package.json

Is "jest-coverage" too long for the npm script name?  Should it be "jest-cov"?  That script is only used by the grunt file in a task named "test-cov" ...
Note that test fails.  My intent is to:
- hook up CI next (#3)
- get test passing (#16)
Closes #1

add jest along w npm and grunt way to run it

---

.circleci/config.yml
.gitignore
Gruntfile.js
README.md
__tests__/bfe.test.js
jest.config.js
package-lock.json
package.json

Note especially 1a8ec24 and e0e6da7 as they allow us to use circleci's "test summary" section (which may be useless) and also allow us to see code coverage via circle ci, e.g. 
- https://15-149367347-gh.circle-artifacts.com/0/jest-coverage/lcov-report/index.html
- https://12-149367347-gh.circle-artifacts.com/0/jest-coverage/lcov-report/index.html
^^ note url starts with circleci build number;  note further that the test does nothing -- ticket to fix that is #16
I had to make the test pass so the "test summary" section had a file to work with.
Closes #3

circleci hook up 

---

package.json

Closes #21
Note that if this is merged after #20 then I can rebase and then the no-op circleci test won't fail.  ;-)

package.json: fix descriptive metadata

---

package-lock.json
package.json

also uses the released version of grunt-contrib-uglify-es instead of the one from git.
Closes #13 
note upstream PR is lcnetdev/bfe#43

npm grunt-contrib packages are dev dependencies

---

.circleci/config.yml
package.json

In keeping with sinopia_profile_editor.

circleci runs grunt as step; removed from jest-ci npm script

---

.circleci/config.yml
.eslintignore
.eslintrc.js
package-lock.json
package.json
src/bfelookups.js
src/lib/aceconfig.js

Adds eslint and hooks it up with CI build.  It would be good for both @jgreben and @jermnelson to review.
We have to start somewhere. This is a pretty bad place to start ... but it is a way to have our CI builds fail if we have an eslint error, or if the warning count goes up.
As we start refactoring and changing code, we'll need to adjust the max-threshold for eslint script in package.json:
I felt a few linting errors were worth keeping as errors (not warnings), so I have some small tweaks to files to address these errors from linting.
595070d, the commit moving express to be a regular dependency, not a devDependency *seems* right - we need express to actually run the javascript for a user, no?  "Express is a minimal and flexible Node.js web application framework that provides a robust …

CI build includes eslint, which will fail on errors or additional warnings

---

.circleci/config.yml
.circleci/setup_puppeteer.sh

I found out that we can avoid that setup_puppeteer.sh script by using a circle/node docker image that already has chromedriver installed. W00t!
Fixes #32

circleci uses appropriate docker image

---

.eslintignore

discovered this problem running it locally - gah.  Luckily static analysis runs last in circleci.

.eslintignore: add static-analysis directory

---

__tests__/__fixtures__/admin.json
__tests__/__fixtures__/agents_contribution_profile.json
__tests__/__fixtures__/agents_primary_contrib_profile.json
__tests__/__fixtures__/agents_profile.json
__tests__/__fixtures__/edition_info_profile.json
__tests__/__fixtures__/form_profile.json
__tests__/__fixtures__/identifiers_profile.json
__tests__/__fixtures__/item.json
__tests__/__fixtures__/language_profile.json
__tests__/__fixtures__/monograph_profile.json
__tests__/__fixtures__/note_profile.json
__tests__/__fixtures__/place_profile.json
__tests__/__fixtures__/pub_profile.json
__tests__/__fixtures__/related_profile.json
__tests__/__fixtures__/title_profile.json
__tests__/__fixtures__/topic_profile.json

I added a bunch of profiles from https://github.com/lcnetdev/verso/tree/master/data/profiles
some minor concerns:
- I took most, but not all.  (not maps, not call numbers, not media, not notated music, not prints and photographs, not rare materials, not serials ...). I assume that's going to be okay for testing.
- I didn't keep the really long names ... do we care?
- I reformatted the JSON to have 2 spaces indentation ... any concern with upstream changes (I don't expect any)
- There is no way to comment in JSON, so there is no way to attribute the fixture data.
- It's often not a good thing to have fixtures you don't end up using.  But it seems handy to have a bunch of them for now.  Not sure how else to proceed easily with e2e tests, working in parallel.
Closes #48

add profile fixtures to __tests__/__fixtures__

---

__tests__/integration/browse.test.js

Actually, the tests were about the browse functionality, and they are currently just showing the datatable is loaded.
When the datatable is loaded, it contains data, not profiles.

tweak browse test descriptions

---

.eslintrc.js
__tests__/__fixtures__/instance_ontology.json
__tests__/__fixtures__/verso_profile_response_short.json
__tests__/integration/index.html
__tests__/integration/profilesLoad.test.js
__tests__/integration/test-config.js
jest-puppeteer.config.js
package.json

Aside from writing the test code itself, this involved:
- adding some fixture json files to be accessed via local url
- a testing copy of config.js (__tests__/integration/test-config.js)
- changes hardcoded url for config.profiles from verso to localhost for short(er) profiles fixture json
- changes the hardcoded url in "retrieve" function to localhost for instance ontology fixture json
- a testing copy of index.html using test-config.js
- turning off web security (CORS) when running puppeteer in order to be able to get localhost json
- tweaked eslint globals (got busted on my test code!)
This approach is brittle on a few counts:
- test-config.js will drift from actual config.js
- test index.html will drift from actual index.html
- hardcoding only allows retrieval of bibframe instance …

integration test can affirm that profile is loaded

---

__tests__/integration/editorTab.test.js

Checks for initial hard-coded profiles menu in the editor tab as a startingPoint.  Monograph, Prints and Photographs,  and Authorities sub-menus are also tested.
Fixes #52

Editor tab testing of default profile menu and submenus

---

package.json

Notice the lockfile doesn't change because serve-static is still an *indirect* dependency via `express` framework.
Fixes #25

Remove serve-static from direct dependencies

---

package-lock.json

Fix security alert from Github about updating version of `merge` used in package-lock.json.

Updating merge version 

---

Gruntfile.js
README.md
bfe-index.html
jest-puppeteer.config.js
package.json
server.js

- Renamed `server-bfe.js` to `server.js` to be more standard
- Restored original `index.html` as `bfe-index.html` for an easy way to look at BFF while we work on getting react trappings
- added npm `install-build` script and sorted scripts by name in package.json
- updated README
Closes #66

server.js, bfe-index.html and other housekeeping

---

.dockerignore

Current root directory from container looks like:
```
$ docker exec 92c1bc4bd9d1 ls -a
.
..
.babelrc
.circleci
.eslintignore
.eslintrc-todo.yml
.eslintrc.js
.eslintrc.yml
.git
.gitignore
Dockerfile
Gruntfile.js
LICENSE.txt
README.md
__mocks__
__tests__
bfe-index.html
build_support
builds
coverage
dist
docs
index.html
jest-puppeteer.config.js
junit.xml
node_modules
package-lock.json
package.json
server.js
setupEnzyme.js
src
static
static-analysis
webpack.config.js
```
About half of that is stuff we don't want in the container.

use .dockerignore file to exclude unwanted files

---

.circleci/config.yml
.dockerignore

The container will only include the webpack artifacts, not the legacy grunt artifacts.
The built container now contains the same files that webpack produces in`dist`:
```
docker pull ld4p/sinopia_editor
docker run ld4p/sinopia_editor ls dist
42e18bb8ebabfb8bcfd5967540c0b88e.png
b62e74f0c408aa3c9a20fc0e71b16e9a.png
bundle.js
index.html
```
This relates to #28
Fixes #106

Include "dist" for container, not "builds"

---

__tests__/components/editor/ValueConstraints.test.js
src/components/editor/Editor.jsx
src/components/editor/PropertyTemplate.jsx
src/components/editor/ValueConstraints.jsx

Fixes #123 
- adds carrier property to static resource template json in Editor.jsx
- adds a new `<ValueConstraints />` component with sub-components:
- `<ValueTemplateRefs />`
- `<UseValuesFrom />`
- `<ValueDataTypes />`
- `<Defaults />`
- function to check whether a hash has a key/value pair, used for conditional display
- test that uses enzyme full rendering with `mount` and a way to test a component's properties directly.

Adds components to render resource template value constraint properties

---

__tests__/sinopiaServerSpoof.test.js
src/components/editor/Editor.jsx
src/sinopiaServerSpoof.js
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/MonographInstance.json
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/MonographWork.json
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/Note.json
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/ParallelTitle.json
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/Title.json
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/TitleNote.json
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/TranscribedTitle.json
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/VarTitle.json
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/WorkTitle.json
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/WorkVariantTitle.json

spoof calls to sinopiaServer to retrieve a resource template with a data structure that gets appropriate JSON from files in our `static` directory.  
Note that the approach taken here works for our tests, works for running the webpack server, and works when we run the express server as well.
Eventually, we will want to make an HTTP request out to the sinopia server, presumably using "fetch" or "axios" and we will have to figure out how to deal with the async nature of that call while rendering components.
Closes #125

Spoof resource templates from server

---

__tests__/components/App.test.js

Unmount `renderRoutes` component in the App.test.js. 
Fixes #131

Unmounts renderRoutes component in App.test.js

---

__tests__/components/editor/Editor.test.js
__tests__/components/editor/Header.test.js
src/components/editor/Editor.jsx
src/components/editor/Header.jsx

Fixes #145 
The cool thing was that WebStorm made all the changes for me. All I had to do was drop and drag the file...

Moves EditorHeader component to component 'editor' folder

---

package-lock.json
package.json

We are now primed to keep track of coverage on current and all new `.jsx` and `.js` files.
NOTE:  after this is merged to master, we need to configure coveralls.io to fail if coverage goes below 80%.  Ask Naomi to show you.
Isn't this a much better picture?  https://coveralls.io/builds/20136858
Or, if you prefer:  https://604-149367347-gh.circle-artifacts.com/0/jest-coverage/lcov-report/index.html
Closes #168

BFF: Fix code coverage

---

.eslintignore
.eslintrc.js
__tests__/components/Header.test.js
__tests__/components/editor/ResourceTemplate.test.js
package.json
src/components/Header.jsx
src/components/editor/PropertyTemplate.jsx
src/components/editor/ResourceTemplate.jsx

I had eslint ignore the BFE code, and then I fixed our eslint configuration to include jsx files and use the plugins that we've npm installed, specifically jsx-a11y (accessibility) and security ... and react, now that jsx files are in play.   Even with the new configuration, our warnings went down to 86 or so, so I dialed that max down for our CI builds.
Next I addressed some simple a11y rule violations, and turned off the rule that cares about semicolons (not worth our time to be 100% conformant).
This PR has many commits, but they are all small.  I recommend reviewing by commit.
Note that THESE eslint rules tell us useful stuff in the warnings.   It caused me to create 4 tickets:  #172, #173, #174, #175 -- each is referenced by a bespoke rule configuration in .eslintrc.js

make eslint more useful

---

__tests__/components/editor/FormWrapper.test.js
__tests__/components/editor/ResourceTemplate.test.js
src/components/editor/FormWrapper.jsx
src/components/editor/ResourceTemplate.jsx

hopefully this will make it easier for us to add modals / text fields / buttons when needed. This is essentially the properties wrapper, just broken out into a new component. I named it the `FormWrapper` but happy to take naming suggestions.
closes #178

Use FormWrapper instead of PropertiesWrapper

---

.circleci/config.yml

No one looks at these on circleci;  the coverage is available via coveralls (and let's us fail builds on reduced coverage from there) and the static analysis can be generated locally (as can coverage, for that matter).

circleci: don't do static code analysis and don't store coverage or analysis artifacts

---

__tests__/components/editor/FormWrapper.test.js
__tests__/components/editor/InputLiteral.test.js
package.json
src/components/editor/FormWrapper.jsx
src/components/editor/InputLiteral.jsx

In the resourceTemplate, takes care of `type: 'literal'` and `mandatory: 'false'` properties.
ResourceTemplate = 'resourceTemplate:bf2:Monograph:Instance'
Then when you change the resourceTemplate to resourceTemplate:bf2:WorkTitle:
paired w/ @jgreben 
closes #166 
Edit:
Here are the stubs depending on the ResourceTemplate- 
*Note*: updated eslint max warnings from 60 to 65

create input text field for propertyTemplate (Type literal)

---

__tests__/components/editor/ResourceTemplate.test.js
__tests__/sinopiaServerSpoof.test.js
package.json
src/components/editor/Editor.jsx
src/components/editor/FormWrapper.jsx
src/components/editor/ResourceTemplate.jsx
src/sinopiaServerSpoof.js

It turns out that the work to render individual form elements and the work to create modals both can benefit from making `getResourceTemplate` an importable function.  This enables that.  To use:
```javascript
const { getResourceTemplate } = require('../../sinopiaServerSpoof.js')
...
// Use how you wish:
this.state = { resourceTemplates: [getResourceTemplate('foo')]}
```

SinopiaServerSpoof: exports getResourceTemplate so it can be used anywhere

---

src/components/DescPanel.jsx

`<ul>` cannot appear as a descendant of `<p>`.

FIX Warning: validateDOMNesting(...): (UL cannot be child of <p> tag)

---

package.json

Given that we should now be:
- looking at eslint warnings/errors for every build ("did these changes add any?")
- looking at warnings from running tests (see below)
- considering code coverage when adding code
I thought it would be helpful to make a single npm script to run with all the steps we do in circleci.
`npm run ci`
e.g.: a warning from running "npm test" 
```
Warning: Each child in an array or iterator should have a unique "key" prop.
Check the render method of `FormWrapper`. See https://fb.me/react-warning-keys for more information.
in p (created by FormWrapper)
in FormWrapper (created by ResourceTemplate)
in div (created by ResourceTemplate)
in div (created by ResourceTemplate)
in ResourceTemplate (created by Editor)
in div (created by Editor)
in Editor (created by Route)
in …
```

add ci script to package.json so we can run it all locally in one step

---

__tests__/components/editor/InputLiteral.test.js
src/components/editor/InputLiteral.jsx

If repeatable is true you are able to input multiple values like:
And if you click on one of the items, we can remove it like:
If it is not repeatable you can only enter 1 value.
Created ticket #204 for CSS/styling.
closes #182

Repeatable mandatory input for type Literal

---

src/components/editor/Editor.jsx
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/MonographInstance.json

for all of our code to play nicely together and be exercised in tests, we need the temporarily hardcoded resource template from Editor to remain Monograph:Instance.
@jgreben this was blocking both Sarav and me, so I just did it.
@jermnelson this was from a quick merge ... oops.

Editor uses hardcoded rtid of resourceTemplate:bf2:Monograph:Instance

---

__tests__/components/editor/StartingPoints.test.js
__tests__/integration/StartingPoints.test.js
jest-puppeteer.config.js
package-lock.json
package.json
src/components/editor/StartingPoints.jsx

- Profile button toggles a div with a DropZone component
- DropZone opens a file dialog onClick, or you can drag and drop a file.
- cancelling the file dialog will toggle-close the DropZone component
- selected file names display at the bottom of the DropZone component section.
- removes the old Starting points text.
- Adds an integration test stub that does not work yet (jest with expect-puppeteer is still not playing nicely with enzyme and the configuration probably needs some more love ¯\_(ツ)_/¯ )

Adds a Profile button with DropZone to the StartingPoints section

---

.eslintrc.js
__tests__/__fixtures__/item.json
__tests__/components/editor/StartingPoints.test.js
__tests__/sinopiaServerSpoof.test.js
src/components/editor/Editor.jsx
src/components/editor/InputLiteral.jsx
src/components/editor/InputLookup.jsx
src/components/editor/InputResource.jsx
src/components/editor/ResourceTemplate.jsx
src/components/editor/StartingPoints.jsx
src/sinopiaServerSpoof.js
static/spoofedFilesFromServer/fromQA/classSchemes.json
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/DDC.json
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/Item.json
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/ItemAcqSource.json
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/ItemChronology.json
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/ItemEnumeration.json
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/ItemRetention.json
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/LCCN.json
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/Shelfmark.json

Fixes #228 
- Load resource template data from file and iterate through all RTs for render.
-- Adds a fixture file `item.json` for loading demo purposes.
- Adds new spoofed resource templates to go with the `item.json` profile.
- Use spread props for typeahead components
- Hide loading spinner by default for lookup/resource components
- allow `info` and `log` console messages

Adds file drop component functionality to starting points menu

---

package-lock.json
package.json
src/components/editor/InputLookup.jsx
src/lib/apidoc.json
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/MonographInstance.json

Fixes #197 
- Adds swagger-client library
- Uses swagger and local copy of QA apidoc to do authority search
- parses a colon-seperated useValuesFrom string to collect api params: vocab, subauthority, and language 
- note: language is not used with `locnames_ld4l_cache:person` but may be used with other authorities lookup that use the lookupComponent control

 Use swagger-js and local copy of QA apidoc.json to do authority lookup

---

__tests__/components/editor/InputList.test.js
__tests__/components/editor/ResourceTemplateForm.test.js
__tests__/reducers/list.test.js
__tests__/reducers/literal.test.js
package-lock.json
package.json
src/actions/index.js
src/components/editor/InputList.jsx
src/reducers/index.js
src/reducers/list.js

Fixes #259
- Combined reducer for list and literal components
- Changes InputList component to dispatch state to reducer action
- Tests for modified component and list reducer
- bumps up max-warnings to allow for security/detect-object-injection, but this is safe because user cannot inject anything in place of `var i` needed to parse the json to create the selection list

Input list redux

---

src/components/editor/InputList.jsx

In the InputList component, called non-existent method, `Object.getOwnPropertyDescription` fixed with correct method `Object.getOwnPropertyDescriptor`. Also need to adjust call to retrieve `@id` and label from the values array in the object.

Use correct Object method getOwnPropertyDescriptor

---

src/components/editor/InputLiteral.jsx

fixes :
checkPropTypes.js:19 Warning: Failed prop type: Invalid prop `id` of type `number` supplied to `InputLiteral`, expected `string`.

Update Proptype id

---

__tests__/components/editor/InputListLOC.test.js
__tests__/components/editor/InputLiteral.test.js
__tests__/components/editor/InputLookupQA.test.js
__tests__/components/editor/ResourceTemplateForm.test.js
src/components/editor/InputListLOC.jsx
src/components/editor/InputLookupQA.jsx
src/components/editor/ResourceTemplateForm.jsx
static/spoofedFilesFromServer/fromSinopiaServer/lookupConfig.json
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/MonographInstance.json

Fixes #284
Select input components and pass connection details as props based on template match to config details; Renamed Input components that do lookups

Use a json config doc to match template uris to component and connection details

---

__tests__/actions/index.test.js
__tests__/components/editor/ResourceTemplateForm.test.js
__tests__/reducers/rdf.test.js
package-lock.json
package.json
src/actions/index.js
src/components/editor/InputListLOC.jsx
src/components/editor/InputLiteral.jsx
src/components/editor/InputLookupQA.jsx
src/components/editor/ResourceTemplate.jsx
src/components/editor/ResourceTemplateForm.jsx
src/components/editor/ResourceTemplateModal.jsx
src/reducers/index.js
src/reducers/rdf.js

Starts support for generating a simple RDF graph for components and props in a `ResourceTemplateForm`.  
- New reducer generates RDF based on the based on the Redux stores for `InputList`, `InputLiteral`, and `InputLookup`. 
- Adds a new key, **rtId** for storing the `ResourceTemplate` id in `InputList`, `InputLiteral`, and `InputLookup`, this is used to scope the generation of triples to a single ResourceTemplate
- Uses [N3](https://github.com/rdfjs/N3.js) JS module for RDF manipulation. 
- New Preview RDF button displays a JS alert with the serialized graph in Turtle format. 
- All subjects are blank nodes
- Only works for `ResourceTemplateForm`s that are **NOT** embedded in a modal; issue is ticketed in #281. 
- Once #281 is completed, will need to return the blank node or uri to the …

Generate RDF from ResourceTemplateForm

---

src/components/editor/Editor.jsx

- Gets rid of hardcoded statement about which resource template was open (it never changed no matter what was opened)
- Make the top h1 of the page closer to what Astrid designed:

Editor.jsx: update heading to be closer to what we eventually want

---

__tests__/components/editor/StartingPoints.test.js
package-lock.json
package.json
src/components/editor/StartingPoints.jsx

Uses ajv for schema validation of resource template on import.   Results of validation are written to console;  nothing else is changed.
- Tests are incomplete as integration tests are required, and it was non-trivial to untangle that (see #301)  --> hence coverage drop.
Note that we also still need to:
- get schema url/$id from template being validated (#294)
- indicate template validity to user and adjust UX flow (#295)
- cache the schemas in local storage rather than doing a get each time (#292)
Closes #258  (????)

BFF does JSON schema validation of resource template on import

---

__tests__/components/editor/InputListLOC.test.js
__tests__/components/editor/InputLiteral.test.js
__tests__/components/editor/InputLookupQA.test.js
__tests__/components/editor/RequiredSuperscript.test.js
__tests__/components/editor/ResourceTemplateForm.test.js
package-lock.json
src/components/editor/InputListLOC.jsx
src/components/editor/InputLiteral.jsx
src/components/editor/InputLookupQA.jsx
src/components/editor/RequiredSuperscript.jsx
src/components/editor/ResourceTemplateForm.jsx
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/MonographInstance.json

In a ResourceTemplate, for all `literals`, `lookups`, and `resource` properties, if *mandatory* is set to "true", then displays a red asterisk (using FontAwesome) to indicate the component is required.
Changed for the following Components:
- InputLiteral, 
- InputLookupQA,
- InputListLOC
- ButtonToolbar in ResourceTemplateForm.
In the spoofed `MonographInstance` Resource Template, the *Instance Of*'s mandatory property is set to **true**:
Which generates the following label with a red asterisk:
This is work required to complete Issue #303. @astridu may want to look at adjust as needed for the final user interface.

Displays a FontAwesome Asterisk when a Property is Mandatory

---

__tests__/components/editor/InputListLOC.test.js
__tests__/components/editor/InputLiteral.test.js
__tests__/components/editor/InputLookupQA.test.js
__tests__/components/editor/PropertyRemark.test.js
__tests__/components/editor/ResourceTemplateForm.test.js
package.json
src/components/CanvasMenu.jsx
src/components/editor/InputListLOC.jsx
src/components/editor/InputLiteral.jsx
src/components/editor/InputLookupQA.jsx
src/components/editor/PropertyRemark.jsx
src/components/editor/ResourceTemplateForm.jsx
src/styles/main.css
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/MonographInstance.json

In the BFE, if a `PropertyTemplate` has a **remark** property, then the label becomes a hyperlink to an external explanatory website, mostly used to associate RDA properties to documentation on the http://access.rdatoolkit.org website. More details in Issue [#315 PropertyLabel needs to be hyperlink to URL in PropertyRemark](https://github.com/LD4P/sinopia_editor/issues/315)
This PR adds a new React component `PropertyRemark` that is has two HTML elements, an anchor tag and a span tag that links to the URL in the remark property. In the styling, I decided to NOT follow BFE example and made the hyperlink less obvious by not changing the color of the link but I did add an underline to visually cue the user that a hyperlink exists for the label. 
For the `InputLiteral` component:
For the …

PropertyRemark Component 

---

src/components/editor/InputListLOC.jsx

Lets see if this fixes the errors on the sinopia deployment:
`Fetch API cannot load http://id.loc.gov/vocabulary/xyz.json due to access control checks.`

Enable cors mode to be able to fetch list from LOC

---

__tests__/components/editor/InputLiteral.test.js
src/components/editor/InputListLOC.jsx
src/components/editor/InputLiteral.jsx
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/Barcode.json

Fixes #196 
- Gets default Literal value from property template and sets the "defaults" state with that data, plus any rdf-related properties that get passed in (`bnode` and `propPredicate`)
- Adds a test for this new feature
- Minor formatting of `InputListLOC`
- adds a default literal to the Barcode resource template so we can see that this is working.

Adds the default literal value if it exists

---

__tests__/actions/index.test.js
__tests__/components/editor/InputLang.test.js
__tests__/components/editor/InputLiteral.test.js
__tests__/components/editor/ResourceTemplateForm.test.js
__tests__/reducers/lang.test.js
package.json
src/actions/index.js
src/components/editor/InputLang.jsx
src/components/editor/InputLiteral.jsx
src/reducers/index.js
src/reducers/lang.js
src/store.js

Fixes #263 
- Creates a reducer to hold the language information. The object ID is the actual Literal value that the user enters.
- Creates a button that appears next to the entered value that defaults to `Language: English` until clicked, then:
- A modal appears with a List field that fetches all of the LOC languages. Selecting a language adds the details (uri, label) to the redux state with the above-mentioned ID
- Specifies follow-up work to be done
- **Note**: test coverage drops a bit, but It's not worth the time to fix right now.

Adds the ability to select a language for a Literal

---

src/components/editor/StartingPoints.jsx

Let's see if this makes it possible for Michelle to import templates she made in profile editor without hitting schema validation errors in BFF.

default schema 0.0.1 for UAT testing

---

__tests__/components/editor/InputLiteral.test.js
src/components/editor/InputLiteral.jsx

For the `InputLiteral` component, if the `PropertyTemplate`'s *repeatable* property is set to false, then the InputLiteral doesn't allow a second item to be added but the problem is there is no visual indication and users can still type in a value but nothing is saved. This PR address one of the two components mention in ticket [#347 Indicate when a field is non-repeatable](https://github.com/LD4P/sinopia_editor/issues/347). 
Starting with a propertyTemplate with repeatable=false:
I can enter text in the input field but hitting enter doesn't do anything:
This PR set's the input field to the Bootstrap-styles *disabled* attribute after one item is saved following BFE design:
This PR also fixes a bug where if the user clicks and removes the single item, the input field is no longer disabled …

Support for repeatable=false for InputLiteral

---

__tests__/components/editor/InputLiteral.test.js
src/components/editor/InputLiteral.jsx

Adds missing functionality discovered by UAT, when repeatable is false and default values exist. Also fixes incorrect spacing noted by @mjgiarlo in his comments on PR#350.

InputLiteral initially disabled when defaults are present and repeatable is false

---

__tests__/components/editor/InputLiteral.test.js
__tests__/components/editor/ResourceTemplateForm.test.js
__tests__/reducers/literal.test.js
src/components/editor/InputLiteral.jsx
src/components/editor/ModalToggle.jsx
src/components/editor/ResourceTemplate.jsx
src/components/editor/ResourceTemplateForm.jsx
src/components/editor/ResourceTemplateModal.jsx
src/reducers/literal.js

Fixes #345 
- Changes formData `id` to `uri` to accommodate having a unique ID to display the input value for a resource on the main form
- Able to read and update redux `formData` items from `ResourceTemplateForm` with default values and create a styled button from that data
- Callback functions to `ResourceTemplateForm` from `InputLiteral` to update the redux state
- Make functions for checking whether something is resource template with value constraints
- Pass the ID for a resource modal button around and back to `ResourceTemplateForm` for use in identifying which values will show with each button.
- Changes `notRepeatable`  to `notRepeatableAfterUserInput` for clarity
- Adds new PropType validations where needed

Default values and entered values on ResourceTemplateForm, styled

---

__tests__/reducers/literal.test.js
src/actions/index.js
src/components/editor/InputLiteral.jsx
src/components/editor/ResourceTemplateForm.jsx
src/reducers/literal.js

Fixes #357 
- Create a REMOVE_ALL_CONTENT action for the `literal` reducer that removes all the items for `formData` when the little trash can icon is clicked on the main resource template form
- Renames the `handleClick` function in the `InputLiteral` component in order to better distinguish these separate actions.

Remove content for resource (modal) from store and main form

---

__tests__/components/editor/InputLiteral.test.js
src/components/editor/InputLiteral.jsx

Fixes #361 
Also, making the proptype validation for `formData.uri` not required, because we do not always have this value, for example, in the tests and in the removeAllItems function when we empty out the formData state completely.

When setting default literal values, make sure to increment last id

---

__tests__/components/editor/InputLiteral.test.js

A question came up today in the Sinopia User Group if Sinopia supports transliterated titles, so this PR adds a test to `InputLiteral` for the Chinese Characters 战争的艺术 (Art of War).

Testing Chinese Characters in InputLiteral

---

.eslintrc.js
__tests__/Config.test.js
__tests__/Logout.test.js
__tests__/actions/index.test.js
__tests__/components/App.test.js
__tests__/components/HomePage.test.js
__tests__/components/Login.test.js
__tests__/components/LoginPanel.test.js
__tests__/components/RootComponent.test.js
__tests__/components/editor/StartingPoints.test.js
__tests__/reducers/authenticate.test.js
package-lock.json
package.json
src/Config.js
src/Logout.js
src/actions/index.js
src/components/App.jsx
src/components/HomePage.jsx
src/components/Login.jsx
src/components/LoginPanel.jsx
src/components/NewsPanel.jsx
src/components/RootContainer.jsx
src/index.js
src/reducers/authenticate.js
src/reducers/index.js

Fixes #372 
Fixes #382 
- When rendering the login panel on the home page, conditionally display a login or sign-out button depending on the authentication state (redux)
- When going to the import profile route (by clicking on tab), conditionally render the import profile page based on authentication state (redux) or redirect to the login component
- Redux support and connections from the various components that require checking the authentication state: 
- App: for routing; requires a higher-order component (RootComponent) to be the Provider for redux 
- HomePage: getting/setting the authentication state
- LoginPanel: for display of the login and sign-out buttons
- A Logout class that redirects to the AWS logout functionality, destroys the jwt, and redurects back to sinopia
- A Config …

Login functionality

---

.eslintrc.js
__mocks__/mockAWSData.js
__tests__/LoginData.test.js
__tests__/components/HomePage.test.js
__tests__/components/LoginPanel.test.js
__tests__/reducers/authenticate.test.js
src/LoginData.js
src/components/HomePage.jsx
src/components/LoginPanel.jsx
src/components/NewsPanel.jsx
src/reducers/authenticate.js

Fixes #381 
- Adds a `username` attribute to loginJWT hash
- Class to decode JWT and pick out username
- passes username down to LoginPanel for display
- mock test file for AWS JWT values, used in multiple tests

Decode JWT and add username to state

---

__tests__/components/Login.test.js
__tests__/components/editor/Editor.test.js
src/components/Login.jsx
src/components/editor/Editor.jsx

Fixes #349 
- From the Editor page we don't need to force the user to authenticate, just warn them and provide a login link
- Use the same alert message style when redirecting to Login from Import, and increase the timeout so the user can see the message before being redirected to Cognito.

Adds a message if the user is not logged in andvisits the editor path

---

__tests__/Config.test.js
src/Config.js

The client ID is already passed in the container environment as COGNITO_CLIENT_ID. See: https://github.com/sul-dlss/terraform-aws/blob/ecea89a3694fcf49d19040102a1d3da0328ece9d/organizations/development/sinopia/container_definitions/homepage.json#L29

Use COGNITO_CLIENT_ID as environment variable name

---

.eslintrc.js
__tests__/components/LoginPanel.test.js
__tests__/components/editor/Editor.test.js
__tests__/localStorage.test.js
__tests__/reducers/authenticate.test.js
package-lock.json
package.json
src/Logout.js
src/components/App.jsx
src/components/HomePage.jsx
src/components/Login.jsx
src/components/LoginPanel.jsx
src/components/NewsPanel.jsx
src/components/editor/Editor.jsx
src/localStorage.js
src/reducers/authenticate.js

Fixes #316 
On the `HomePage` it checks whether the user is authenticated in redux; if not, it will look for the JWT query param and authenticate them. When the component updates it will then save the authentication state to localStorage via the `saveState()` call.
The `LoginPanel`, `Editor`, and other child components then look for the authentication state via the `loadState()` call and set their local state accordingly. 
The HomePage `logOut()` function gets passed to the `LoginPanel` child component (other child components will need it later) and when called it clears the localStorage state and then redirects to cognito for the destruction of the JWT.

Use localStorage to manage the authentication status if the user 

---

__tests__/integration/schemaValidation.test.js

this is necessary for future work on schemaValidation tests (e.g. after import tab redirects to editor tab with data loaded properly - WIP by @jgreben)
@jermnelson this will help with #377 
Note that when `sinopia-devs` email list is approved, we will want to change the token used here (see LD4P/sinopia#190)

schemaValidation.test: add cognito JWT token passed in

---

static/spoofedFilesFromServer/fromSinopiaServer/lookupConfig.json

Adds QA authority lookup sources for Stanford, Cornell, and UCSD Works and Instances. **NOTE** currently QA is returning an URI instead of a text literal in the label field. This will be fixed soon.

Adds Stanford, Cornell, and UCSD ShareVDE authority sources

---

__tests__/components/editor/PropertyActionButtons.test.js
__tests__/components/editor/PropertyResourceTemplate.test.js
__tests__/components/editor/PropertyTemplateOutline.test.js
src/components/editor/PropertyActionButtons.jsx
src/components/editor/PropertyResourceTemplate.jsx
src/components/editor/PropertyTemplateOutline.jsx
src/components/editor/PropertyTypeRow.jsx

As documented in issue #388, in the current master branch, for embedded resource templates in a `PropertyPanel` is not rendering the Resource Template, like **Has Bibframe Instance** below:
This PR adds that rendering support:
Remaining TODOs:

Working PropertyTemplateOutline using embedded Resource Template in PropertyPanel Component

---

__tests__/components/editor/InputLiteral.test.js
__tests__/reducers/literal.test.js
src/components/App.jsx
src/components/editor/InputLiteral.jsx
src/reducers/index.js
src/reducers/literal.js
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/Barcode.json
webpack.config.js

On the way to finishing ticket #412, this PR uses Redux to set defaults based on Resource Template ID and URI of property using more generic reducers and a single `getProperty` selector to map the redux state to the InputLiteral's props. 
Fixes #390
Fixes #391
Fixes #428

Working selector and defaults for InputLiteral using common reducers

---

.babelrc
__tests__/components/editor/ImportResourceTemplate.test.js
__tests__/components/editor/SinopiaResourceTemplates.test.js
package-lock.json
package.json
src/components/editor/ImportResourceTemplate.jsx
src/components/editor/SinopiaResourceTemplates.jsx
src/styles/main.css
webpack.config.js

Fixes #418 
Make calls to sinopia_server using the swagger generated API code. If the calls come back with an error message, display on the page, otherwise display the returned data in a bootstrap table:
**No connection to sinopia_server, or no data retrieved from calls:**
**sinopia_server is connected and returns the expected data from `repository/ld4p`:**

List of resource templates retrieved from sinopia_server

---

__tests__/components/editor/Editor.test.js
__tests__/components/editor/ResourceTemplate.test.js
src/components/editor/Editor.jsx
src/components/editor/ResourceTemplate.jsx

Shifted the code around that seemed specific to the resource template (i.e. the resource template ID/URI and label) to the resource template component.  At first, I had the preview RDF button still in the Editor component but moved the entire section with that and RDF Modal into ResourceTemplate.  Added a constructor to ResourceTemplate just so it can have state and showRDF (notice these are set in ResourceTemplateForm).  
The placement of preview rdf should match the original, but the label and URI are now being retrieved from the resource template data.
Tests have been updated to reflect shifting of content across components.

Resourcelabel 393

---

__tests__/components/editor/PropertyTemplateOutline.test.js
src/components/editor/PropertyTemplateOutline.jsx

Updating PropertyTemplateOutline to retrieve and send array of lookup config items (instead of just the first one) to the input lookup qa component as expected.  Function for getting just the first lookup (for input list loc) and all lookup configs both employ shared code for retrieving lookup configuration based on a template uri.

sending multiple lookup config items array to input qa

---

src/store.js

Following a suggestion by @jgreben during pairing, enables the Redux dev tools plugin if Editor is running in development.

Conditional Redux plugin support depending on Environment

---

__tests__/integration/schemaValidation.test.js
src/Config.js
src/components/editor/ImportFileZone.jsx

Fixes #396
This introduces a new env-overrideable config variable setting the default RT/Profile schema version. 
~~Note that I was unable to determine whether 0.0.9 is the right default for now. #396 specifies 0.0.9 so that is what I went with, but 0.1.0 seems to be the newest version available~~ I... *think* I confirmed on Slack this morning that 0.0.9 is the right default for the time being.
~~FWIW, I attempted to upload a few seemingly valid 0.1.0 and 0.0.9 profiles and I was unable to get *any* to validate. I am not sure whether that should be in scope for this issue but I would at least like to understand why this is the case.~~ Confirmed with @michelleif that https://github.com/LD4P/sinopia_sample_profiles/blob/master/configuration_demo/SinopiaConfigurationDemo.json is the most …

Update schema version info message when importing a new RT/profile

---

.eslintrc.js
__tests__/actions/index.test.js
__tests__/components/editor/InputLiteral.test.js
__tests__/components/editor/PropertyResourceTemplate.test.js
__tests__/components/editor/PropertyTemplateOutline.test.js
__tests__/reducers/index.test.js
__tests__/reducers/literal.test.js
src/actions/index.js
src/components/editor/InputLiteral.jsx
src/components/editor/PropertyPanel.jsx
src/components/editor/PropertyResourceTemplate.jsx
src/components/editor/PropertyTemplateOutline.jsx
src/components/editor/PropertyTypeRow.jsx
src/components/editor/ResourceTemplateForm.jsx
src/reducers/index.js
src/reducers/literal.js
src/styles/main.css

PR uses the structure of the Resource Template as a data-structure that stores the state of `InputLiteral` anywhere in the User Interface. This example shows the default value of _DLC_ in a multiple-layer deep embedded resource template:
Todos:

Embedded resource template Redux support for UI

---

__tests__/components/editor/ImportResourceTemplate.test.js
__tests__/components/editor/SinopiaResourceTemplates.test.js
__tests__/components/editor/UpdateResourceModal.test.js
src/components/Login.jsx
src/components/editor/ImportResourceTemplate.jsx
src/components/editor/SinopiaResourceTemplates.jsx
src/components/editor/UpdateResourceModal.jsx

Update resources when a trellis response indicates a conflict and warn user in rendered modal.
Fixes #454
This PR includes:
- Creates `UpdateResourceModal` that appears when a 409/Conflict error is caught from a POST call to trellis with an existing resource ID. The modal captures the 409 response and renders some details about it, and then returns the conflicting template data to a callback function that handles the update (PUT) call instead.
- `ImportResourceTemplate` provides the callback function to the modal and handles the trellis call to do the updates, setting the component state and props as needed
- `SinopiaResourceTemplates` should handle an array of contents as well as a single content as a string. Refactors promise for better testing
- (minor change) Decrease the timeout …

Update resources and warn users

---

__tests__/components/App.test.js
__tests__/components/editor/Header.test.js

Reviewing PR #471 made me wonder if there were more commented out tests, besides schemaValidation, that should be skipped.  I did a super quick grep check and ended up making these two tweaks.
Yay - the answer was we only have one other commented out test and the whole test was commented out, not just the guts.

Tiny test tweaks (no code changed)

---

__tests__/Config.test.js
__tests__/__fixtures__/lcc_v0.0.9.json
__tests__/__fixtures__/lcc_v0.1.0_bad_id.json
__tests__/__fixtures__/place_profile_v0.0.9.json
__tests__/components/RootComponent.test.js
__tests__/components/editor/ImportFileZone.test.js
__tests__/components/editor/ImportResourceTemplate.test.js
__tests__/integration/schemaValidation.test.js
package-lock.json
src/Config.js
src/components/editor/ImportFileZone.jsx

This PR was originally about testing the "spaceless" IDs in the JSON schema (See https://github.com/LD4P/sinopia/pull/201) but morphed into refatoring the schema validation tests to happen at the component/unit-test level in stead of integration tests (which were incomplete and error-prone). There is still one integration test for the malformed JSON test which was dificult to test at the unit-test level. A beneficial side-effect is that this refactoring increases overall code-coverage.

Test spaceless ids (refactor the schema validation tests)

---

.circleci/config.yml
.dockerignore
Dockerfile
README.md
__tests__/Config.test.js
__tests__/components/App.test.js
__tests__/components/editor/PropertyTemplateOutline.test.js
__tests__/components/editor/ResourceTemplate.test.js
__tests__/reducers/linkedData.test.js
__tests__/sinopiaServer.test.js
docker-compose.yml
package-lock.json
package.json
src/Config.js
src/components/editor/PropertyTemplateOutline.jsx
src/components/editor/ResourceTemplate.jsx
src/components/editor/ResourceTemplateForm.jsx
src/reducers/linkedData.js
src/sinopiaServer.js
webpack.config.js

Fixes #459 
Includes:
* Add configuration for disabling/enabling spoofing
* Set default value to enable spoofing and explicitly set this value in the editor service in docker-compose to retain current behavior
* Inject environment variables the editor can see and use via Docker in order to disable/enable spoofing and set the Sinopia server URL
* Favor `getResourceTemplate()` over `getResourceTemplateFromServer()` to allow switching behavior (namely where the RTs are coming from) via env vars.
* Reduce number of max warnings for eslint failures

Allow environment variable injection from containerland into application

---

__tests__/Config.test.js
__tests__/components/Header.test.js
src/Config.js
src/components/Header.jsx
src/components/editor/Header.jsx

Fixes #479, #480
- Omits extra https in url string
- Makes import the default Linked Data Editor page
- Renames the import tab

Fixes header and login links

---

__tests__/Config.test.js
src/Config.js

The last PR did not fix the login link to AWS. I believe this should do the trick.

Fix AWS Cognito Domain to remove extra https in login link

---

__tests__/components/editor/PropertyActionButtons.test.js
__tests__/components/editor/PropertyTemplateOutline.test.js
src/components/editor/PropertyActionButtons.jsx

@jermnelson made the changes to <PropertyActionButtons>;  I mostly mucked about with tests.
Make "Add" and "MintURI" buttons into components.
Found a bit of a testing boondoggle in PropertyTemplateOutline tests -- a number of false positives.  Will be addressing those by making issues and/or PRs.
This PR should help with all things about repeatable properties for M3:
- #387 Add Button should be disabled when repeatable is false and more than one value
- #346 Handle repeatable true for a resource
- #217 implement repeatable = true (yes, prob a dup ticket, but UAT ticket)
- #210 allow duplicate values when property is repeatable

 PropertyActionButtons: AddButton, MintButton are components

---

__tests__/components/App.test.js
__tests__/sinopiaServer.test.js
src/components/App.jsx
src/components/editor/Editor.jsx
src/components/editor/ResourceTemplateForm.jsx
src/components/editor/SinopiaResourceTemplates.jsx
src/sinopiaServer.js

Fixes #480 
- Redirect to Import Templates if there is no resourceTemplateId in state (i.e. no template to edit with yet)
- Spoof all of the local templates in the list of available resource templates (because we no longer will be loading a default RT for testing)

Going directly to editor route redirects to the "Resource Templates" tab

---

__tests__/components/editor/OutlineHeader.test.js
__tests__/components/editor/PropertyTemplateOutline.test.js
src/components/editor/InputLiteral.jsx

- Adds unit tests for OutlineHeader
- skips and leaves breadcrumbs for false positive test cited in #496
(I also beefed up issue #496)

More test cleanup

---

__tests__/components/editor/PropertyTemplateOutline.test.js
__tests__/components/editor/ResourceTemplateForm.test.js
src/components/editor/PropertyTemplateOutline.jsx
src/components/editor/ResourceTemplateForm.jsx

These are just like the false positives I found for PropertyTemplateOutline.test.  I put "expect(1).toBe(2)" in the blocks with expect statements, and these tests passed.  :-(
I also corrected the misspelling of fulfill and got rid of unused imports.

ResourceTemplateForm.test: skip tests giving false positives

---

__tests__/components/editor/ResourceTemplate.test.js
src/components/editor/Editor.jsx
src/components/editor/ResourceTemplate.jsx
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/MonographInstance.json

- Use actual property template labels for spoofed Monograph:Instance instead of the ones we started with for wire-framing
- Move the resource template label down from the Editor component so we can display the actual RT label (plus some inline styling)
- Remove the `[Clone|Edit]` button placeholders. When we need those buttons we will make real ones.

Remove vestiges of wireframed resource template components

---

__tests__/components/editor/SinopiaResourceTemplates.test.js
src/components/editor/SinopiaResourceTemplates.jsx

Removes HTML that displayed a list of groups that retrieved from Trellis.
Fixes #508

Removes bullet list of groups retrieved from Trellis

---

__tests__/components/editor/InputListLOC.test.js
__tests__/reducers/inputs.test.js
src/components/editor/InputListLOC.jsx
src/components/editor/ResourceTemplateForm.jsx
src/reducers/index.js
src/reducers/inputs.js

Fixes #430 
- Renames `literal` reducer to `inputs` because it is now being used by more than one input component
- Add a redux function to set the selections from the typeahead option list. Selections are overwritten every time with everything in the `selected` array because the typeahead component keeps track of what's in there
- Reorder the properties in the default payload to match what's set when selections are made
- Remove the un-used rtId and add the reduxPath as needed by the new selectorReducer way of setting the redux state
- Whether the typeahead component allows multiple selections should come from the repeatable property of the valueConstraint and not the property template.

Inputlistloc selector reducer

---

__tests__/components/editor/PropertyTemplateOutline.test.js
src/components/editor/PropertyTemplateOutline.jsx

Adds check for missing valueConstraint and valueConstraint.valueTemplateRefs when user clicks on the plus.
Fixes #509
Todo:

Handles missing valueConstraint and valueTemplateRef in PropertyTemplateOutline

---

docker-compose.yml

Until I made these changes, I could not successfully make HTTP requests to Trellis using the Authorization header and my (valid) JWT. This brings the editor DC configuration in line with the ACL configuration.

Update docker-compose config for Trellis and ACL components

---

__tests__/components/editor/ResourceTemplateForm.test.js
src/Utilities.js
src/components/editor/ImportResourceTemplate.jsx
src/components/editor/PropertyTemplateOutline.jsx
src/components/editor/ResourceTemplateForm.jsx
src/components/editor/SinopiaResourceTemplates.jsx
src/components/editor/UpdateResourceModal.jsx

Fixes #517 
Fixes #496 for ResourceTemplateFormTest
- Collect ids from resource templates that could not be fetched from server and display them in error message:
- Fix false positives in ResourceTemplateForm tests and test for missing template message
- There was a function that was needed to be used in three different components to get the resource name out of a URI (everything after the last `/`). Switch to using a one-liner instead of repeating that function (or creating a global function)

Missing templates

---

__mocks__/SinopiaClientErrorFake.js
__mocks__/SinopiaClientSuccessFake.js
__tests__/components/editor/ImportResourceTemplate.test.js
__tests__/components/editor/SinopiaResourceTemplates.test.js
__tests__/components/editor/UpdateResourceModal.test.js
__tests__/reducers/inputs.test.js
jest-puppeteer.config.js
package-lock.json
package.json
src/components/Footer.jsx
src/components/editor/ImportResourceTemplate.jsx
src/components/editor/SinopiaResourceTemplates.jsx
src/components/editor/UpdateResourceModal.jsx
src/sinopiaServer.js

Fixes #506 
Fixes #507 
Includes:
* Bump sinopia_server to 3.0.0-beta4
* Using the newer version of the sinopia client allows the editor to invoke the updateResource API with a custom content type (application/json). Prior to this change, updates worked (apparently) but what was happening was the editor was issuing PUT requests and getting 204s... but not modifying the NonRDFSource. Instead the RDFSource that Trellis auto-attaches to every NonRDFSource was being modified.
* Use new SSL-based location of the CreativeCommons image
* This gets rid of the constant mixed content errors in the console.
* Correct two typos that are surfaced in the user-facing UI
* Avoid wrapping promises in other promises (coming from the sinopia client)
* Refactor resource template components
* Add test …

Refactor and fix resource template components

---

__tests__/components/editor/ImportFileZone.test.js
__tests__/components/editor/ImportResourceTemplate.test.js
src/components/editor/ImportFileZone.jsx
src/components/editor/ImportResourceTemplate.jsx
src/components/editor/SinopiaResourceTemplates.jsx

Fixes #507 
Fixes #531
Includes:
* Update component state less often: batch up `setState` calls to avoid timing-related failures such as seen in #507 
* Disallow multi-file uploads when importing resource templates (#531)
* Remove unused property type declaration while troubleshooting
* Remove unnecessary braces around single-line `if` action

Fix resource template table updates

---

.babelrc
__tests__/components/editor/ImportResourceTemplate.test.js
package-lock.json
package.json
src/components/editor/ImportResourceTemplate.jsx
src/components/editor/SinopiaResourceTemplates.jsx

Fixes #534
This branch includes the following changes:
* Reset messages and errors in `ImportResourceTemplate` component when HTTP response is successful
* Reset messages when update handler is finished
* Prevent users from dismissing flash message box, else it never comes back
* Extract code to parse a response object into a human-friendly location into a new function in `ImportResourceTemplate` component
* Add Babel plugin for optional chaining (as dev dependency) via the safe navigation (or "Elvis") operator
* This lets us safely reach into objects such as HTTP responses without having to check at every level for `null` or `undefined`

Prevent upload modal & flash message from showing stale messages

---

src/components/editor/PropertyComponent.jsx
src/components/editor/ResourceProperty.jsx

Only use one function for searching lookupConfig, use `map` instead of `forEach`, and fix propTypes

Minor tweaks to refactor

---

README.md
package.json
webpack.config.js

* add `COGNITO_USER_POOL_ID` to `webpack.config.js` so that it's usable by the editor
* update README to explain gotcha around having editor pick up env vars and/or build them into env specific images
and a couple small opportunistic things:
* add section on specifying Cognito login info when running tests locally on dev laptop
* addresses one of the follow on tasks in #528 ("update README to give new instructions for running test suite locally")
* add two more devs to the list of contributors
fixes #544 (🤞)

fix login on non-dev instances.  other touchups.

---

__tests__/components/editor/ImportResourceTemplate.test.js
__tests__/components/editor/SinopiaResourceTemplates.test.js
__tests__/components/editor/UpdateResourceModal.test.js
src/components/editor/ImportFileZone.jsx
src/components/editor/ImportResourceTemplate.jsx
src/components/editor/SinopiaResourceTemplates.jsx
src/components/editor/UpdateResourceModal.jsx

Fixes #554
Includes:
* Reset `ImportResourceTemplate` messages when initiating a new upload, not when wrapping one up for simplicity (before we get stuck in a maze of callbacks)
* Rework `updateStateFromServerResponse` as `updateStateFromServerResponses` so we can report on multiple requests at one time, collecting all the messages at once
* Change 409 Conflict message to be clearer (we're not *attempting* to update; we are waiting on a user prompt)
* Rename `ImportResourceTemplate.state.message` to `flashMessages` to make intent clearer
* Rename `ImportResourceTemplate.state.createResourceError` to `modalMessages` to make intent clearer
* Move resetting of `updateKey` into `updateStateFromServerResponses` so it's centrally located

Display messages for all resource templates in a profile

---

__tests__/components/editor/PropertyComponent.test.js
__tests__/components/editor/PropertyTemplateOutline.test.js
package-lock.json
package.json
src/components/editor/PropertyComponent.jsx
src/components/editor/ResourceTemplateForm.jsx

As @michelleif noted in #575, the defaults were not showing up because the `reduxPath` was not set  in the PropertyComponent component. 
Fixes #575

Add reduxPath to PropertyComponent

---

__tests__/components/editor/InputListLOC.test.js
__tests__/components/editor/InputLookupQA.test.js
src/components/editor/InputListLOC.jsx
src/components/editor/InputLookupQA.jsx
static/spoofedFilesFromServer/fromSinopiaServer/lookupConfig.json

Fixes #576
Includes:
* Fix a couple dozen typos in the lookup config (`getty_att*` to `getty_aat*`)
* Log info, rather than error, messages to the console when lookups lack defaults. Defaults are not required so these are not errors.
* Avoid creating a new Swagger client on every QA request; instead create the client in the component constructor.
* Increase parity/decrease drift between `InputLookupQA` and `InputListLOC` components by including `id` and `selectHintOnEnter` in the typeahead properties.
* Fix typo in `InputLookupQA` component that was setting the subauthority to the same value as the authority.

Fix Getty AAT QA lookups

---

__tests__/components/editor/InputListLOC.test.js
__tests__/components/editor/InputLookupQA.test.js
src/Utilities.js
src/components/editor/InputListLOC.jsx
src/components/editor/InputLiteral.jsx
src/components/editor/InputLookupQA.jsx
src/components/editor/PropertyComponent.jsx
src/components/editor/PropertyTemplateOutline.jsx

Fixed bug where lookup config is returning an array of objects and InputListLOC expects just a single object.
Also, removes annoying console logging which we do not really need
Also, makes sure that the lack of a setting for one property variable does not break the other variables where the property is actually set.
Adds a test for the presence of a lookupConfig URI.

Fix lookup config bug in InputListLOC

---

.eslintrc.js
__tests__/components/editor/ImportFileZone.test.js
__tests__/components/editor/ResourceProperty.test.js
__tests__/reducers/index.test.js
src/components/editor/ImportFileZone.jsx
src/components/editor/ResourceProperty.jsx
src/reducers/index.js

Fixes #602
This PR fixes two errors referenced in #602 and supersedes #613.
First, it fixes the assumption made in `src/reducers/index.js` that all property templates have `.valueConstraint.defaults` defined; some resource templates lack a valueConstraint` so this is not true.
Second, in the `ResourceProperty` component, if a referenced resource template is undefined, render a warning message instead of throwing an error. (Sinopia users expect to be able to import resource templates referencing other resource templates which have not yet been created.) @michelleif Here's what the UI change looks like:
Also includes these maintenance bits, added opportunistically:
* Avoid stashing values in `ImportFileZone` component state when not necessary. This also follows a React guideline of not …

Render a warning when expanding a template w/ missing RT

---

src/components/editor/RequiredSuperscript.jsx

By making this an abbr with a title, you can hover over to discover that the asterisk means the field is required.

Explain what the asterisk means

---

src/components/editor/PropertyLabel.jsx

If you click the link in the property label you are taken out of the editor. If you then use the back button, the state is lost.

Property label links open new window/tab.

---

__tests__/components/editor/GroupChoiceModal.test.js
__tests__/components/editor/RDFModal.test.js
__tests__/integration/previewSaveRDF.test.js
__tests__/sinopiaServer.test.js
src/Config.js
src/components/editor/Editor.jsx
src/components/editor/GroupChoiceModal.jsx
src/components/editor/RDFModal.jsx
src/sinopiaServer.js
src/styles/main.css

Fixes #597 
Granted, on the original design, the Preview RDF was a full page instead of a modal.

Create a modal to get user input for choosing a sinopia group

---

src/components/editor/Editor.jsx

Property was introduced as an `object` here: https://github.com/LD4P/sinopia_editor/commit/41e563c1081c39af879879a3d37ac1306ced1979#diff-b1dd550483f4824a3137472f58cea377R115

RDF is a string

---

src/components/NewsItem.jsx
src/components/NewsPanel.jsx

- revised text on homepage for release 0.3.0
- made the column for the news item wider so it didn't wrap weirdly (login fields used to be to the right of the news panel so we needed the narrower column previously)

revised text for new release

---

__tests__/components/LoginPanel.test.js
src/components/LoginPanel.jsx

Fixes #594 
This raises an alert so the user is aware that the signout failed. Since jest does not implement the window.alert method specifically, a `global.alert` declaration is required to avoid a `window.alert is not implemented` error message.

Raise alert when the signout fails

---

src/components/editor/property/PropertyTemplateOutline.jsx
src/components/editor/property/ResourceProperty.jsx

PropertyTemplateOutline does not need initNewResourceTemplate

---

src/components/editor/property/InputListLOC.jsx

State change can happen once it's mounted via componentDidMount()
Fixes this error:

Don't allow constructors to change state

---

__tests__/components/editor/property/InputLang.test.js
src/components/editor/property/InputLang.jsx

The default Typeahead component `emptyLabel` is "no matches found." Sometimes the list lookup to LOC takes a couple of seconds, so changing the label to something more user friendly might help avoid confusion.

Change default display label for Typeahead component

---

__tests__/components/editor/ImportFileZone.test.js
src/components/editor/ImportFileZone.jsx

Fixes #653 
Button text now reads "Import a Profile containing New or Revised Resource Templates"
(Also removes some cruft and a pointer to a better way to render a select form for possible future use)

Change button text so as not to be misleading

---

__tests__/integration/unauthenticatedNavigation.test.js

This is just a simple (and possibly not useful) pass at an integration test to verify that a logged out user cannot access the resource templates that require authentication. This is part of #421 which is has some testing already complete in other PRs.

Simple integration test for unauthenticated users

---

__tests__/Utilities.test.js
__tests__/sinopiaServerSpoof.test.js
src/Utilities.js
src/sinopiaServerSpoof.js
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/RDAMainifestationMonograph.json
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/adminMetadata.json
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/adminMetadataStatus.json
static/spoofedFilesFromServer/fromSinopiaServer/resourceTemplates/rdaItemMonograph.json

Fixes #660 
Adds some new spoofed resource templates for testing this fix.
If the defaultLiteral value is undefined, use the defaultURI instead.

Fix undefined label in the InputLookupQA component

---

__tests__/integration/loginHelper.js
__tests__/integration/nestedResources.test.js
__tests__/integration/previewSaveRDF.test.js
__tests__/integration/repeatableResources.test.js
__tests__/integration/schemaValidation.test.js
__tests__/integration/unauthenticatedNavigation.test.js
package.json

Given the same code was copied into 5 different tests, it seemed worthwhile to make helper functions for it.  I suspect we'll be adding more integration tests requiring login in the future, too.
Fixes #547

add loginHelper for integration tests

---

__tests__/components/editor/ImportFileZone.test.js
__tests__/components/editor/ImportResourceTemplate.test.js
__tests__/components/editor/SinopiaResourceTemplates.test.js
__tests__/components/editor/property/InputLang.test.js
__tests__/components/editor/property/InputListLOC.test.js
__tests__/integration/landingPage.test.js
__tests__/integration/nestedResources.test.js
__tests__/integration/previewSaveRDF.test.js
__tests__/integration/repeatableResources.test.js
__tests__/integration/schemaValidation.test.js
__tests__/integration/unauthenticatedNavigation.test.js
__tests__/sinopiaServer.test.js
__tests__/sinopiaServerSpoof.test.js
src/components/editor/property/PropertyPanel.jsx
src/components/editor/property/PropertyTemplateOutline.jsx

This makes the css selectors a lot more readable for integration tests.
Since those were async tests and I realized they needed a little bit of love to avoid false positives, I just did a search on `async` in all the tests and applied the same love everywhere.
- be sure to "return" on async beforeXXX blocks  (https://jestjs.io/docs/en/setup-teardown) 
- indicate the number of assertions expected in a test (https://jestjs.io/docs/en/asynchronous)
Only one test showed up as being a no-op, which I marked "skip".
closes #573

improve css selectors in tests; ensure no false positives for async tests

---

__tests__/integration/previewSaveRDF.test.js

These tests are unable to be run individually as they depended on the state created by the preceeding tests. I've combined them to show that they can not stand on their own.

Combine tests that depend on one another

---

__tests__/integration/repeatableResources.test.js
src/components/editor/property/PropertyPanel.jsx
src/components/editor/property/PropertyTemplateOutline.jsx

propLabel was not recognized by react and raised a warning.  data-label can fulfill the same purpose and it doesn't raise a warning
Fixes #707

Change propLabel to data-label

---

__tests__/components/editor/property/InputLiteral.test.js

Rename mocks so they aren't confusing.

Ensure tests can be run indenpendently

---

package-lock.json
package.json

Version bump; will create a tagged release `0.3.2` when merged.

Updated version and regenerated lock file

---

__tests__/Validator.test.js
__tests__/actions/index.test.js
__tests__/components/editor/Editor.test.js
__tests__/components/editor/property/InputLiteral.test.js
__tests__/reducers/inputs.test.js
src/Validator.js
src/actions/index.js
src/components/editor/Editor.jsx
src/components/editor/property/InputLiteral.jsx
src/reducers/index.js
src/reducers/inputs.js
src/store.js

Display validations at the top level when validate is pressed.

---

__tests__/Utilities.test.js
__tests__/reducers/inputs.test.js
src/Utilities.js
src/reducers/index.js
src/reducers/inputs.js

Fixes #712:
Similar to https://github.com/LD4P/sinopia_editor/pull/684, if the lookup component has a `defaultURI` defined as an empty string, the `TypeaheadComponent` will expect a label to go along with that default and without one will crash. This PR redefines when the defaults should return an empty array to that component.
Fixes #718:
If the initial state of a redux resource object is undefined, and the defined property component assigns a `shortid` in the redux path, the component crashes when trying to filter on an undefined object in that path, so check for that in the reducer when reassigning state.
I ran across the bug surfaced in #718 while testing #712, so that's why this PR fixes both issues. I can split the PRs up if desired, but the changes here are not extensive.

Fix Blank Screen when performing a Lookup

---

src/components/editor/property/InputLiteral.jsx

PR #738 Fixed #736. This PR is now only about using the Utility function to determine the boolean values from JSON strings.

Use Utility function in InputLiteral component to determine the boolean values from JSON strings

---

__tests__/components/editor/GroupChoiceModal.test.js
src/Config.js
src/components/editor/GroupChoiceModal.jsx

a bit of light refactoring and tweaking to make it happen, plus a new integration test to make sure it worked.
the sort wasn't asked for, but it seemed easy enough to do, so i went ahead and did that.
if this gets merged as-is, we should also merge the comment in LD4P/sinopia_acl#75
closes #732

get the correct list of groups to display (and sort them in alphabetical order) when choosing where to save a resource

---

__tests__/components/editor/property/PropertyTemplateOutline.test.js
src/components/editor/property/PropertyTemplateOutline.jsx

Fixes #697 
I am working on a more complete test for this. I'm happy to continue that test here or in a follow up PR if this fix needs to get in ASAP.

Do not add extra property rows when clicking the plus/add button.

---

__tests__/components/editor/property/InputLookupQA.test.js
src/components/editor/property/InputLookupQA.jsx

This was causing problems because it was expecting props to be set in the constructor rather than the render function
Fixes #755

Restore the ability for defaults to be used in a lookup

---

.eslintrc.js
src/components/editor/property/ResourceProperty.jsx

Fixes #649 - warning about state changes during rendering of `ResourceProperty` component.
Assumptions / Questions:

ResourceProperty: separate state changes from rendering

---

__tests__/GraphBuilder.test.js
__tests__/components/editor/property/InputLang.test.js
__tests__/reducers/index.test.js
src/GraphBuilder.js
src/Utilities.js
src/components/editor/property/InputLang.jsx

This involved switching to using iso639-1 language codes because these are required for language tags per RFC 5646.
Fixes #666

Export language tags to RDF

---

__tests__/reducers/index.test.js
src/components/editor/property/ResourceProperty.jsx
src/reducers/index.js

Selections of new resource templates from list should replace the state of `selectorReducer.resource`

Fixes bug where subsequently selected resource templates are appended to selectorReducer.resource

---

.eslintrc.js
__tests__/integration/previewRDFHelper.js
__tests__/integration/previewSaveRDF.test.js
__tests__/integration/verifyPreviewRDF.test.js
package.json

Replacement PR for #758, this moves the reusable setup steps from `previewSaveRDF` into a helper method. This is reused in a new test `verifyPreviewRDF` which doesn't rely on the "Save & Publish" clicks but checks the content of the modal.
This also avoids changing the intent of the nestedResource test.

Add test to verify content exists in preview RDF

---

__tests__/reducers/inputs.test.js
src/reducers/inputs.js

Sets the state for the rdfPreview.show modal to false and tests that the condition is set for invalid RDF.
Fixes #781

Close the previewRDF modal if validations fail

---

package-lock.json

This changed after running `npm install`
This seems to be due to differences between linux and MacOS.  See https://github.com/dependabot/feedback/issues/197

Update the package-lock.json

---

__tests__/integration/previewRDFHelper.js
__tests__/integration/saveIncompleteRDF.test.js
__tests__/reducers/index.test.js
src/reducers/index.js

Fixes #745 
Clears the errors and sets displayValidations to false when a resource template is loaded. Adds unit testing for the values and an integration test for displaying and clearing the validation errors on the page.
Before: After validation errors and clicking on a new template - Validation errors are still displayed. 
After:  After validation errors and clicking on a new template - Validation errors are cleared.

Clear validation errors when a resource template is loaded

---

.eslintrc.js
__tests__/components/editor/property/PropertyLabel.test.js
__tests__/components/editor/property/RequiredSuperscript.test.js
src/components/editor/property/PropertyLabel.jsx
src/components/editor/property/RequiredSuperscript.jsx

Fix empty tooltip and missing required tooltip

---

__tests__/reducers/index.test.js
src/reducers/index.js

Rather than resourceTemplateLoaded.  resourceTemplateLoaded occurs for each new template that is added so we don't want to clear the editor state when a new template is added, only when the root template is added.

setResourceTemplate should clear the editor state

---

__tests__/actions/index.test.js
__tests__/reducers/index.test.js
src/actions/index.js
src/components/editor/ResourceTemplate.jsx
src/reducers/index.js

This makes it clearer this is only for the root template.  It also is more consistent with other actions that use "loaded" as a suffix

[Refactor] Rename setResourceTemplate to rootResourceTemplateLoaded

---

server.js
webpack.config.js

Refs #630
The now-reverted #793 PR—which replaced `webpack-dev-server` (used as the web server in dev and test environments) with `webpack-dev-middleware` sitting in front of an environment-specific express server—showed a thorough mechanism to use the same server infrastructure across dev, test, and prod environments. It also fundamentally broke the build and introduced way more code than was necessary for the task.
After thrashing in the deep-end briefly, wrapping my head around what it means to bring our dev/test and prod servers more into alignment—such that both `npm start` and `npm run dev-start` both spin up servers with the same routes, to support the ElasticSearch proxy (#630)—I reckoned that a much simpler approach (outlined by @jermnelson in a Slack thread the other day) is …

Demonstrate a lightweight pattern for cross-environment routes

---

.eslintignore
README.md
docker-compose.yml
server.js
webpack.config.js

Includes:
* Subject the webpack config to the useful oppression of the eslint regime
* Improve and correct typos in README
* Add indexing pipeline, ElasticSearch, and DejaVu (ES admin app) to docker-compose configuration.
* Organize server.js better.
* Add better documentation about docker-compose configuration
* Fix the editor service so that it can talk to Trellis
* The editor runs locally (hello, client-side applications), thus must use `localhost` to hit Trellis, rather than `platform` which only works INSIDE containerland (and our browsers are not in containerland).

Salvage useful bits of #793

---

__tests__/components/editor/ResourceTemplateForm.test.js
__tests__/components/editor/property/PropertyResourceTemplate.test.js
src/components/editor/ResourceTemplateForm.jsx
src/components/editor/property/PropertyResourceTemplate.jsx

Since PropertyResourceTemplate has the add button it makes sense for it to be
responsible for generating reduxPath for the children.  This will enable the editor
to load up existing resources from Trellis.

Refactor so that PropertyResourceTemplate makes the child rows

---

__tests__/components/templates/SinopiaResourceTemplates.test.js
src/components/templates/SinopiaResourceTemplates.jsx

~~starting this out in draft because i'd be interested in getting advice or pairing on writing a simple test for this... maybe an integration test?  maybe that's overkill?  but i'll note that the code change didn't fail any existing tests (and i only made the change i did to the component's unit tests so that the example there wouldn't be confusingly out of sync with the app code, even though lack of change would've left things passing).~~
closes #802 (remark)
closes #636 (author)

swap the group col for author and remark ("guiding statement") cols in the template list page (/templates)

---

__tests__/__fixtures__/propertyURIRepeated.json
__tests__/fixtureLoaderHelper.js
__tests__/integration/repeatedPropertyURI.js
src/components/editor/property/InputLiteral.jsx
src/components/editor/property/PropertyComponent.jsx

since fix is to pass the property template down from `PropertyComponent` to `InputLiteral`*, write a simple integration test that checks to see that a fixture RT renders as expected.
*parent already has the right instance, no need to look it up from the redux store, which just returns the property that first matches on propertyURI
closes #765

fix repeated placeholder text for input literals in RT where propertyURI is repeated but propertyLabel differs

---

__tests__/__fixtures__/MonographInstance.json

Fixes #837 
Remove "Notes on Frequency" propertyTemplate as it isn't used in any tests.

MonographInstance fixture: remove duplicate property

---

__tests__/integration/correctRdfInPreview/literalPropertyTemplates.test.js
__tests__/integration/landingPage.test.js
__tests__/integration/nestedResources.test.js
__tests__/integration/previewSaveRDF.test.js
__tests__/integration/repeatableResources.test.js
__tests__/integration/saveIncompleteRDF.test.js
__tests__/integration/schemaValidation.test.js
__tests__/integration/unauthenticatedNavigation.test.js
__tests__/integration/verifyPreviewRDF.test.js

fixes #840
This PR adapts our tests to have better syntax for async setup and teardown methods. 
from https://jestjs.io/docs/en/setup-teardown
> beforeEach and afterEach can handle asynchronous code in the same ways that tests can  handle asynchronous code - they can either take a done parameter or return a promise. For example, if [ promiseFromFunction() ] returned a promise that resolved when the database was initialized, we would want to return that promise:
```js
beforeEach(() => {
return promiseFromFunction()
})
```
As @jmartin-sul points out in #840 and also in [this PR comment](https://github.com/LD4P/sinopia_editor/pull/820#discussion_r297858708), an `async` method, by definition, returns a promise.  So this is also an appropriate way for a setup/teardown method to handle …

tests: if setup or tear down is async, no need for explicit return

---

src/reducers/index.js

The complexity of this method increased by one on the last merge with master so this wasn't noticed until merged. Fixes the master build.

Set method complexity to fix eslint in build

---

.dockerignore

Because we should not include sensitive values in public assets.

Ignore .env file when building docker images

---

__tests__/components/editor/ResourceTemplate.test.js
__tests__/integration/verifyTemplateTitle.test.js
src/components/editor/ResourceTemplate.jsx
src/reducers/index.js

Fixes #844 
This sets the title of the resource Template into `resourceTemplateLabel` in order to be displayed on the editor page.
Note: This bug was missed by the simple unit test due to the injection of the title guaranteeing it's availability in the display. Basic integration tests like the one below are critical in surfacing these kinds of bugs by using fixtures that are compared to the output.

Get resource template title for display in editor

---

__tests__/components/editor/property/InputListLOC.test.js
__tests__/integration/previewRDFHelper.js
src/components/editor/property/InputListLOC.jsx
src/components/editor/property/InputLookupQA.jsx
src/components/editor/property/PropertyComponent.jsx

Closes #604.  Note that #604 was at the top of the ready column when I started the work.
In addition to getting propertyTemplate and lookupConfig from redux, we also retrieve the propertyTemplate defaults from the selectorReducer.
Lastly, saw an opportunity to tweak some comments in 2 other spots, so I took it.  Happy to break those into separate PRs if they are controversial.

InputListLOC uses redux state for propertyTemplate and lookupConfig 

---

__tests__/components/editor/property/PropertyTemplateOutline.test.js
src/components/editor/property/PropertyTemplateOutline.jsx

Rather, the rendering should be a projection of the state.

Avoid rendering into the state

---

__tests__/__fixtures__/MonographInstance.json

It doesn't make sense to have both properties set for a template

Remove defaults on template that has valueTemplateRefs

---

.circleci/config.yml
Dockerfile
__tests__/Config.test.js
package-lock.json
package.json
server.js
src/Config.js
webpack.config.js

Fixes #630
Includes:
* Add middleware to Express server to proxy ElasticSearch requests
* Allow only GET and POST requests to a known path
* Add new config entry for index (*i.e.*, ElasticSearch) URL, backed by an environment variable
* Add environment variable to the necessary spots to ensure it is properly fixed at build time (per README)
* Handle a FIXME in server.js, preferring `.find()` over `.forEach()`

Proxy ElasticSearch service

---

server.js

Requested by @ndushay in #868 
Also: use ES6 import style now that server is invoked via `npx babel-node`, for consistency with the rest of the codebase.

Add comments to Express server

---

src/components/editor/property/InputListLOC.jsx

connects to #772:   InputListLOC wasn't updating redux state.
This fixes the bug, but it has no tests:
- waiting for #832:  tests should not depend on network services -- this code is intimately tied to QA lookups.
- I couldn't figure out how to test this with a unit test - how to test that redux gets the right information when the component's actions, intertwined with Typeahead component, get user input.  I would be eager to see a PR or a pairing session that can show how to do this as a unit test -- it would be great to get it in my own wheelhouse.
- I've been getting pushback on the notion of integration tests ... so 🤷‍♀ .  why should I concern myself with writing tests that half of us never write, or don't find useful?
@jcoyne @jermnelson:  Note that this is very nearly an undo of …

InputListLOC: changes redux state once again

---

package-lock.json
package.json
src/components/App.jsx
src/components/editor/property/InputListLOC.jsx
src/components/editor/property/InputLookupQA.jsx

this puts us on the latest version of `eslint-plugin-react`.
upgrade eslint-plugin-react, clean up newly found lint.
* add propTypes declarations
* fix a test that wasn't actually testing what the code was trying to do, and which led to an error under stricter type checking
closes #468
**note**:  i always get changes of the sort seen in the second commit when i `npm install`.  is there any harm in resolving those packages to specific `https://registry.npmjs.org` URLs?  the specificity maybe even seems desirable to me from a stability/reproducibility/security standpoint?  but maybe there are downsides i'm unaware of?
i can't really find any advice on the subject.  the most relevant thing i came across was:
https://stackoverflow.com/a/53827243 …

npm update eslint-plugin-react

---

src/selectors/resourceSelectors.js

the current intent seems to be safe access to `obj`, and return of `undefined` if `obj[key]` is undefined.  it seems like the logic replaced by this commit does that, albeit likely in an unintended way (if `obj[key]` was undefined, it'd have been returned, but by the if branch of the replaced ternary operation instead of the else branch)..

simplify findNode conditional logic

---

__tests__/components/home/NewsItem.test.js
src/components/home/NewsItem.jsx

so presentation on home page is always up to date, instead of hardcoding it independently
(noticed this when reviewing https://github.com/LD4P/sinopia_editor/pull/892/files#diff-5083dfea3973f64f536edf318a38b904R9, had it in my notes as a small todo)

NewsItem: get the version number from package.json

---

docker-compose.yml

This fixes the link between the editor and trellis and elasticsearch when using dockder compose.
If the build args are necessary, I can add those back in, but without ENV vars on the editor block I was unable to make much use of docker-compose.
Not this is necessary for #442 development

Fix docker-compose: move build args into env vars

---

docker-compose.yml

The prior change was a result of a mismatch in what I had running in docker. the INDEX_URL needs to be a build argument as the editors env vars are not available at runtime (per @mjgiarlo)

Revert #924 - add index_url to build args

---

server.js

So that javascript running on dev-server can use the search feature (when running on different ports)

Set CORS headers

---

__tests__/components/editor/ResourceTemplateForm.test.js
__tests__/components/editor/property/InputLiteral.test.js
__tests__/components/editor/property/InputLookupQA.test.js
__tests__/components/editor/property/InputURI.test.js

There is no PropertyRemark element.  These tests were only passing because the find returns an empty object, which is a truthy value

Remove tests for PropertyRemark

---

server.js

express.json() drops the posted body when running a search, using body-parser captures it properly.

Use body-parser.json over express.json

---

__tests__/components/editor/property/InputListLOC.test.js
__tests__/components/editor/property/InputLiteral.test.js
__tests__/components/editor/property/InputLookupQA.test.js
__tests__/components/editor/property/InputURI.test.js

The find statement always returns an object, which is always truthy.  In fact, since these are shallow renders, it's useless to look for a grandchild component

Fix bad tests

---

Dockerfile
src/Config.js

This default should work in production, and when developing locally one could set SEARCH_HOST
Fixes #1001

Provide a sensible default for Config.searchHost

---

.github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md

Not entirely sure if this is helpful, but trying to make the "regular issue" link a little more obvious.

Clarify link to regular github issues in the issue template

---

__tests__/components/templates/ImportResourceTemplate.test.js
src/components/templates/ImportResourceTemplate.jsx

Fixes #1044 
Adds a call to `fetchResourceTemplateSummaries` after a template is imported/created.
NOTE: Integration test failures are unrelated to this PR and being worked on separately.

Reload the resource tempaltes summaries after import

---

.dockerignore
Dockerfile

... these are built during the `npm run build` command so it seems redundant. I've got this version deployed in dev (for now) to ensure there are no major differences and can be used as a test.
This also improves the speed of builds.

Do not copy the dist and nodmodules into the image

---

src/components/search/SearchResults.jsx

This avoids an error where react asks for each child component to have a key

Change keyField to a field that exists on the results

---

__tests__/components/editor/property/RequiredSuperscript.test.js
src/components/editor/property/RequiredSuperscript.jsx

Fixes #1024 
(note - tooltip still works, of course)

make "required" asterisk same color as text

---

src/components/editor/ResourceTemplate.jsx
src/components/editor/ResourceTemplateForm.jsx
src/components/editor/property/PropertyPanel.jsx
src/styles/main.css

Use a balanced 2-column layout on large screens and a single column layout on small screens.
Avoid having to precalculate left or right
Before:
After:

Make the layout responsive.

---

__tests__/components/editor/property/PropertyActionButtons.test.js
__tests__/components/editor/property/PropertyResourceTemplate.test.js
__tests__/components/editor/property/PropertyTemplateOutline.test.js
__tests__/components/editor/property/ResourceProperty.test.js
src/components/editor/property/PropertyActionButtons.jsx
src/components/editor/property/PropertyResourceTemplate.jsx
src/components/editor/property/PropertyTemplateOutline.jsx
src/components/editor/property/ResourceProperty.jsx

Fixes #1100 "A disabled button is confusing to a user, if the property is not repeatable, don't show the button rather than disabling it."
Please review carefully as I'm not awesomely confident in whether I did this properly.  Aside from the tests, I did empirically prove the code in my local instance.
Note:  I saw a disabled add button in OutlineHeader component that I don't fully understand, and I'm assuming it's not relevant.  https://github.com/LD4P/sinopia_editor/blob/master/src/components/editor/property/OutlineHeader.jsx#L43
```
<button type="button" className="btn btn-sm btn-toggle" onClick={props.handleToggle} data-id={props.id} disabled={isAdd}>
<FontAwesomeIcon icon={icon} />
</button>
```

"Add another" button for property is hidden rather than disabled

---

__tests__/components/editor/property/InputLiteral.test.js
src/components/editor/ResourceTemplateForm.jsx
src/components/editor/property/InputLiteral.jsx

This prevents data loss if they didn't press 'enter' before saving
Fixes #1072

Add literal onBlur

---

src/components/editor/property/InputURI.jsx

Bootstrap styles don't allow for labels that wrap the input

---

__tests__/actionCreators/search.test.js
__tests__/components/search/SearchResultsPaging.test.jsx
src/Config.js
src/actionCreators/resources.js
src/actionCreators/search.js
src/actions/index.js
src/components/search/Search.jsx
src/components/search/SearchResultsPaging.jsx
src/reducers/index.js
src/reducers/search.js
src/sinopiaServer.js
src/store.js

Fixes #1082 
Note: Integration testing of search will come in a follow up PR addressing #1089 
UI Notes:
- Paging includes a first page, previous page, next page, and last page button.
- First, previous, next, and last buttons are disabled as necessary
- Current page is shown as active
- Total result count and current result span are displayed.

Add search paging

---

__tests__/actionCreators/resources.test.js
__tests__/components/editor/GroupChoiceModal.test.js
__tests__/reducers/index.test.js
src/actionCreators/resources.js
src/actions/index.js
src/components/editor/GroupChoiceModal.jsx
src/reducers/index.js

Closes #1051
This is a refactor;  no functionality change expected.
Please review carefully;  I'm pretty sure I got it right but it's my first thunk.
Also wondering if GroupChoiceModal component tests adequately assert the appropriate plumbing methods are called

[Refactor] GroupChoiceModal uses thunk for saving to trellis

---

__tests__/integration/previewRDFHelper.js
src/components/editor/property/InputListLOC.jsx
src/components/editor/property/InputLookupQA.jsx
src/components/editor/property/InputLookupSinopia.jsx

closes #581
So this isn't perfect (you have to hit backspace twice to delete a value in a typeahead box), but better than the reported bug.

Fixes typehead bug when hitting backspace key.

---

__tests__/components/editor/property/InputValue.test.jsx
__tests__/integration/literal.test.js
src/components/editor/property/InputLiteral.jsx
src/components/editor/property/InputValue.jsx

closes #1136
Note that this needs to be rebased after https://github.com/LD4P/sinopia_editor/pull/1133 is merged.

Retain language after editing InputLiteral

---

src/components/search/SearchResultsPaging.jsx

Force rounding up for the last page of the list of search pages. This fixes a bug where if the number of results was < 50% of filling the final page, the page count was rounded down. Forces rounding up so final page is not missed.

Force rounding up for last page of paging.

---

__tests__/ResourceValidator.test.js
__tests__/__fixtures__/lookupWithValueTemplateRefs.json
__tests__/fixtureLoaderHelper.js
__tests__/integration/propertyTemplateMisconfigured.test.js
src/ResourceValidator.js
src/components/editor/property/PropertyComponent.jsx
src/utilities/propertyTemplates.js

Fixes #1122.
note no display of error except in console ... (you can tell I clicked the Add button because it's darker blue ...)

Display error for bad prop template

---

__tests__/__fixtures__/MonographInstance.json
__tests__/__fixtures__/adminMetadata.json
__tests__/integration/loginHelper.js
static/lookupConfig.json

Per issue https://github.com/LD4P/qa_server/issues/141, subauthorities are being removed for LCSH.

remove subauthorities for LCSH

---

src/sinopiaServer.js

fixes #1171 
This change from #1165 doesn't appear to have changed the results from a title & subtitle search, so `title` is still required.

Reverts change to title field for searches

---

src/components/editor/property/InputLookupQA.jsx

To fix:
```
Warning: Failed prop type: Invalid prop `options` of type `array` supplied to `InputLookupQA`, expected `object`.
in InputLookupQA (created by Context.Consumer)
in Connect(InputLookupQA) (created by PropertyComponent)
in Suspense (created by PropertyComponent)
in PropertyComponent (created by ResourceTemplateForm)
in div (created by PropertyPanel)
in div (created by PropertyPanel)
in PropertyPanel (created by Context.Consumer)
in Connect(PropertyPanel) (created by ResourceTemplateForm)
in div (created by ResourceTemplateForm)
in form (created by ResourceTemplateForm)
in div (created by ResourceTemplateForm)
in ResourceTemplateForm (created by Context.Consumer)
in Connect(ResourceTemplateForm) (created by ResourceTemplate)
in div (created by ResourceTemplate)
in div (created by …
```

Fixed proptype for InputLookupQA.

---

__tests__/components/App.test.js
src/components/App.jsx

This avoids a brief 404 that was occurring before a session was available.
It also changes routing so if a user is not logged in, all routes go to the home page.

Avoid 404 flash.

---

.github/ISSUE_TEMPLATE/tagged-release.md
README.md

Updated docs and issue template for checking and uploading supporting repo's tagged images

README and Tagged Release Template Issue changes

---

__tests__/__fixtures__/MonographInstance.json
__tests__/components/editor/property/RenderLookupContext.test.js
src/components/editor/property/RenderLookupContext.jsx

Updating context rendering component to handle objects that come back as values in context.
For example, broader concepts in genre form lookup come back as
values": [
{
"uri": "http://id.loc.gov/authorities/genreForms/gf2011026049",
"id": "gf2011026049",
"label": "Animated films"
}
]
The code now looks for "label" in the value object and displays that.  If there is no label but there is a uri, it will display that instead, and if neither, then it will display a stringified version of the json object

#1200 handle objects in context

---

static/lookupConfig.json

* add lookups for Alberta, Cornell, Colorado, and Duke including subauths for works, superworks, and instances
* update Frick with subauths for work, superwork, and instance
* remove old Cornell configs
NOTE: Stanford and UCSD are still using old data.

update ShareVDE authorities

---

static/lookupConfig.json

The  authority for https://id.loc.gov/vocabulary/organizations no longer returns the expected JSON list of codes expected by the `InputListLOC` component.
For #1208

Removes LOC orgs from Config

---

static/lookupConfig.json

Assuming https is the desired URI based on existing list entries, even though the canonical is http.

List lookups based on cohort requests LC Profiles

---

static/lookupConfig.json

The only one not yet completed is for Harry Ransom.  We are still working on some access issues for that one.
This also removes access to the old sharevde data for Stanford and UCSD.

add remaining sharevde lookups

---

.github/ISSUE_TEMPLATE/tagged-release.md

Updated to include step for deploying to staging (rather than wait for ops).

Updated tagged-release template

---

__tests__/utilities/qa.test.js
src/utilities/qa.js

If the QA authority doesn't support context still returning expected results. The `InputLookupQA` component handles the presence of context property in the returned result.  Setting this parameter in the Swagger client to always true may have an impact performance but it also means we don't have to set a context property in each authority in `lookupConfig`. 
Closes #1338

Authorities in QA always request context

---

__tests__/components/templates/ImportFileZone.test.js
src/components/templates/ImportFileZone.jsx

When a DropZone file load fails to execute readAsText, save the error message to the `message` state instead of logging it to the console.

Display flash message instead of console error

---

__tests__/components/editor/property/InputLookupQA.test.js
__tests__/components/editor/property/InputLookupSinopia.test.js
package.json
src/components/editor/property/InputLookupQA.jsx
src/components/editor/property/InputLookupSinopia.jsx
src/components/editor/property/renderTypeaheadFunctions.js

Refactored so type-ahead functions are now exported from a separate file that each lookup component calls.

Lookup sinopia literal

---

static/lookupConfig.json

Fix several configs for getty that were pointing to aat when they should point to tgn or ulan.
Identified in https://github.com/LD4P/qa_server/issues/121

fix getty tgn and ulan pointing to aat

---

__tests__/actionCreators/search.test.js
__tests__/components/search/Search.test.js
__tests__/integration/copyQASearchResult.test.js
__tests__/utilities/qa.test.js
src/actionCreators/search.js
src/actions/index.js
src/components/search/QASearchResults.jsx
src/components/search/Search.jsx
src/reducers/search.js
src/utilities/authorityConfig.js
src/utilities/propertyTemplates.js
src/utilities/qa.js
static/authorityConfig.json
static/searchConfig.json

Fixes #1420
This switches the store from using "authority" to using "uri" which is a unique reference in the `authorityConfig.json`.  Using this `authorityConfig.json` allows it to know that "discogs" is a non-LD source.

Discogs search should use the endpoint configured by authorityConfig.json

---

__tests__/actionCreators/resourceTemplates.test.js
__tests__/components/templates/SinopiaResourceTemplates.test.js
__tests__/test_utilities/testUtils.js
src/actionCreators/resourceTemplates.js
src/components/templates/Download.jsx
src/components/templates/SinopiaResourceTemplates.jsx

Clicking a Resource Template takes you to the Editor with the RT and default values loaded, and allows you to download the resource:
If the list of available resource templates cannot load, an error message is displayed (via redux not the component itself):

Refactor SinopiaResourceTemplates as functional component

---

__tests__/components/templates/UpdateResourceModal.test.js
src/components/templates/ImportResourceTemplate.jsx
src/components/templates/UpdateResourceModal.jsx

This can break the html.  Remove UpdateResourceModal show property because it's always true

Prevent an extra closing div tag

---

__tests__/components/templates/ImportFileZone.test.js
__tests__/components/templates/ImportResourceTemplate.test.js
__tests__/integration/schemaValidation.test.js
cypress/integration/end2end.spec.js
src/components/templates/DropZone.jsx
src/components/templates/ImportFileZone.jsx
src/components/templates/ImportResourceTemplate.jsx

fixes #1602 
Allows a user to upload either a single resource template or a profile. Also, changed some labels to match the new reality.
Note: Some of the work was already done (validation code works fine in both scenarios).
To do:

Allow user to upload rt or profile

---

src/styles/main.css

fixes #1576 
when rendering drop-down menus in the LookupComponent, we should be sure the text is black (since the background is white), so we can read it

override bootstrap CSS to ensure text is black against white background

---

__tests__/components/App.test.js
__tests__/components/editor/Editor.test.js
__tests__/components/editor/RDFModal.test.js
__tests__/components/editor/SaveAndPublishButton.test.js
__tests__/components/editor/property/InputListLOC.test.js
__tests__/components/editor/property/InputLiteral.test.js
__tests__/components/editor/property/InputURI.test.js
__tests__/components/load/LoadByRDFForm.test.js
__tests__/components/templates/SinopiaResourceTemplates.test.js
__tests__/integration/copyQASearchResult.test.js
__tests__/integration/nestedResources.test.js
__tests__/integration/previewSaveIncompleteResource.test.js
__tests__/integration/previewSaveResource.test.js
__tests__/reducers/index.test.js
__tests__/reducers/inputs.test.js
__tests__/selectors/resourceSelectors.test.js
src/components/editor/ErrorMessages.jsx
src/components/editor/SaveAndPublishButton.jsx
src/components/editor/property/InputListLOC.jsx
src/components/editor/property/InputLiteral.jsx
src/components/editor/property/InputLookupQA.jsx
src/components/editor/property/InputLookupSinopia.jsx
src/components/editor/property/InputURI.jsx
src/components/editor/property/OutlineHeader.jsx
src/reducers/index.js
src/reducers/inputs.js
src/selectors/resourceSelectors.js
src/store.js

This re-organizes and renames resource validation state to make it consistent with other state conventions and to have clearer naming. This is in preparation for upcoming work on handling errors.

Cleans up resource validation state.

---

__tests__/components/editor/ResourceURIMessage.test.js
src/components/editor/ResourceURIMessage.jsx

Copy URI button now has `btn-secondary` css class so looks more like a button. When clicked, the text changes to _Copied URI  to Clipboard_ for 3 seconds before reverting back to *Copy URI* 
Fixes #1588

Copy URI "button" improvements

---

__tests__/utilities/qa.test.js

QA authority error that was fixed in PR https://github.com/LD4P/sinopia_editor/pull/1650 broke a QA test.

Removing test that depended on qa authority failure

---

__tests__/components/editor/property/InputListLOC.test.js
__tests__/components/editor/property/renderTypeaheadFunctions.test.js
__tests__/test_utilities/testUtils.js
src/components/editor/property/InputListLOC.jsx
src/components/editor/property/InputLookupQA.jsx
src/components/editor/property/InputLookupSinopia.jsx
src/components/editor/property/renderTypeaheadFunctions.js

For the `InputListLOC` and `InputLookupQA` components, the ordering of the sources is respected when displaying the drop-down menu.
```  "propertyTemplates": [
{
"mandatory": "false",
"repeatable": "true",
"type": "lookup",
"resourceTemplates": [],
"valueConstraint": {
"valueTemplateRefs": [],
"useValuesFrom": [
"urn:ld4p:qa:sharevde_nlm_ld4l_cache:work",
"urn:ld4p:qa:sharevde_alberta_ld4l_cache:work",
"urn:ld4p:qa:sharevde_cuboulder_ld4l_cache:work"
],
"defaults": [],
"valueDataType": {}
},
"propertyLabel": "nlm, alberta, then colorado",
"propertyURI": "http://www.cnn.com"
},
```
This `propertyTemplate` creates this display in the UI:
Fixes #1638

Search Results now use propertyTemplate valueConstraint ordering

---

__tests__/components/search/SinopiaSearchResults.test.js
src/components/search/SinopiaSearchResults.jsx

As discussed during the demo yesterday, the search table 'Title' column should match the word 'Label' used in the sort menu.  Less important, but I also made the 'Modified' column match the language used in the sort drop-down as well.

rename search table columns to match sort option labels

---

__tests__/components/editor/property/InputLookupQA.test.js
src/components/editor/property/InputLookupQA.jsx
src/components/editor/property/renderTypeaheadFunctions.js

One way to leverage the Typeahead component to do what we want here is to use the component's multiple prop in a different way: it should always be set to true, and we can use the component's disabled prop to prevent subsequent multiple entries by passing it the boolean result of an expression that checks both the resource template's repeatable prop along with the length of the selections.
- Removing the disabled prop of the `<Token/>` component allows items to always be removed.
- Use a component ref to force a blur of the input.

Always set multiple prop to true and use function to set disabled prop

---

src/components/Header.jsx

alternate approach to fix #1659 (as compared to work in #1675)
popover documentation at https://getbootstrap.com/docs/4.0/components/popovers/
this simply hides all popovers when a navigation/tab is clicked

hide popovers when a nav link is clicked

---

__tests__/GraphBuilder.test.js
__tests__/ResourceStateBuilder.test.js
src/GraphBuilder.js
src/ResourceStateBuilder.js

When labels for URIs are present in a component's items, the label is used to generate a triple using `rdfs:label` in the Graph builder. When loading RDF back into the editor, the items label is set if to the `<uri> rdfs:label <label> ` is present.
Fixes #1641

Lookup URI labels now persist and also load from RDF

---

__tests__/components/editor/property/InputLookupSinopia.test.js
__tests__/components/editor/property/OutlineHeader.test.js
__tests__/integration/validationErrors.ppt.js
src/components/editor/property/InputListLOC.jsx
src/components/editor/property/InputLiteral.jsx
src/components/editor/property/InputLookupQA.jsx
src/components/editor/property/InputLookupSinopia.jsx
src/components/editor/property/InputURI.jsx
src/components/editor/property/OutlineHeader.jsx
src/components/exports/Exports.jsx
src/components/load/LoadByRDFForm.jsx
src/components/search/Search.jsx

fixes #1714 (and some related items)
see https://getbootstrap.com/docs/4.3/migration/#forms-1 for bootstrap update documentation
It is possible we may also need to remove the `.has-error` class on form elements and decorate those elements with `required`, but that may require changes to the components that render the form elements, so not undertaking that here.

update some deprecated styles in bootstrap 4

---

__tests__/actionCreators/resources.test.js
src/actionCreators/resources.js

Previously only the first nested resource was expanded.
Fixes #1715

Expand all nested resources when loading resource

---

__tests__/__fixtures__/WikidataLookup.json
__tests__/fixtureLoaderHelper.js
static/authorityConfig.json

This adds a basic wikidata lookup from QA.  It is a non-linked data lookup and provides results in a format consistent with the normalized linked data search results.
Example:
```
[
{
"id": "Q8495",
"uri": "http://www.wikidata.org/entity/Q8495",
"label": "milk",
"context": [
{
"property": "label",
"value": "milk"
},
{
"property": "title",
"value": "Q8495"
},
{
"property": "description",
"value": "white liquid produced by the mammary glands of mammals"
}
]
},
...
]
```

add basic wikidata lookup

---

__tests__/components/templates/ImportFileZone.test.js
__tests__/components/templates/ImportResourceTemplate.test.js
__tests__/integration/schemaValidation.test.js
cypress/integration/end2end.spec.js
src/components/templates/ImportFileZone.jsx
src/components/templates/TemplateSearch.jsx

(sort of) fixes #1792 
I was able to more or less get the search bar and import button on the same line, but if you shrink your screen down, the search box overruns the import button (due to a fixed pixel setting for the width of the search box).  If you do the right thing and make the search box width = 100%, then it comes out too small to show the placeholder text.  I can't figure out how to get the search bar and the import button to make better use of the space available otherwise.

best attempt to get to design of new import button

---

src/components/search/QASearchResults.jsx
src/components/search/SinopiaSearchResults.jsx

fixes #1758 
- added scroll to top for opening a template from QA search results
- added new scroll to top code for the error case of opening a resource that triggers an error (like a validation error on the resource template)

scroll to top on edit template error

---

__tests__/components/editor/actions/CloseButton.test.js
src/components/editor/ResourcesNav.jsx
src/components/editor/actions/CloseButton.jsx

The default CloseButton will use the resourceKey of the current resource, but it will also accept a resourceKey as a prop to handle the case when it should close a different resource than the current one.

Fix close button bug by passing in resourceKey as a prop

---

__tests__/components/editor/SaveAlert.test.js
src/components/editor/SaveAlert.jsx

An ellipsis indicates an ommission of a word or phrase, but it's unclear what is omitted in this case.

Removed unnecessary ellipsis

---

__tests__/components/home/NewsPanel.test.js
src/components/home/NewsPanel.jsx

Previously it was using a one-column layout if there were login errors.
Fixes #1907

Always use the 2 column login layout.

---

__tests__/GraphBuilder.test.js
__tests__/actionCreators/resources.test.js
__tests__/components/editor/actions/CloseButton.test.js
__tests__/components/editor/actions/SaveAndPublishButton.test.js
__tests__/selectors/resourceSelectors.test.js
src/GraphBuilder.js
src/actionCreators/resources.js
src/selectors/resourceSelectors.js
src/sinopiaServer.js

Fixes #1753
To be discussed/tested before merging and going with this approach:
1. With the changes in this branch, how does/will the editor handle the currently broken triples coming back from Trellis? (I *think* they will load since we have code in place for handling null subjects in N-Triples data, but I could be mistaken.)
2. Assuming all is copacetic with (1) above, will the code in this branch automagically handle migration of data that needs fixing, or do we need a more intentional and systematic migration strategy for all the broken data?
3. When this is deployed, what effect will it have on open sessions (particularly w/ regard to the changes in this branch related to checking to see if a resource has changed, which used to do this check by hashing the N-Triples representation …

Persist RDF to Trellis using Turtle

---

src/styles/main.scss

fixes #1909 
see screenshots below - we can also adjust it smaller/bigger than shown if desired
note: may not be supported in all browsers (tested in firefox and chrome mac, where it works fine, didn't notice a change in safari)

increase radio button size

---

__tests__/ResourceTemplateValidator.test.js
src/ResourceTemplateValidator.js
src/utilities/propertyTemplates.js

Fixes #1858 
Also removed unused argument in function call and corrects a typo.

Check if typeahead authorities are configured before checking for known tag names

---

__tests__/components/editor/property/renderTypeaheadFunctions.test.js
src/components/editor/property/renderTypeaheadFunctions.js

Currently the editor when is doing a lookup, if the user adds a valid URI (not found in the lookup itself) the correct label is being displayed but we're not adding an "uri"
In the RDF preview, the following RDF is generated with both values being literals:
This PR fixes this bug and results in the following:

Sets correct option key for URIs vs. strings

---

package-lock.json
package.json

was unable to push to master per release issue template instructions, creating PR for version bump.
~~discussed w/ @jermnelson, who suggested just approving and merging myself, since i'd have pushed directly to master.~~
actually i am not allowed to self-approve (makes sense).

bump version to 2.0.5

---

.github/ISSUE_TEMPLATE/tagged-release.md

can't push directly to master per old instructions, since it's a protected branch.  results in error like:
```
$ git push
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 8 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 423 bytes | 211.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: At least 1 approving review is required by reviewers with write access.
To github.com:LD4P/sinopia_editor.git
! [remote rejected]   master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:LD4P/sinopia_editor.git'
```
i also …

update version bump instructions

---

static/authorityConfig.json

Add new authorities for CERL and Ligatus.
Update MeSH to include subauths.  There is not full search of MeSH, so it defaults to search the subject subauth.  This prevents breaking of any existing resource templates.

add CERL, Ligatus, and subauths for MeSH

---

static/authorityConfig.json

Per Nancy, also removes MeSH default.
See also... https://github.com/LD4P/sinopia_profile_editor/pull/315

fix typo in MeSH publication types subauth

---

static/authorityConfig.json

Partial fix for #2125 
This is a simple renaming to include ` - cache` or ` - direct` after the label for all OCLC authority/subauth pairs to clearly identify the source of the data.  The name of the authority config in QA for direct access changed.  This is also reflected in this PR.  The config name change will have no effect on the data or function.

identify whether OCLC FAST data is coming from our cache or OCLC

---

src/components/editor/RDFModal.jsx

Reduces this expensive operation to only when RDFModal is visible.

Only build graph when RDFModal is displayed.

---

__tests__/reducers/languages.test.js
src/reducers/languages.js

Two new tests and copied `languagesReceived()` from `__tests__/reducers/entities.test.xjs` for  `reducers/languages.js`. Fixes #2247

Tests Language Reducer

---

__tests__/reducers/search.test.js

Tests `clearSearchResults`, `clearTemplateSearchResults`, `setSearchResults`, and `setTemplateSearchResults` function in search reducer. Fixes #2249

Testing Search Reducer

---

README.md
__tests__/reducers/resources.test.js
__tests__/selectors/resources.test.js
__tests__/testUtilities/stateUtils.js
src/actionCreators/resourceHelpers.js
src/actionCreators/resources.js
src/actions/resources.js
src/components/editor/property/InputListLOC.jsx
src/components/editor/property/InputLiteral.jsx
src/components/editor/property/InputLookup.jsx
src/components/editor/property/InputURI.jsx
src/reducers/index.js
src/reducers/resources.js
src/selectors/resources.js
src/store.js
src/utilities/valueFactory.js

This changes the approach for determining if a resource has changed so that it does not rely on the GraphBuilder.

Removed building graph to see if resource has changed.

---

__tests__/sinopiaSearch.test.js
src/sinopiaSearch.js

We are moving to using multiple nodes in our AWS Elasticsearch cluster; as part of this work we needed to upgrade to 
AWS Elasticsearch version 7.4. The search result object returned from Elasticsearch slightly changed with the total hits moving from a integer to a object containing a value key. This PR updates the sinopiaSearch along with updating the tests to support this change. This PR depends on a new `sinopia_indexing_pipeline` PR https://github.com/LD4P/sinopia_indexing_pipeline/pull/212 being merged and available. We will need this PR merged before upgrading Elasticsearch on stage and production.

Search result updates for Elasticsearch Upgrade

---

__tests__/feature/editing/addRemove.test.js

With PR #2318 being merged, required panels no longer have an `+Add` or trash button causing test to fail.

Removes failing feature test

---

src/components/editor/property/InputLookup.jsx

InputLooks were querying once they had a value and any property changed. This means that changing other inputs was causing a re-query.
Locally.
No.

Stop InputLookup from re-querying when a prop changed.

---

package-lock.json
package.json

The SUL `access-update-scripts` did not create a dependency update PR; ran `npm update` to create manual dependencies update PR.
Ran testing suite.
n/a

Ran npm update because auto dependency updates failed to run

---

__tests__/feature/editing/editingLiteral.test.js
__tests__/feature/editing/editingUri.test.js

A small bug fix in tests. I found that `toBeDisabled` always returns true because it's actually a function and should be called as `toBeDisabled()` - I'm unclear why this isn't an error.
N/A
N/A

toBeDisabled always returns a positive the correct call is toBeDisbled()

---

.eslintrc.js
__tests__/feature/userAuthentication.test.js
__tests__/testUtilities/stateUtils.js

* tests for logout, login as another user, and login with the wrong password
* eslint config tweak to allow placeholder params in mocks
* tweak to default state to provide signout callback for user
to increase feature test coverage.
closes #2274
PR is solely additional feature tests.
minor tweak to eslint config to allow `_` prefixed params to be ignored by the `no-unused-vars` rule, so that mock params can match those of the real life object (even though the mock implementation doesn't need the param).

feature tests for user authentication

---

__tests__/selectors/errors.test.js
__tests__/testUtilities/stateUtils.js

Adds tests for `selectors/errors`. Fixes #2251  
Updates `testUtilities/stateUtils` to add various errors to state objects that can be tested.

Test selector errors

---

__tests__/components/home/LoginPanel.test.js
src/components/home/LoginPanel.jsx

Fixes #2376 by adding the role attribute to the LoginPanel authentication error div
Modified the existing test's CSS selector to look for the div's role attribute instead of the classname

Adds aria alert role to LoginPanel authentication error div

---

__tests__/feature/exportFile.test.js
__tests__/testUtilities/stateUtils.js

Fixes #2273. Tests that download links appear on the exports page. Otherwise the actual downloading is just the normal browser download behavior.

Adds test for downloads links of Sinopia export files

---

__tests__/components/LongDate.test.js
src/components/LongDate.jsx

closes #2363
So that null resource template dates are not rendered.
Unit test
NA

Handles null property template date.

---

__tests__/feature/editing/saveAndCopyResource.test.js

Extends saveResource test to also test copying the saved resource to a new duplicate resource
Fixes #2260 #2267

Extends saveResource test to also test copying the resource

---

README.md
docker-compose.yml

Reduce the number of containers run by default.
NA
README.

Comment out monitoring apps in docker-compose.

---

README.md
__tests__/TemplatesBuilder.test.js
__tests__/__action_fixtures__/expandProperty-ADD_VALUE.json
__tests__/__action_fixtures__/loadResource-ADD_SUBJECT.json
__tests__/__action_fixtures__/newResource-ADD_SUBJECT.json
__tests__/__action_fixtures__/newResourceFromDataset-ADD_SUBJECT.json
src/TemplatesBuilder.js
src/components/templates/SinopiaResourceTemplates.jsx

To fix #2362 
Although the same component is being used to render resource template rows in both the recent and full list, the data structure passed to the component is not the same, and in the case of the recent templates, it didn't have the expected full template URI.  This adds it.
`props.row.uri` was undefined in the recent templates structure here: https://github.com/LD4P/sinopia_editor/blob/master/src/components/templates/ResourceTemplateRow.jsx#L37
localhost development environment

allow for recent templates to be editable with button

---

__tests__/feature/editing/openAndCloseResource.test.js
__tests__/feature/searchAndOpenTemplate.test.js

Fixes #2258.
Did not test the error when opening an invalid resource template. I think that should be a separate test. If agreed, I can make a ticket for that and work on it.
(Also added to this PR, I truncated the import statement on `openAndCloseResource.test`)

Adds test for searching for a template and then opening the template from the recently used list

---

__tests__/actionCreators/resources.test.js
package-lock.json
package.json
src/actionCreators/resources.js

Fixes #2239, adds missing action to `contractProperty`.
Run test suite
n/a

New tests for actionCreators/resources

---

README.md

Per a slack discussion where @jermnelson provided new information about adding new fixture templates
README

Update readme with information about adding new fixtures

---

__tests__/feature/editing/saveAndCopyResource.test.js
__tests__/feature/invalidTemplate.test.js

Fixes #2421 
(Also removes duplicate  `scrollIntoView = jest.fn()` mock found in saveAndCopyResource.test)

Adds test for loading an invalid template

---

README.md
__tests__/feature/editing/editingLiteral.test.js
cypress/integration/end2end.spec.js
cypress/integration/leftNav.spec.js
package-lock.json
package.json
src/components/editor/property/InputLiteral.jsx

Fixes #2177
Note that a UI change here is switching from an input element to a textarea element for all input literals. Why? Because as far as I can tell, input elements are not auto-resizable in HTML.
I briefly looked into rolling my own auto-resize logic but it is over my head, even without all the React machinery in the way. I also looked into using contentEditable but I believe that approach is geared towards divs and spans rather than input elements (such as textarea) within a form.
I'm not sure if the small test change is sufficient to test this commit. Advice welcome! I suspect that the line I removed from the input literal test, which began failing, is due to moving from an input element to a textarea element.
Also includes:
* Clarify in README how to start Express server
In …

Auto-resize input literals to reduce scrolling

---

src/components/editor/actions/CloseButton.jsx
src/components/editor/actions/CloseResourceModal.jsx

Fixes #2057
The prior implementation of CloseResourceModal used the selectCurrentResourceKey to figure out which resource the CloseButton should close, and that was the bug. Instead, the CloseButton should tell the CloseResourceModal what its resource is and it should close that resource.
This change was tested in the browser and confirmed working. See linked screen capture:
I briefly entertained the idea of adding unit tests for CloseButton and CloseResourceModal but it seemed of little value to test properties injection which is core React functionality. Given also that 1) such tests would not make it apparent that this bug is related to the tests, 2) my familiarity with React testing is relatively low, and 3) this is fixing a production bug, I decided not to add any automated tests in …

Make resource close button close the expected tab

---

__tests__/feature/editing/editingLiteral.test.js
package.json

closes #2432
We have `request` listed as a dependency, but don't use it directly.
Unit / integration
NA

Removes request as a dependency.

---

docker-compose.yml

This may be something only I'm seeing, or there may be a better approach, but the `restart: always` configs here mean that the mongo resources are configured to always start when docker-desktop starts. This is not ideal for local resources where we don't want an extraneous service running when we're not working on this project.
In order to remove the restart directive, `docker-compose up -d` needs to run with this config (including the `restart: "no"`, we can likely eventually just remove the restart directive all together, but if you've already run the current config, you need to force it to get the new no-restart.
If we need the restart directive, perhaps `restart: unless-stopped` would be more appropriate so we can actually stop the thing.
Locally
N/A

Do not restart docker resources

---

src/components/editor/property/InputLiteral.jsx

This will allow the form to be valid without having to press the enter key.
Fixes #2361
This was caused by https://github.com/LD4P/sinopia_editor/commit/869e3ca1c0cbb6add1771aed45faebdbddf3609f#diff-c8159322c93a06854f45e72e68ffdfd3R95

Create the value onBlur

---

__tests__/feature/editing/openAndCloseResource.test.js
__tests__/feature/loadNewResource.test.js
src/components/editor/property/PanelResourcePropertyNavItem.jsx
src/components/editor/property/PanelResourceSubjectNavItem.jsx
src/components/editor/property/PanelResourceTopNavItem.jsx

Fixes #2419
To fix #2419.
This commit has a few different components:
* Subject nav items should inject the resource key property into its property nav items
* Property nav items should check their resource key (see prior bullet) to determine if they are the currently selected property nav item and, if and only if they are, they should render their child navigation items
* Top-level navigation items should include an aria-label, partly for a11y purposes and partly to facilitate integration testing
CI and local in-browser testing. See demo of changes here:
None

Expand current property navigation item only

---

__tests__/components/App.test.js
__tests__/feature/exportFile.test.js
__tests__/testUtilities/stateUtils.js
src/actionCreators/exports.js
src/actionCreators/languages.js
src/components/exports/Exports.jsx
src/selectors/exports.js
src/selectors/languages.js

So that http calls are not made during tests (e.g., to retrieve export list.)
Unit / feature
NA.

Test tweaks

---

.github/ISSUE_TEMPLATE/tagged-release.md

Better reflects the actual process for creating a tagged release by removing old projects and adding the Sinopia API.
n/a
n/a

Updated template for New Release Procedures

---

__tests__/feature/editing/openAndCloseResource.test.js
__tests__/feature/editing/saveAndCopyResource.test.js
__tests__/feature/searchAndOpenTemplate.test.js
src/components/editor/ResourcesNav.jsx
src/styles/header.scss
src/styles/main.scss
src/styles/resourceTabs.scss

Looks like this now:
Fixes #2438

Update styles for resource tabs

---

README.md
__tests__/__action_fixtures__/newResourceCopy-ADD_SUBJECT.json
__tests__/actionCreators/templateValidationHelpers.test.js
__tests__/feature/editing/reordering.test.js
__tests__/reducers/resources.test.js
__tests__/selectors/resources.test.js
__tests__/testUtilities/stateUtils.js
src/actionCreators/templates.js
src/actions/resources.js
src/components/editor/property/NestedResource.jsx
src/components/editor/property/NestedResourceActionButtons.jsx
src/reducers/index.js
src/reducers/resources.js
src/selectors/resources.js
src/sinopiaApi.js
src/styles/main.scss

closes #2358
Support re-ordering of nested resources, in particular, re-ordering of property templates when editing a resource template.
This can be tested when creating a new resource template or using Uber template 1 > property 19.
Unit tests, feature test, locally.
NA

Adds re-ordering of nested resources.

---

__tests__/__action_fixtures__/loadResource-ADD_SUBJECT.json
__tests__/__action_fixtures__/newResource-ADD_SUBJECT.json
__tests__/__action_fixtures__/newResourceFromDataset-ADD_SUBJECT.json
__tests__/__template_fixtures__/uber_template1.json
__tests__/feature/editing/addRemove.test.js
__tests__/feature/loadNewResource.test.js
__tests__/feature/previewRdf.test.js
cypress/fixtures/uber_template1.txt
src/actionCreators/resourceHelpers.js

Fixes #2371
Added a new property template literal field that has required and default values and confirmed they show up on the page and in the preview RDF.  Had to modify existing tests to account for this new field.
None

do not overwrite default values if exist

---

__tests__/components/editor/RDFDisplay.test.js
__tests__/feature/previewRdf.test.js
src/components/editor/RDFDisplay.jsx
src/components/editor/RDFModal.jsx
src/components/editor/ResourceComponent.jsx
src/selectors/modals.js

Fixes #2424. RDFDisplay should receive a dataset instead of an RDF string to avoid overloading the browser memory when calling the `toCannonical` method on the rdf dataset. Adds a selector in `selectors/modals` to set the unusedRDF state.
Updated tests for previewRDF and RDFDisplay components.

Fix template error

---

src/components/editor/property/InputValue.jsx
src/styles/main.scss

Move styles to stylesheet
Having multiple instances of an id is not permitted.  Stylesheets is the best place for static styles.

Remove ids that are not unique in the document

---

src/styles/main.scss

Part of #2439 - Changes the background color of the card header and panel, and removed the border:
BEFORE:
AFTER:
N/A
N/A

Change background color for resources in editor

---

src/reducers/search.js

Fixes #2050 by setting the proper templateSearchResultsPerPage variable to be used instead of searchResultsPerPage.
Manually
N/A

Use proper resultsPerPage variable for templates

---

src/components/editor/property/InputLookupQA.jsx
src/components/editor/property/InputLookupSinopia.jsx
src/utilities/Search.js

And remove them from the components
These utility functions share similar logic and are business logic, so they don't belong in the view layer.

Consolidate search utility functions

---

__tests__/actionCreators/resources.test.js
__tests__/feature/editing/addRemove.test.js
__tests__/reducers/resources.test.js
src/actionCreators/resourceHelpers.js
src/actionCreators/resources.js
src/actions/resources.js
src/reducers/index.js
src/reducers/resources.js

Fixes #2371 and #2461 
Get rid of `removeProperty` that does appear to be used anymore.
TODO:
None

ensure expanded field has default values if they exist

---

src/components/home/NewsItem.jsx

Causing an error when trying to render the apostrophe in NewsItem.
Ran testing suite.
n/a

Removed backticks that were causing rendering error

---

__tests__/reducers/templates.test.js
src/Config.js
src/components/templates/NewResourceTemplateButton.jsx
src/reducers/templates.js
src/sinopiaApi.js
src/sinopiaSearch.js

Fixes #2510
To prevent showing the root resource template in the editor history.
Includes:
* Add root resource template ID to configuration
* Import config consistently across the app
* Do not add root resource template ID to history
CI. 
**NOTE**: I can't get the containers to spin up without using up all available swap space on my laptop, so I am limited in my testing until new RAM shows up. Can someone pull down this branch and test it for me?
Added a config for root resource template ID.

Do not add root resource template ID to history

---

__tests__/actionCreators/exports.test.js
__tests__/actionCreators/languages.test.js
__tests__/components/App.test.js
__tests__/reducers/exports.test.js
__tests__/reducers/languages.test.js
__tests__/reducers/lookups.test.js
__tests__/reducers/templates.test.js
__tests__/selectors/templates.test.js
__tests__/testUtilities/stateUtils.js
src/actionCreators/languages.js
src/actions/languages.js
src/components/editor/property/InputLang.jsx
src/reducers/exports.js
src/reducers/index.js
src/reducers/languages.js
src/reducers/lookups.js
src/reducers/templates.js
src/selectors/exports.js
src/selectors/languages.js
src/selectors/lookups.js
src/selectors/templates.js
src/store.js

This is one of several PRs for making our reducers stop mutating state in accordance with Redux best practice. To assist with that, state is being made more shallow by eliminating `selectorReducer`.
Unit/feature.
NA

Move more out of selectorReducer

---

__tests__/actionCreators/resources.test.js
__tests__/feature/searchAndViewResource.test.js
__tests__/reducers/resources.test.js
__tests__/selectors/resources.test.js
__tests__/testUtilities/stateUtils.js
src/actionCreators/resources.js
src/actions/resources.js
src/components/ViewResourceModal.jsx
src/components/editor/ResourceComponent.jsx
src/components/editor/property/InputListLOC.jsx
src/components/editor/property/InputLiteral.jsx
src/components/editor/property/InputLookup.jsx
src/components/editor/property/InputLookupQA.jsx
src/components/editor/property/InputURI.jsx
src/components/editor/property/InputValue.jsx
src/components/editor/property/LanguageButton.jsx
src/components/editor/property/NestedPropertyHeader.jsx
src/components/editor/property/NestedResource.jsx
src/components/editor/property/PanelProperty.jsx
src/components/editor/property/PanelResource.jsx
src/components/editor/property/ResourceList.jsx
src/components/search/SearchResultRows.jsx
src/components/search/SinopiaSearchResults.jsx
src/reducers/index.js
src/reducers/resources.js
src/selectors/resources.js
src/styles/main.scss

Fixes #2172
**NOTE**: Since I made this screencast, I had to pull the change that blurred the background because we don't have a maintainable, testable approach for this in the editor.
To allow catalogers to view resources among search results before editing or copying them.
CI, and in the browser, locally.
None

Add view resource modal to search results rows

---

.eslintrc.js
__tests__/feature/editing/propInfo.test.js
src/components/editor/property/PropertyLabelInfoTooltip.jsx
src/styles/main.scss

Fixes #2539
To make tooltips behave per user expectations.
CI and local browser.
**NOTE**: I fought with RTL/Jest for 1-2 hours and could not get the commented-out test line to pass. That line is the most important line to testing that the clicks work properly. Advice or code are most welcome.
None

Make property tooltips hide when elsewhere is clicked

---

src/styles/main.scss
src/styles/resourceNav.scss

This makes the checkmarks more prominent
Fixes #2447

Remove bullets from the left side navigation

---

src/components/editor/property/LookupWithMultipleAuthorities.jsx

closes #2542
The recent refactoring of selectors broke the Lookup component, as values are no longer being provided by the selector.
Local. The Lookup component needs better testing.
NA

Displays lookup selection.

---

__tests__/feature/editing/propInfo.test.js
cypress/integration/leftNav.spec.js

Connects to #2539
To add test coverage.
By running `npm run cypress-open` locally.
None

Add test coverage for property tooltip behavior

---

__tests__/__template_fixtures__/DiscogsLookup.json
__tests__/__template_fixtures__/Note.json
__tests__/__template_fixtures__/ResourceTemplate.json
__tests__/__template_fixtures__/SinopiaLookup.json
__tests__/__template_fixtures__/Title.json
__tests__/__template_fixtures__/TitleNote.json
__tests__/__template_fixtures__/WikidataLookup.json
__tests__/__template_fixtures__/WorkTitle.json
__tests__/__template_fixtures__/ld4p_RT_bf2_Form.json
__tests__/__template_fixtures__/ld4p_RT_bf2_RareMat_RBMS.json
__tests__/__template_fixtures__/ld4p_RT_bf2_Title_AbbrTitle.json
__tests__/__template_fixtures__/multiple_loc.json
__tests__/__template_fixtures__/nonUniqueValueTemplateRefs.json
__tests__/__template_fixtures__/notFoundValueTemplateRefs.json
__tests__/__template_fixtures__/propertyURIRepeated.json
__tests__/__template_fixtures__/uber_template1.json
__tests__/__template_fixtures__/uber_template2.json
__tests__/__template_fixtures__/uber_template3.json
__tests__/__template_fixtures__/uber_template4.json
__tests__/sinopiaApi.test.js
cypress/fixtures/WorkTitle.txt
cypress/fixtures/uber_template1.txt
cypress/fixtures/uber_template2.txt
cypress/fixtures/uber_template3.txt
cypress/fixtures/uber_template4.txt
src/sinopiaApi.js

closes #2519
The URN of the new resource template lives in the .literal property of the property template, not in the .uri property, due to a recent change in root templates.
Locally and in CI.
NA

Fix RDF loading.

---

src/components/editor/property/InputValue.jsx
src/components/editor/property/NestedPropertyHeader.jsx

This is a holdover from bootstrap 3

Remove inoperative class btn-default

---

src/components/editor/property/InputLiteral.jsx

Fixes #2523 
This fixes the problem by basically forcing the diacritics panel to close anytime focus returns to a new input literal.  If you open the diacritics panel, enter some text, and then click back into the same input field or a new input field, the panel will close.  If you want to enter diacritics again, you toggle it open with the button, and it will be re-connected to the correct input literal.  This (a) prevents the diacritics panel from ever being connected to the wrong input literal (thus fixing the bug), but (b) means that if you click on the same input field you are entering diacritics into, this will also close the diacritics panel.
Reviewing the behavior with Jeremy, and we both agree this is not necessarily a problem... as clicking back into the input literal signifies …

hide previously opened diacritics panels

---

src/styles/resourceNav.scss

This ensures that centering the text at high font sizes doesn't contribute to an unbalanced indent structure
Fixes #2565

Align buttons in left nav to the left

---

__tests__/feature/editing/selectFromLookup.test.js
src/components/editor/property/LookupWithMultipleAuthorities.jsx

Quick fix for #2564
New button under text input that the cataloger can click to add a literal:
For a URI:
Ran testing suite
n/a

Allow user to add URI or literal in Lookup Modal

---

cypress/integration/leftNav.spec.js
src/components/editor/property/PropertyLabelInfoTooltip.jsx

Fixes problem when user clicks on a tooltip and the page jumps to the top of the window.
Testing suite
n/a

Adds nonexistent relative href to prevent jumping to top of screen

---

__tests__/feature/searchAndOpenTemplate.test.js
__tests__/feature/searchAndViewResource.test.js
cypress/integration/end2end.spec.js
cypress/integration/leftNav.spec.js
src/components/search/Search.jsx
src/components/templates/TemplateSearch.jsx

Fixes #2227
Also adds clear search button to both search screens which resets state and input elements.
See screencast to watch feature in action:
To prevent catalogers from having to re-type searches for resources and templates over and over again
CI and in browser locally
None

Remember resource and template search state

---

__tests__/feature/search.test.js
src/components/search/Search.jsx
src/styles/main.scss

Addresses part of #2182 (search spinner)
Timeouts are in #2583
- adds search spinner when searches are executing (sinopia or QA)
- clears any current search results as soon as a new search is started (and shows the spinner when running the new search of course)
This is how the loading spinner looks: (Note: the "results loading" text is in a span that only shows for screen readers.)
- Localhost browser
None

add search spinner while waiting for search to run

---

__tests__/feature/searchAndViewResource.test.js
src/components/ViewResourceModal.jsx

Fixes #2580
This prevents a scenario where the resource edit page continues hiding the property panel because the state was not updated.
CI and browser.
None

Reset read-only state when dismissing ViewResourceModal

---

__tests__/actionCreators/lookups.test.js
src/actionCreators/lookups.js

closes #2593
Remove duplicates from LC authorities.
Unit, locally.
NA

Handles non-unique LC authority entries.

---

__tests__/sinopiaSearch.test.js
src/sinopiaSearch.js
static/authorityConfig.json

refs #2360
Allow a user to lookup existing resource templates when creating a template.
Unit, locally
NA

Support lookup of existing resources when creating a template.

---

src/components/editor/diacritics/VocabChoice.jsx

Fixes #2604 
It appears when the new diacritics panel is shown, the first item in the list if selected but not yet shown.  The current events to switch languages are "change" or "blur", neither of which are called if you click on Latin.  Add a "click" event ensures it gets called each time the user selects a new language (even if its the first on the list).
Local browser

add click event to ensure diacritics language is shown

---

__tests__/__action_fixtures__/loadResourceNestedResource-ADD_SUBJECT.json
__tests__/__action_fixtures__/newResourceFromDataset-ADD_SUBJECT.json
__tests__/__resource_fixtures__/test2.json
__tests__/actionCreators/resources.test.js
__tests__/feature/loadResource.test.js
__tests__/feature/previewRdf.test.js
__tests__/testUtilities/fixtureLoaderHelper.js
src/GraphBuilder.js
src/actionCreators/resourceHelpers.js

To fix a bug whereby when loading a resource that has a property that has multiple nested resource templates, only the resource templates with data were being displayed.
Unit
NA

Display nested resources from dataset and template

---

__tests__/reducers/lookups.test.js
src/reducers/lookups.js

refs #2616
To make it easier to find items in an Input List.
Unit, locally.
NA

Sorts Input Lists.

---

src/components/editor/ResourcesNav.jsx
src/styles/resourceTabs.scss

Fixes #2608 
1. Force the tabs to always be the same width (so they stack up nicely when in rows).  Width is set to 350px. This seems like a reasonable number to allow for three to four tabs across the page in a normal sized browser window, but I had to actually shrink the number of characters in the tab down to 38 (from 40) before you get the truncation to prevent overflow of text when tab widths are no bigger than 350px.
2. Add some spacing between them (so they aren't stuck together). 
3. Make better use of the tab width by removing the padding that comes from bootstrap.
4. Move the 'x' button over to the far right.
None

add spacing between resource nav tabs

---

src/components/editor/Tabs.jsx

closes #2575
It was a mess.
Locally.
NA

Aligns tabs for InputLookup.

---

src/components/editor/actions/MarcButton.jsx

closes #2624
The MARC preview was dropping right, which made it difficult to use.
Locally
NA

Set maxwidth for MARC preview.

---

__tests__/feature/editing/editingLiteral.test.js
src/components/editor/diacritics/DiacriticsSelection.jsx

Fixes #2103 
~~Also added the ability to hit the escape key and have it close the panel too (which follows other UI patterns).~~
Added a new test, but it still passes even without my change, so I don't think the test is working correctly.

prevent backspace for sending back button to browser when editing with diacritics

---

__tests__/actionCreators/resources.test.js
src/actionCreators/resourceHelpers.js

closes #2634
To avoid user confusion when there are extra labels.
Unit, locally.
NA

Swallow extra label triples.

---

__tests__/feature/newResourceTemplate.test.js
src/components/templates/NewResourceTemplateButton.jsx

Fixes #2610. Removed "+" in label to be consistent with other buttons in the editor.
Unit and Integration tests
n/a

New Templates link is now a blue buttton

---

__tests__/feature/editing/copyTemplateResource.test.js
__tests__/feature/editing/openAndCloseResource.test.js
src/components/editor/leftNav/ActivePanelPropertyNav.jsx
src/components/editor/leftNav/PanelResourceNav.jsx
src/components/editor/property/PanelProperty.jsx
src/components/editor/property/PanelResource.jsx
src/styles/main.scss
src/styles/variables.scss

Fixes #2599 
Adds expectations in existing feature tests:
```
editing/copyTemplateResource.test.js
editing/openAndCloseResource.test.js
```
Adds a 'template' class name conditionally depending on resource subjectTemplateKey

Conditionally change css to render different template and nav button colors

---

__tests__/__template_fixtures__/DiscogsLookup.json
src/components/editor/property/RenderLookupContext.jsx

closes #2662
Not all Discogs authorities render correctly.
Locally.
NA

Render Discog context for all discog authorities.

---

src/components/editor/diacritics/DiacriticsSelection.jsx
src/components/editor/property/InputLiteral.jsx
src/components/editor/property/InputLookup.jsx
src/components/editor/property/Lookup.jsx
src/hooks/useDiacritics.js

closes #2652
To allow catalogers to enter diacritics into InputLookup.
Not adequately.
NA

Adds diacritics selector to InputLookup.

---

src/components/editor/property/LookupTab.jsx
src/components/editor/property/LookupTabs.jsx

closes #2653
So that the user knows which tabs have results.
I will be adding tests for InputLookup in a separate PR.
NA

Adds result counts for lookup tabs.

---

src/components/editor/ResourcesNav.jsx

closes #2665
Fix resource nav so does not close when click on empty space.
Locally.
NA.

Fixes resource nav close.

---

src/components/editor/property/InputLookup.jsx

To make InputLookup search consistent with main search (which recently changed).
Locally.
NA

Makes InputLookup search button consistent with main search.

---

__tests__/actionCreators/resources.test.js
src/actionCreators/resourceHelpers.js

refs #2673
To allow a user to correct a resource when the resource template has changed.
Unit.
NA

Do not throw on more than one quad for ordered property.

---

src/components/editor/property/InputLookup.jsx
src/components/search/Search.jsx
src/components/templates/NewResourceTemplateButton.jsx
src/components/templates/TemplateSearch.jsx
src/styles/main.scss

- Fixes display of lookup values for a non-nested resource lookup, and to be adaptive to browser width.
- Fixes display of resource template search to be adaptive to browser width.
N/A only CSS changes were made
Before:
After:
Before:
After:

Makes lookup search input and values look better

---

.circleci/config.yml

```
On November 1st, Docker Hub will begin limiting anonymous image pulls. We want to make sure you know how you might be impacted and what you can do to avoid interruptions to your workflow.
Adding Docker authentication to your pipeline config is the easiest way to avoid any service disruptions. If you use the Docker executor or pull Docker images when using the machine executor on CircleCI, we encourage you to authenticate. Because the anonymous API rate limits are based on IP addresses, they will impact CircleCI cloud customers. Authenticated users get higher per-user rate limits, regardless of IP.
We are currently working on a partnership with Docker to minimize the impact of this change for our users and will share more details as we get them.
For more information or to leave a …
```

Add docker login to avoid anonymous image pulls.

---

__tests__/feature/loadResource.test.js
__tests__/feature/search.test.js
__tests__/feature/searchAndViewResource.test.js
src/components/editor/property/InputList.jsx
src/components/editor/property/InputLiteral.jsx
src/components/editor/property/NestedProperty.jsx
src/components/editor/property/NestedPropertyHeader.jsx
src/components/editor/property/PanelProperty.jsx
src/components/editor/property/PropertyComponent.jsx
src/components/editor/property/PropertyLabel.jsx

to make usage of the `PropertyLabel` component more accessible, per #2494
_note_, per #2683, this does not always make the `<label>` association work, despite the right pieces seeming to be in place.
manual testing in browser, unit tests
n/a

turn PropertyLabel into an HTML <label>

---

src/components/editor/actions/MarcButton.jsx

closes #2688
So that the user is notified when there is a MARC conversion error.
Locally
NA

Fixes handling of MARC conversion errors.

---

src/actionCreators/search.js

Fixes error in all environments that was causing search in the search tab to fail. 
Test suite.
n/a

Removed list wrapper for config object, causing search to fail

---

.npmignore

Local `.env` variables were being copied into a publicly available package when published to the npm registry.
Testing suite
Yes

npmignore updates

---

__tests__/feature/readNews.test.js
package-lock.json
package.json

Version bump to sync with `sinopa_editor` npm package. Fixed test failure that used restrictive regex.
Testing suite
n/a

Version bump to 3.5.10

---

__tests__/GraphBuilder.test.js
src/GraphBuilder.js

closes #2743
To correctly handle ordered properties that have empty subject values.
Locally
NA

Correctly serialize ordered properties that have empty subject values.

---

package-lock.json
package.json

to deploy weekly dependency updates (https://github.com/LD4P/sinopia_editor/issues/2767)
(jump from 3.5.13 is because 3.5.14 was tagged, but it seems package.json and package-lock.json weren't updated)
n/a, version bump only
`package.json` (and `package-lock.json`)

bump version to 3.5.15

---

README.md
dep_updates.md

I'm tired of chasing through multiple documents that are only 30% relevant to weekly dependency updates
It's a start.  I will create the approp links in first responder sheet.

create instructions for weekly dependency updates

---

src/components/editor/property/InputLiteral.jsx
src/components/editor/property/InputLookup.jsx
src/hooks/useDiacritics.js

closes #2361
Fix a regression introduced when moving diacritics into a hook.
Locally, dev environment by PO
NA

Fix entering value onBlur. 

---

src/components/editor/actions/CloseButton.jsx
src/components/editor/actions/CloseResourceModal.jsx

closes #2183
The close modal was getting confused about which resource to close.
Local, PO on dev.
NA

Fixes tab closing.

---

README.md

* link to dep update checklist was incorrect and 404ed
* there was still a section referring to the old checklist issue
see also https://github.com/LD4P/sinopia_editor/pull/2772/files and https://github.com/LD4P/sinopia_editor/pull/2777/files
proofread it, previewed the updated README clicked the link
README.md

freshen release instructions

---

README.md
__tests__/GraphBuilder.test.js
__tests__/TemplatesBuilder.test.js
__tests__/__action_fixtures__/expandProperty-ADD_VALUE.json
__tests__/__action_fixtures__/loadResource-ADD_SUBJECT.json
__tests__/__action_fixtures__/loadResourceNestedResource-ADD_SUBJECT.json
__tests__/__action_fixtures__/newResource-ADD_SUBJECT.json
__tests__/__action_fixtures__/newResourceFromDataset-ADD_SUBJECT.json
__tests__/__template_fixtures__/uber_template1.json
__tests__/__template_fixtures__/uber_template5.json
__tests__/actionCreators/resources.test.js
__tests__/actionCreators/templateValidationHelpers.test.js
__tests__/testUtilities/fixtureLoaderHelper.js
src/GraphBuilder.js
src/TemplatesBuilder.js
src/actionCreators/resourceHelpers.js
src/actionCreators/templateValidationHelpers.js
src/components/vocabulary/Vocab.js
static/authorityConfig.json
static/resourceAttribute.json

refs #2787
To produce/load RDF that avoids blank nodes.
Unit, dev
README

Adds support for suppressing blank node when a nested resource.

---

package-lock.json
package.json

version and deploy for weekly dependency updates
unit
version in `package.json` and `package-lock.json`

patch-level version bump for weekly dependency updates

---

src/Config.js

Add the `other` group to Sinopia intended for people experimenting with Sinopia who aren't associated with any of existing groups.
FIXES #2856
Unit tests
Yes, `src/Config.js`

Adds other group

---

package-lock.json
package.json

note: skipping from 3.6.0 to 3.6.2 because i mistakenly tagged a 3.6.1 release without doing some previous steps

version bump for dependency updates

---

release_process.md

refs https://github.com/LD4P/rdf2marc/issues/61
So that infra devs also deploy rdf2marc.

Added release instructions for rdf2marc.

---

__tests__/reducers/resources.test.js
src/reducers/resources.js

Fixes #2784 - save button needs to be enabled if the user changes the ordering of properties
In browser (localhost) and updated unit test

re-enable save button on property re-order

---

__tests__/components/search/GroupFilter.test.js
__tests__/components/search/SinopiaSearchResults.test.js
__tests__/feature/search.test.js
src/components/search/GroupFilter.jsx

Fixes #2870 - rename a button in the search tab
Updated test

rename filter by institution button to filter by group

---

__tests__/components/search/SinopiaSearchResults.test.js
src/components/dashboard/ResourceList.jsx
src/components/search/SinopiaSearchResults.jsx

Fixes #2995 -- rename search table header from "Institution" to "Group" to follow on from work done in #2870.  Also, renamed a similar table header on the Dashboard.
Updated tests

rename search and dashboard headers from institution to group

---

src/components/editor/actions/MarcButton.jsx

closes #2998
So the button works.
Local, development

Update MARC button to BS 5.

---

src/components/templates/SinopiaResourceTemplates.jsx

Fixes #3005 - update to match new bootstrap 5 styles.
See https://getbootstrap.com/docs/5.0/components/collapse/

update attributes for bootstrap 5

---

README.md
docker-compose.yml

refs https://github.com/LD4P/sinopia_api/issues/173
Due to changes in Sinopia API, now needs AWS keys available.
README, docker-compose.yml

Tweaks necessary for changes in Sinopia API.

---

src/components/templates/ResourceTemplateRow.jsx
src/components/templates/ResourceTemplateSearchResult.jsx

Fixes #3029 - add a column showing the group to resource lists (dashboard and recent)
Localhost

add group column to recent/current resource templates

---

README.md

We have a new linter, update the README to match.  Also, a small note about another way of running a single test.

updates to readme about linters and testing

---

src/components/ViewResourceModal.jsx
src/components/editor/actions/MarcButton.jsx

Fixes #3015 - show MARC button on the preview modal
Note: this uses the `<MarcButton>` component, which means the MARC button will only be shown for resources with templates of type `http://id.loc.gov/ontologies/bibframe/Instance`.  
Localhost browser (at least verifying the button is shown).  Unclear to verify button operation works as expected.  Should we add another test?

show marc button on preview modal

---

__tests__/components/home/UserNotifications.test.js
src/components/home/NewsPanel.jsx
src/components/home/UserNotifications.jsx
src/selectors/authenticate.js

Fixes #3003 - show a warning to a user on the home page when they are not in any groups
- Existing unit tests, and added a test for the new component
- Localhost browser (though had to temporarily fake it in the code to see the warning since I'm not sure how to remove myself from all groups or log in with a user that has no groups)
**When a logged in user is in at least one group:** (behavior unchanged)
**When a logged in user is NOT in at least one group:** (new alert)

show warning to a logged in user with no groups

---

__tests__/reducers/languages.test.js
src/reducers/languages.js
src/reducers/resources.js

Fixes #3037 - enable the save button when a language is changed.  Similar fix to what happened in #2991

set property as changed when updating language to enable save button

---

src/components/editor/GroupChoiceModal.jsx

closes #3047
Now it is just like every other group.

Removes special handling of ld4p group.

---

README.md
__tests__/TemplatesBuilder.test.js
__tests__/__action_fixtures__/addSiblingValueSubject-ADD_VALUE.json
__tests__/__action_fixtures__/expandProperty-ADD_PROPERTY.json
__tests__/__action_fixtures__/expandProperty-ADD_VALUE.json
__tests__/__action_fixtures__/loadResource-ADD_SUBJECT.json
__tests__/__action_fixtures__/loadResourceNestedResource-ADD_SUBJECT.json
__tests__/__action_fixtures__/newResource-ADD_SUBJECT.json
__tests__/__action_fixtures__/newResourceCopy-ADD_SUBJECT.json
__tests__/__action_fixtures__/newResourceFromDataset-ADD_SUBJECT.json
__tests__/reducers/history.test.js
__tests__/testUtilities/stateUtils.js
src/TemplatesBuilder.js
src/actionCreators/templates.js
src/reducers/history.js

closes #3038
The permissions on the dashboard should be consistent with rest of app.
Unit, local
README

Fix edit permissions on Dashboard.

---

__tests__/feature/searchAndViewResource.test.js
src/components/editor/property/PanelProperty.jsx

closes #3054
Empty headers aren't very helpful in a preview.
Unit

Omit empty properties in preview.

---

__tests__/__action_fixtures__/loadResource-ADD_SUBJECT.json
__tests__/__action_fixtures__/loadResourceNestedResource-ADD_SUBJECT.json
__tests__/__action_fixtures__/newResource-ADD_SUBJECT.json
__tests__/__action_fixtures__/newResourceFromDataset-ADD_SUBJECT.json
__tests__/__template_fixtures__/uber_template1.json
__tests__/reducers/resources.test.js
src/reducers/resources.js

Fixes #3025 - allowing an rdfs label for the root resource subject to be stored in state.
Part of this sprint stretch goal:  "enable use of rdfs:label for labelling resources in search results and tab headers and Editor heading"
test code and running locally and confirming with redux

root resource subject state can have rdfs label assigned

---

src/components/editor/actions/MarcButton.jsx

The `<bdi>` tag will do its best to autodetect the correct direction for text display.  It empirically seems to work fine for this case.   Thanks to @justinlittman  for the link to https://www.w3.org/International/articles/inline-bidi-markup/ in the issue.  See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/bdi for more about bdi tag.
Fixes #3057
I tested it locally by using the example resource from the ticket in my browser and then editing the html displayed via the inspector webtools.  JLitt did a similar test by adding spurious display of marc from the record in the Sinopia editor and adding the `<bdi>` tag inside the `<pre>` tag for displaying the marc.

when displaying Marc, use bdi tag for correct right-to-left text

---

src/hooks/useNavigableComponent.js

Allow previewing empty resources.

---

__tests__/components/ModalWrapper.test.js
src/components/Alert.jsx
src/components/ResourceTemplateChoiceModal.jsx
src/components/ViewResourceModal.jsx
src/components/editor/EditorActions.jsx
src/components/editor/RDFModal.jsx
src/components/editor/ResourcesNav.jsx
src/components/editor/actions/CloseButton.jsx
src/components/editor/actions/CloseResourceModal.jsx
src/components/menu/CanvasMenu.jsx
src/styles/main.scss

This is the prescribed way https://getbootstrap.com/docs/5.1/components/close-button/
It used to look like this:
Now it looks like:

Update the close button for Bootstrap 5

---

src/components/home/DescPanel.jsx

the JSX compiler is removing this important space.

Add missing space on homepage.

---

src/styles/lookupContext.scss

The lookup search results uses nav-pills not nav-tabs
See a8ecb820822a3f2a206fa157a433d9876bb5d738

Remove unused styles

---

__tests__/feature/dashboard.test.js
__tests__/feature/invalidTemplate.test.js
__tests__/feature/loadNewResource.test.js
__tests__/feature/previewRdf.test.js
__tests__/feature/searchAndOpenTemplate.test.js
__tests__/feature/searchAndViewResource.test.js
__tests__/feature/userPermissions.test.js
cypress/integration/end2end.spec.js
cypress/integration/leftNav.spec.js
package-lock.json
package.json
src/components/templates/ResourceTemplateRow.jsx
src/components/templates/ResourceTemplateSearchResult.jsx

Fixes #2853:
- unlink resource template name as a way of creating a resource
- add the react-bootstrap icon module since we are now using it
- label column on dashboard with "Actions"
- add a new icon for create a resource to the Actions column
- change edit template icon to better match style shown in mockup
- add/adjust hover text for all icons
- fix the tests so they can find the new linking style of creating resources
Example for how it looks now:
Existing tests

use icon for creating resource instead of linking resource template name

---

__tests__/sinopiaSearch.test.js
src/sinopiaSearch.js

This reverts commit 4bf7151f2dff5e162345f584ef146a8342be3023.
It was not the correct change to make: https://github.com/LD4P/sinopia_editor/pull/3108#issuecomment-939082091

Revert "Add the group field to the search query"

---

__tests__/actionCreators/resources.test.js
src/actionCreators/resources.js

connects to #2457 
Along with LD4P/sinopia_api/pull/199, gives clearer error message for Sinopia Editor users.

actionCreators/resources: saveNewResource: tweak error message prefix

---

src/components/Header.jsx

Fixes #3145 
The Sinopia logo now links to the homepage.  The gifs below shows that when you hover over it, it looks like a link, too:
Plain:
Hovering Over:
Where it Goes when you click on it:
locally

editor header: Sinopia logo links to homepage

---

src/components/editor/leftNav/ActivePanelPropertyNav.jsx
src/components/editor/leftNav/PanelPropertyNav.jsx
src/components/editor/leftNav/PropertySubNav.jsx
src/hooks/useLeftNav.js
src/hooks/useNavigableComponent.js

More attempts to fix #3109 as a follow on to work done in #3136 
1. Prevent scrolling when a field is clicked behind a modal
2. Prevent fields from being selected behind a modal
~~Still unclear: clicking a header in a resource template behind the modal still changes the left nav (even though that doesn't really impact you or cause problems, it can be confusing).  The template property headers are rendered here:~~
~~https://github.com/LD4P/sinopia_editor/blob/main/src/components/editor/property/PanelProperty.jsx#L63-L68~~
~~https://github.com/LD4P/sinopia_editor/blob/main/src/components/editor/property/PropertyLabel.jsx~~
~~but I  don't see where we are responding to clicks to change the left nav in response (to disable there too).~~
UPDATE: Now unable to reproduce this behavior :/ …

disable scrolling and clicks behind modals

---

src/components/editor/property/PanelProperty.jsx
src/styles/main.scss

closes #3120
White on white is not adequate contrast.

Make Add button visible.

---

src/components/editor/leftNav/SubjectSubNav.jsx

Fixes #3166 -- found one more location we can disable when modals are open (similar work to #3159)
It has hard for me consistently reproduce on my localhost browser, so worth a check on dev too to see if this additional location is the one causing the problems.

disable nav when modal is open

---

src/components/editor/EditorActions.jsx
src/components/editor/ResourceComponent.jsx
src/components/editor/ResourceURIMessage.jsx
src/components/editor/actions/CloseButton.jsx
src/components/editor/actions/MarcButton.jsx
src/components/editor/actions/TransferButton.jsx
src/components/editor/actions/TransferButtons.jsx
src/styles/main.scss

Closes #3125 
There is a comment at the end of #3125 in that this PR converts the "Request Marc" and "Export to Symphony" buttons to have no borders, but it does NOT turn them into links.  The main difference to the user is the hover behavior.  If that is unacceptable, I would request that a new issue be created for that.
I can split things up if it's easier for review.
- Primary button: Save - no change
**When hovering over "link"**
**When error producing MARC (or Export):**
locally

Update visual design of various controls

---

__tests__/actionCreators/resources.test.js
src/actionCreators/resources.js
src/components/editor/GroupChoiceModal.jsx
src/components/editor/actions/SaveAndPublishButton.jsx

closes #3127
Allow user to fix a recoverable error.

Switches resource save to warn instead of error.

---

__tests__/components/editor/preview/ResourcePreviewHeader.test.js
src/components/editor/preview/ResourcePreviewHeader.jsx

Fixes #3194 - show full group names, not IDs, in preview header
Localhost, and updated unit test

show full group names in preview header

---

__tests__/sinopiaSearch.test.js
__tests__/utilities/Lookup.test.js
src/sinopiaSearch.js
src/utilities/Lookup.js

closes #3222
Allow users to create templates without error.
Unit, local

Fix handling of template lookup results.

---

src/reducers/languages.js

Fixes #824 - alpha sort languages in type ahead box

alpha sort list of languages in type ahead box

---

__tests__/actionCreators/resources.test.js
src/actionCreators/resourceHelpers.js

Fixes #3199
This commit makes a small tweak to the spot in the codebase where groups are merged into resources, short-circuiting that behavior when the resource is new. The intent is to prevent copied resources from inheriting groups and edit groups from the resources from which they were copied. These should not be set, and the user should select the group and edit groups after copying the resource.
CI
None.

Merge groups into resource only when not a new resource

---

__tests__/feature/editing/copyTemplateResource.test.js
__tests__/feature/newResourceTemplate.test.js
__tests__/testUtilities/fixtureLoaderHelper.js
__tests__/testUtilities/stateUtils.js
src/sinopiaApi.js
static/templates/rt_literal_property_attrs_doc.json
static/templates/rt_lookup_property_attrs_doc.json
static/templates/rt_property_template_doc.json
static/templates/rt_resource_property_attrs_doc.json
static/templates/rt_resource_template_doc.json
static/templates/rt_uri_doc.json
static/templates/rt_uri_property_attrs_doc.json

part of #3266
Easier maintenance and deploy of base templates.

Loads base templates instead of retrieving from API.

---

src/components/vocabulary/Vocab.js
static/authorityConfig.json
static/literalDataType.json
static/templates/rt_literal_property_attrs_doc.json

closes #2907
Allow template author to specify a regex for a literal field.

add configurations for validation of literals

---

src/components/search/HeaderSearch.jsx
src/hooks/useSearch.js
src/styles/header.scss

Search only items with a particular bibframe class

---

src/components/editor/leftNav/LeftNav.jsx
src/components/editor/leftNav/PanelResourceNav.jsx
src/components/editor/leftNav/Versions.jsx

Fixes #3272
This makes the left nav exist when on the 'Versions' tab

Deduplicate layout rendering

---

README.md

related to #3266
To document the term "base template" and what it means, as well as where to find them and what updating them entails.

README: add section on base templates and Vocab.js

---

src/components/templates/NewResourceTemplateButton.jsx

Fixes #3299 - add loading spinner to New Template button
Localhost

show loading spinner when new template button is pressed

---

README.md
__tests__/TemplatesBuilder.test.js
src/TemplatesBuilder.js

Fixes #3287
When a property template has a literal which has a validationDataType specified, then a resource using that property template should not display the language button for the literal with the validationDataType.
Look!  no language button!
from this property template:
with a new unit test, and locally (see pix above)

literal with validationDataType does not display language button

---

static/templates/rt_literal_property_attrs_doc.json

Fixes #3332 
note laguage "button"
locally, unit tests.

suppress language button for literal hasValidationRegex and hasValidtionDataType

---

src/components/editor/inputs/InputURIValue.jsx

Keep the link button on the same line as the URL field

---

__tests__/reducers/resourceValidationHelpers.test.js
__tests__/reducers/resources.test.js
src/reducers/resourceHelpers.js

closes #3259
In a particular corner case, literals were being mis-validated.

Validate literals as literals, not URIs.

---

package-lock.json
package.json
server.js

request is deprecated
Locally, development

Replace request for proxying

---

__tests__/components/editor/preview/ResourcePreviewHeader.test.js
__tests__/components/editor/property/PropertyLabelInfo.test.js
__tests__/components/editor/property/PropertyLabelInfoTooltip.test.js

Refactor some tests to use the testUtils (as done in #3349)

refactor tests to use renderCompontent and createStore

---

static/authorityConfig.json

Updated lookup labels to match between the cache and direct access. Deleted concept, intangible, and alt_lc. Note: intangibles are reflected in the separate topic and genreform subauths now.

Aligned FAST direct and cache lookups

---

__tests__/GraphBuilder.test.js
__tests__/__action_fixtures__/loadResource-ADD_SUBJECT-multiple-property-uris.js
__tests__/__action_fixtures__/loadResource-ADD_SUBJECT.js
__tests__/__action_fixtures__/newResource-ADD_SUBJECT.js
__tests__/__action_fixtures__/newResourceCopy-ADD_SUBJECT.js
__tests__/__action_fixtures__/newResourceFromDataset-ADD_SUBJECT-bad-ordered.js
__tests__/__action_fixtures__/newResourceFromDataset-ADD_SUBJECT-nested.js
__tests__/__action_fixtures__/newResourceFromDataset-ADD_SUBJECT-ordered.js
__tests__/__action_fixtures__/newResourceFromDataset-ADD_SUBJECT.js
__tests__/testUtilities/resourceBuilderUtils.js
src/GraphBuilder.js

Closes #2891
When there is a validationDataType, the URI is now included in the RDF as the @type of the literal property's value.
we indicate the datatype in the graph:
unit test and locally on my laptop

GraphBuilder: add datatype declaration to literal value when present

---

src/components/editor/inputs/LookupTab.jsx

Fixes #3341 - show an error on QA lookups if there are network issues instead of showing "No results"
Localhost

show network error on lookup instead of no results

---

README.md
__tests__/__state_fixtures__/full_resource.json
__tests__/actionCreators/relationships.test.js
__tests__/reducers/resources.test.js
__tests__/sinopiaApi.test.js
__tests__/testUtilities/fixtureLoaderHelper.js
__tests__/testUtilities/stateResourceBuilderUtils.js
src/reducers/resourceHelpers.js
src/reducers/resources.js
src/sinopiaApi.js

Adds localAdminMetadataFor as a bfAdminMetadataRefs property.

---

__tests__/utilities/QuestioningAuthority.test.js
src/components/editor/inputs/LookupTab.jsx
src/utilities/QuestioningAuthority.js

closes #3377
Allow publisher cities authority to function properly.
Unit, local

Handles authorities without headers.

---

src/components/editor/property/LiteralTypeLabel.jsx

closes #3384
Consistency with other literal validation.

Adds label for EDTF literal.

---

src/components/search/HeaderSearch.jsx

Changed label in search dropdown.

---

__tests__/feature/metrics/viewResourceMetrics.test.js
__tests__/feature/metrics/viewUserMetrics.test.js
src/components/metrics/ResourceMetrics.jsx
src/components/metrics/TemplateMetrics.jsx
src/components/metrics/UserCountMetric.jsx
src/components/metrics/UserMetrics.jsx
src/components/metrics/UserResourceCountMetric.jsx
src/components/metrics/UserTemplateCountMetric.jsx
src/sinopiaMetrics.js

Fixes #3398 - add user engagement metrics to user metrics UI page
I also tried putting the cards into sets of either two or three columns (in a second commit), instead of all stacked one on top of the other, since I think it looks better.  See screenshots.
Note: i created a component for the existing user count metric to match the style of the other metrics pages (where each card was its own component)
Localhost

add user engagement metrics to editor ui

---

src/components/editor/property/PanelProperty.jsx
src/styles/main.scss

Layout tweaks.

---

src/components/search/SearchResultRow.jsx

Make the relationship results more visually distinct.

Add light styling to relationship results.

---

__tests__/feature/metrics/viewTemplateMetrics.test.js
src/components/metrics/TemplateFilter.jsx
src/components/metrics/TemplateUsageCountMetric.jsx
src/hooks/useMetric.js

The template usage metric should start out as blank (0) until you search for a specific template.
Also, show the template ID of the currently reported on template to make it clear which one was selected (useful if you clear out the search, as it makes it clear why the results haven't changed yet):
Localhost, and updated test

allow the app to set no default for template usage metric

---

__tests__/feature/editing/transfer.test.js
src/Config.js

Adds `cornell` and `penn` groups to the `transferConfig` function to allow exporting to FOLIO via Airflow.
Unit tests
`src/Config.js`

Config Cornell and Penn for exporting to ILS

---

src/components/search/RelationshipResults.jsx
src/styles/bootstrap-override.scss

Fix relationship table background.

---

static/authorityConfig.json

This authority is broken and has been replaced by a QA authority.
authorityConfig.json

Removed Cultural Heritage Organizations authority.

---

.circleci/config.yml

From [Circle-CI](https://support.circleci.com/hc/en-us/articles/4421154407195-Deprecating-Ubuntu-14-04-and-16-04-images-EOL-5-31-22), the Orbs we are using are being depreciated.
Unit and integration tests
`.circleci/config.yml`

Updates Orbs used in project

---

release_process.md

We are no longer publishing to NPM.

Remove npm publish step

---

static/templates/rt_resource_template_doc.json

closes #3551
Per @NancyL.
Local

No longer suppress labels for optional classes.

---

static/templates/rt_property_template_doc.json

closes #3552
Per @NancyL 
Local

No longer suppress labels for chooseable properties.

---

src/components/vocabulary/Vocab.js

refs https://github.com/LD4P/rdf2marc/issues/57
Per @NancyL

Adds nonfiling to vocab.

---

__tests__/feature/searchAndPreviewResource.test.js
src/components/editor/preview/RDFDisplay.jsx

Correctly handle RTL for previews.

---

.circleci/config.yml

This context was missing, which was causing CI failure. This was because I removed redundant env variable configuration in Circle.

Add missing ld4p context

---

static/authorityConfig.json

Fixes #3725
Fixes #3726
Fixes #3732
Unit tests
`authorityConfig.json`

New Serials publication type, Note Types, and Relationship authorities

---

static/authorityConfig.json

Adding LOC Subjects Direct as first step toward removing cache lookups.

Add LOC Subjects Direct Lookup

---

static/authorityConfig.json

Adding direct lookup for DBPedia as a first step toward removing cached version.

Adding DBPedia Direct lookup

---

src/components/Footer.jsx

Adds accessibility note and link to footer

---

static/authorityConfig.json

If this works in Sinopia, I'll add the remaining RDA vocabs in another pull request.

Add RDA Aspect Ratio Designation local lookup

---

src/components/editor/ResourceComponent.jsx
src/components/editor/actions/TopButton.jsx

closes #3763
Note that this was added to the sticky header instead of the bottom of the page.
Editor joy.

Add scroll to top button to editor.

---

static/authorityConfig.json

Direct lookups are safe to use now.

Removing "Test (DO NOT USE YET)"

---

src/Config.js

The Sinopia editor can export to an institutional specific ILS when configuration is updated. The main addition is the changes to **src/Config.js**
ran npx jest command
**src/Config.js**

Sinopia2alma src/Config.js edits

---

src/Config.js

adding PUC Pontificia Universidad Católica de Chile to config
n/a
n/a

Update Config.js - adding PUC Pontificia Universidad Católica de Chile

---

src/Config.js

User group members reporting they cannot export to catalog; fixes group configuration files cases need to match AWS case.
n/a
n/a

Update Config.js - updated PUC group to reflect AWS case
