__tests__/reducers/errors.test.js
src/reducers/errors.js

Tests for Reducer/Errors

---

.github/pull_request_template.md

To be consistent with other Infrastructure projects

Adds PR Template

---

src/components/editor/property/NestedResourceActionButtons.jsx

Fixes #2304 
Testing suite
n/a

NestedResourceActionButton onClick function

---

__tests__/feature/previewRdf.test.js
src/components/editor/RDFDisplay.jsx

Feature test for `Preview RDF` modal, fixes #2262

Feature test for Preview RDF

---

__tests__/reducers/modals.test.js

Fixes #2241 
Ran test suite
n/a

Refactor and new tests for Reducers/modals

---

README.md
src/components/editor/diacritics/DiacriticsSelection.jsx

Update the README to reflect reality / current practices.
NA
NA

README edit.

---

README.md

Updates README to include the correct directions for running the development server.
n/a
README

Corrects npm run call directions and port number.

---

README.md

Was confused about the dev server - hopefully this will help my future self or another new developer.
n/a

more clarifications for readme on dev server

---

README.md

Fixed Markfown format for Sinopia staging link in README 
n/a
README

Fixed markdown link

---

__tests__/reducers/exports.test.js

improve test coverage.
closes #2244
PR just adds a test
n/a

test reducers/exports

---

__tests__/selectors/languages.test.js

Adds a test for selectors/languages

---

src/components/home/NewsItem.jsx

For new tagged release `3.1.0`
Test suite and linter
Wiki

News items for version 3.1.0

---

__tests__/__template_fixtures__/ResourceTemplate.json
__tests__/feature/newResourceTemplate.test.js
__tests__/testUtilities/fixtureLoaderHelper.js
src/components/templates/NewResourceTemplateButton.jsx
src/components/templates/TemplateSearch.jsx

refs #2378
To make it clearer for a user how to create a new resource template.
Feature test.
NA

Adds new resource template button.

---

__tests__/__action_fixtures__/addSiblingValueSubject-ADD_VALUE.json
src/actionCreators/resources.js

Fix typo in addSiblingValueSubject

---

src/components/Header.jsx
src/components/home/Header.jsx

Remove Profile Editor link from headers

---

cypress/integration/end2end.spec.js
cypress/integration/leftNav.spec.js

Attempt to address Cypress test flappiness.
Circle.
NA

Adjust flappiness.

---

Dockerfile
Dockerfile.cypress
cypress/integration/end2end.spec.js
docker-compose.yml
package-lock.json
package.json

Various tweaks to make build more efficient and switch to using Firefox for integration testing.
Unit / integration tests.
NA

Build tweaks

---

package-lock.json
src/actionCreators/exports.js
src/actionCreators/lookups.js
src/actionCreators/resources.js
src/actionCreators/templates.js
src/components/editor/RDFDisplay.jsx
src/components/search/QASearchResults.jsx
src/sinopiaApi.js
src/utilities/QuestioningAuthority.js

Sometimes err.message is undefined, in which case use error.
I don't know why.
NA
NA

Use err when no err.message

---

__tests__/sinopiaApi.test.js

Fixes #2388 
Adds tests for `sinopiaApi` module in the editor
n/a

Sinopia API tests

---

__tests__/feature/newResourceTemplate.test.js
src/components/templates/NewResourceTemplateButton.jsx

Updates link text to New template

---

__tests__/feature/editing/addRemove.test.js
__tests__/feature/editing/editingLiteral.test.js
__tests__/feature/editing/editingUri.test.js
__tests__/feature/editing/expandContract.test.js
__tests__/feature/editing/openAndCloseResource.test.js
__tests__/feature/editing/propInfo.test.js
__tests__/feature/editing/saveAndCopyResource.test.js
__tests__/feature/invalidTemplate.test.js
__tests__/feature/loadNewResource.test.js
__tests__/feature/loadRDF.test.js
__tests__/feature/loadResource.test.js
__tests__/feature/newResourceTemplate.test.js
__tests__/feature/previewRdf.test.js
__tests__/feature/readNews.test.js
__tests__/feature/searchAndOpenTemplate.test.js
__tests__/feature/userAuthentication.test.js
src/components/editor/actions/CopyToNewButton.jsx
src/components/editor/property/InputValue.jsx
src/components/editor/property/LanguageButton.jsx
src/components/editor/property/NestedPropertyHeader.jsx
src/components/editor/property/NestedResourceActionButtons.jsx
src/components/editor/property/PanelProperty.jsx
src/components/search/Search.jsx
src/components/search/SearchResultRows.jsx
src/components/templates/ResourceTemplateRow.jsx

*ByRole selectors were bogging down the tests (taking ~1 sec per query rather than ms) causing timeouts.
Feature tests.
NA

Purged ByRole selectors to improve performance.

---

package-lock.json
package.json

Update jest-dom to latest.
Unit/feature.
NA

Update jest-dom to latest.

---

package-lock.json
package.json
src/components/home/NewsItem.jsx

Version `3.2.0` for Sprint 2.
Unit tests (build is failing, will need to rebase once https://github.com/LD4P/sinopia_editor/pull/2466 is merged.
Wiki

Version bump to 3.2.0

---

src/components/editor/actions/SaveAndPublishButton.jsx

Each function should only do one job.

Separate validate logic from save logic

---

src/components/editor/property/InputListLOC.jsx
src/components/editor/property/InputLiteral.jsx
src/components/editor/property/InputLookup.jsx
src/components/editor/property/InputURI.jsx
src/components/editor/property/NestedPropertyHeader.jsx
src/styles/main.scss

Add the Source Sans Pro font.  Update the link color.
Ref #2440

Typeography and error style changes

---

__tests__/feature/search.test.js

add feature test coverage for various basic search result display behaviors.
connects with #2276
PR only adds tests
n/a

Search feature test

---

src/actions/inputs.js
src/components/editor/diacritics/CharacterButton.jsx
src/components/editor/property/InputLiteral.jsx
src/components/editor/property/InputValue.jsx
src/reducers/index.js
src/reducers/inputs.js

Insert diacritics at the cursor's current position

---

package-lock.json
package.json

Version bump
Test suite
`package.json`

Version bump to 3.2.1

---

src/components/editor/property/InputLookupModal.jsx
src/styles/main.scss

Fixes #2478 
Fixed up per style guideline and now the delete button works.
CI
N/A

Fixes up lookupValue styling and enables the delete value button

---

__tests__/actionCreators/search.test.js
__tests__/components/search/GroupFilter.test.js
__tests__/components/search/QASearchResults.test.js
__tests__/components/search/Search.test.js
__tests__/components/search/SearchResultsPaging.test.js
__tests__/components/search/SinopiaSearchResults.test.js
__tests__/components/search/SinopiaSort.test.js
__tests__/components/search/TypeFilter.test.js
__tests__/reducers/search.test.js
__tests__/selectors/search.test.js
src/actionCreators/search.js
src/actions/search.js
src/components/search/GroupFilter.jsx
src/components/search/QASearchResults.jsx
src/components/search/Search.jsx
src/components/search/SearchResultsMessage.jsx
src/components/search/SearchResultsPaging.jsx
src/components/search/SinopiaSearchResults.jsx
src/components/search/SinopiaSort.jsx
src/components/search/TypeFilter.jsx
src/components/templates/ResourceTemplateSearchResult.jsx
src/components/templates/SinopiaResourceTemplates.jsx
src/components/templates/TemplateSearch.jsx
src/reducers/index.js
src/reducers/search.js
src/selectors/search.js
src/store.js
src/utilities/Search.js

refs #2485
Refactor reducers.
Unit/feature.
NA

Moves search out of selectorReducer.

---

__tests__/feature/editing/copyTemplateResource.test.js
__tests__/feature/editing/editTemplateResource.test.js
__tests__/testUtilities/stateUtils.js
src/components/templates/ResourceTemplateRow.jsx

Fixes #2384 
Adds a mocked template resource to stateUtils

Test edit copy resource

---

__tests__/components/editor/property/RenderLookupContext.test.js
src/components/editor/property/LookupWithMultipleAuthorities.jsx
src/components/editor/property/RenderLookupContext.jsx
src/components/editor/property/renderTypeaheadFunctions.js
src/styles/lookupContext.scss
src/styles/main.scss

Update Lookup context styles

---

__tests__/components/vocabulary/Vocab.test.js
src/components/App.jsx
src/components/Footer.jsx
src/components/vocabulary/Vocab.js

Fixes https://github.com/LD4P/sinopia/issues/277
Added unit tests for new component
n/a

Publish Sinopia vocab

---

src/components/editor/leftNav/PanelResourceNav.jsx
src/styles/main.scss
src/styles/resourceNav.scss

Set the background color for the active editor menu

---

package-lock.json
package.json
src/components/home/NewsItem.jsx

Version for Sprint 3 changes
Unit tests
Sinopia wiki updated

Version bump to 3.3.0 

---

.circleci/config.yml
__tests__/__action_fixtures__/newResource-ADD_SUBJECT.json
__tests__/actionCreators/resources.test.js
__tests__/components/App.test.js
__tests__/feature/editing/addRemove.test.js
__tests__/feature/editing/copyTemplateResource.test.js
__tests__/feature/editing/editingLiteral.test.js
__tests__/feature/editing/expandContract.test.js
__tests__/feature/editing/propInfo.test.js
__tests__/feature/editing/reordering.test.js
__tests__/feature/editing/saveAndCopyResource.test.js
__tests__/feature/loadNewResource.test.js
__tests__/feature/loadResource.test.js
__tests__/feature/newResourceTemplate.test.js
__tests__/feature/previewRdf.test.js
__tests__/feature/searchAndOpenTemplate.test.js
__tests__/feature/searchAndViewResource.test.js
cypress/integration/end2end.spec.js
cypress/integration/leftNav.spec.js
src/actionCreators/resourceHelpers.js
src/actionCreators/resources.js

closes #2541
To automatically expand property panels.
Unit/feature.
NA

Expand panel properties.

---

src/styles/bootstrap-override.scss
src/styles/bootstrap-variables.scss
src/styles/colors.scss
src/styles/main.scss
src/styles/variables.scss

The styles are becoming disorganized and there isn't a clear place for different functions (e.g. defining the palate, set bootstrap variables, override bootstrap styles, set local variables, components, etc.)

Organize stylesheets

---

src/components/editor/property/InputLookup.jsx
src/hooks/useNavigableComponent.js

When the globe icon is clicked go to the source uri

---

src/styles/main.scss
src/styles/variables.scss

Icons and buttons should be the same color as links

---

src/styles/main.scss

Ensure the add property button uses the color of blue used throughout

---

package-lock.json
package.json
src/components/home/NewsItem.jsx

Patch version for work blocking regression fix for new Lookup modals. Added one news item. 
Unit and Integration tests
n/a

Patch version for Regression Fix

---

__tests__/sinopiaSearch.test.js
src/sinopiaSearch.js

Return up to 20 institutions in the filter

---

.circleci/config.yml

Why? To speed up the build a little.
CI
CI configs

Run integration tests while running unit/feature tests in CI

---

package-lock.json
package.json

Critical Bug fixes with new Dashboard feature.
n/a
Yes, release notes updated.

Version 3.4.0

---

src/components/search/Search.jsx

Fix broken test.

---

src/components/App.jsx
src/components/editor/Editor.jsx
src/selectors/errors.js

closes #2591
Presumably warnings are bad.
Locally.
NA

Fixes cannot update while rendering warning.

---

src/components/editor/property/InputLiteral.jsx

closes #2584
Fix entry and navigation in InputLiteral.
Local
NA

Fix navigation within InputLiteral.

---

__tests__/__action_fixtures__/loadResource-ADD_SUBJECT.json
__tests__/actionCreators/history.test.js
__tests__/actionCreators/resources.test.js
__tests__/actionCreators/user.test.js
__tests__/feature/dashboard.test.js
__tests__/reducers/history.test.js
__tests__/selectors/resources.test.js
__tests__/sinopiaSearch.test.js
__tests__/testUtilities/fixtureLoaderHelper.js
cypress/integration/end2end.spec.js
src/actionCreators/history.js
src/actionCreators/resources.js
src/actionCreators/user.js
src/actions/history.js
src/components/dashboard/Dashboard.jsx
src/components/dashboard/ResourceList.jsx
src/components/load/LoadByRDFForm.jsx
src/components/search/QASearchResults.jsx
src/components/search/SinopiaSearchResults.jsx
src/components/templates/SinopiaResourceTemplates.jsx
src/hooks/useRdfResource.js
src/hooks/useResource.js
src/reducers/history.js
src/reducers/index.js
src/selectors/history.js
src/selectors/resources.js
src/sinopiaSearch.js
src/store.js
src/styles/main.scss

So that a user can quickly find resources that she has been editing.
Unit, feature, integration
NA

Add resource history to dashboard

---

src/styles/resourceNav.scss

Fixes #2602
Unit and integration tests
n/a

Adds font awesome css-code for checkmark

---

src/styles/resourceNav.scss

Fixes #2635 
Visually locally
n/a

Adds font-families to class

---

__tests__/feature/editing/editingLiteral.test.js
src/components/editor/property/InputLiteral.jsx

closes #2623
Fix the preview.
Locally
NA

Fixes disabled InputLiteral for preview.

---

src/components/search/Search.jsx
src/styles/main.scss

Fixes #2607 
Localhost browser and test suite passing
None

change search from icon to button

---

cypress/integration/helpAndResources.spec.js

Fixes helpAndResources test.

---

src/components/templates/NewResourceTemplateButton.jsx

Button Fixes

---

src/components/editor/actions/MarcButton.jsx

refs #2661
So that the MARC button correctly handles state when toggling between resources.
Note that this is only a partial fix; leaving the editor (e.g., to search) clears the state. Fixing this would require putting the data into redux state. However, since the MARC button is only a proof-of-concept this has not been implemented.
Locally.
NA

Allow MarcButton to persist between resources.

---

src/components/dashboard/SearchList.jsx

closes #2606
Per @astridu's request.
Local
NA

Cuts dashboard search list spacing.

---

src/actionCreators/resourceHelpers.js

Checks for null value in resourceHelpers

---

package-lock.json
package.json

Update to version 3.5.2.
NA
NA

Updated version to 3.5.2

---

package-lock.json
src/hooks/useResource.js

closes #2699
To fix returning to an resource that is already being edited.
Locally.
NA

Fixed returning to editing resource.

---

__tests__/TemplatesBuilder.test.js
__tests__/__action_fixtures__/loadResource-ADD_SUBJECT.json
__tests__/__action_fixtures__/loadResourceNestedResource-ADD_SUBJECT.json
__tests__/__action_fixtures__/newResource-ADD_SUBJECT.json
__tests__/__action_fixtures__/newResourceFromDataset-ADD_SUBJECT.json
src/TemplatesBuilder.js
src/components/editor/property/ResourceList.jsx

closes #2701
To fix Create New (regression).
Locally, unit
NA

Fixes Create New.

---

package-lock.json
package.json

Version bump
testing suite
n/a

3.5.4 Version

---

src/components/editor/property/ResourceList.jsx

Fixes #2716 
Testing suite
n/a

OnClick function now takes event

---

package-lock.json
package.json

to enable deployment of dependency updates.

bump to version 3.5.6

---

package-lock.json
package.json

Bump version to 3.5.7 (dep updates)

---

package-lock.json
package.json

Updated version to 3.5.8.

---

package-lock.json
package.json

Bump version to 3.5.9 and update dependencies

---

.circleci/config.yml
.github/ISSUE_TEMPLATE/tagged-release.md
README.md

Changes to use `main` as default branch
Test suite
README, config.yml

Switch default branch to main

---

package-lock.json
package.json

Updated to version 3.5.11
NA
NA

Updated to version 3.5.11

---

package-lock.json
package.json

Bump version to 3.5.12

---

package-lock.json
package.json

3.5.13 Version

---

__tests__/feature/editing/editingLookup.test.js
src/components/editor/property/ResourceList.jsx
src/sinopiaSearch.js

Fixes #2716 . Adjusted fixture handling in sinopiaSearch to better replicate searching with ElasticSearch.
Added new feature test to confirm change
n/a

Create New button for Sinopia Lookups

---

__tests__/components/vocabulary/Vocab.test.js
src/components/vocabulary/Vocab.js

Fixes #2717 and updates vocabulary based on feedback from @briesenberg07 
Updates test, test suite
n/a

Vocabulary updates

---

package-lock.json
package.json

Dependency updates and bug fixes.
n/a
n/a

Version 3.5.19

---

package-lock.json
package.json

To update package.json to version 3.5.20 for dep updates

version bump to 3.5.20 for dep updates

---

release_process.md

Added a some minor clarifications.

tweak text for sinopia_editor release process

---

package-lock.json
package.json

Dependency updates version bump

version bump for dependency updates

---

package-lock.json
package.json

bump version to release dependency updates
n/a
version in `package.json`

version 3.5.25

---

package-lock.json
package.json

Bump version to 3.5.26

---

package-lock.json
package.json

Dependency updates - update version

---

src/Config.js

Fixes #2824
Unit tests
src/Config.js

Adds Music Library Association Group

---

package-lock.json
package.json

update npm for dependency updates

bump version to 3.5.28

---

package-lock.json
package.json

Dependency updates.
Test suite

Version 3.5.30

---

package-lock.json
package.json

version 3.5.31

---

package-lock.json
package.json

Dependency update version bump

---

package-lock.json
package.json

Updated version to 3.5.35

---

package-lock.json
package.json

Dependencies update
Unit tests

Version 3.5.36

---

.circleci/config.yml
release_process.md

Change to environment specific image building and deploy.

---

package-lock.json
package.json

version bump (dependency updates, new container image deployment approach)
CI
n/a

bump version for dependency updates and new deployment behavior

---

package-lock.json
package.json

Remove eslint utils

---

package-lock.json
package.json

Remove babel core

---

package-lock.json
package.json

Remove hookrouter

---

package-lock.json
package.json

Remove set-value

---

package-lock.json
package.json

Remove query string

---

package-lock.json
package.json

Remove ajv

---

package-lock.json
package.json
src/Honeybadger.js

Upgrade Honeybadger.

---

__tests__/components/editor/property/RenderLookupContext.test.js
package-lock.json
package.json
setupEnzyme.js
src/components/editor/property/RenderLookupContext.jsx

closes #2946
No longer using enzyme for testing.
Unit

Remove enzyme.

---

package-lock.json
package.json

Upgrade babel-jest.

---

package-lock.json
package.json

Upgrade jsdom.

---

README.md
__tests__/actionCreators/lookups.test.js
__tests__/actionCreators/resources.test.js
package-lock.json
package.json
src/actionCreators/lookups.js
src/actionCreators/resourceHelpers.js
src/components/editor/actions/MarcButton.jsx
src/components/editor/property/InputURI.jsx
src/components/editor/property/NestedProperty.jsx
src/components/editor/property/PanelProperty.jsx
src/components/editor/property/PropertyLabelInfoTooltip.jsx
src/components/editor/property/RequiredSuperscript.jsx
src/components/editor/property/ResourceList.jsx
src/utilities/valueFactory.js

closes #2967
Shortid is deprecated.
Unit

Replace shortid with nanoid.

---

__tests__/components/App.test.js
package-lock.json
package.json

Upgrade jest and fix open handles.

---

src/components/editor/ExpiringMessage.jsx
src/components/search/QASearchResults.jsx
src/hooks/useNavigableComponent.js
src/hooks/useResource.js

closes #2928
Better rendering.
Unit, local

Switches to useLayoutEffect where relevant.

---

.circleci/config.yml

Adds dependency updates to circle.

---

Dockerfile.cypress
__tests__/components/App.test.js
__tests__/feature/editing/copyTemplateResource.test.js
__tests__/feature/editing/propInfo.test.js
__tests__/feature/loadResource.test.js
__tests__/feature/searchAndOpenTemplate.test.js
__tests__/testUtilities/featureUtils.js
cypress/integration/end2end.spec.js
cypress/integration/leftNav.spec.js
package-lock.json
package.json
src/components/Alert.jsx
src/components/Header.jsx
src/components/editor/EditorActions.jsx
src/components/editor/actions/CloseResourceModal.jsx
src/components/editor/property/InputLang.jsx
src/components/editor/property/InputList.jsx
src/components/editor/property/InputLiteral.jsx
src/components/editor/property/InputLookup.jsx
src/components/editor/property/InputValue.jsx
src/components/editor/property/PropertyLabelInfoTooltip.jsx
src/components/editor/property/ResourceList.jsx
src/components/home/NewsPanel.jsx
src/components/search/Search.jsx
src/components/search/SinopiaSort.jsx
src/index.js
src/styles/bootstrap-variables.scss
src/styles/main.scss
test-env.js
webpack.config.js

closes #2956
BS goodness
Unit, local

Upgrade to Bootstrap 5.

---

package-lock.json
package.json

Upgrade isomorphic fetch.

---

package-lock.json
package.json

Upgrade crypt-js.

---

__tests__/feature/userPermissions.test.js
__tests__/testUtilities/fixtureLoaderHelper.js
__tests__/testUtilities/stateUtils.js
src/actionCreators/authenticate.js
src/components/Header.jsx
src/components/ViewResourceModal.jsx
src/components/search/SearchResultRows.jsx
src/components/templates/NewResourceTemplateButton.jsx
src/components/templates/ResourceTemplateRow.jsx
src/hooks/usePermissions.js
src/sinopiaSearch.js

Enforce permissions

---

release_process.md

Document release process.
release instructions

Add instructions for creating a release from a beta release.

---

docker-compose.yml

More realistic local environment.
docker-compose.yml

Enforce permissions in local docker.

---

src/components/editor/actions/MarcButton.jsx

Fixes #3016 - change styling of MARC button and DRY up classes for drop-down item buttons
Localhost

change styling of MARC button

---

__tests__/__action_fixtures__/loadResource-ADD_SUBJECT.json
__tests__/__action_fixtures__/newResourceCopy-ADD_SUBJECT.json
__tests__/__resource_fixtures__/test.json
__tests__/feature/dashboard.test.js
__tests__/feature/editing/changeGroups.test.js
__tests__/feature/editing/saveResource.test.js
__tests__/feature/editing/viewGroups.test.js
__tests__/feature/loadResource.test.js
__tests__/feature/searchAndViewResource.test.js
__tests__/reducers/resources.test.js
__tests__/testUtilities/stateUtils.js
src/components/editor/ResourceComponent.jsx
src/reducers/resources.js

Display the rdfs:label as the resource title

---

__tests__/utilities/Utilities.test.js

Remove last trellis reference

---

__tests__/feature/editing/saveAndCopyResource.test.js
src/components/editor/ResourcesNav.jsx
src/selectors/templates.js

Display resource label on editor tabs

---

__tests__/feature/editing/editingLiteral.test.js
src/components/editor/inputs/InputLang.jsx

Fixes #3036 -- set the radio buttons correctly based on the language selection
Localhost

ensure language radio buttons are selected correctly

---

index.html

WCAG 1.1 requirements
Fixes #3073

Add a language tag to the HTML element

---

src/styles/variables.scss

Switch the property heading color to black for better contrast

---

src/components/editor/diacritics/DiacriticsSelection.jsx

Add an accessible label for closing the diacritics keyboard

---

__tests__/feature/loadRDF.test.js
src/components/load/LoadByRDFForm.jsx

Update labels on the Load RDF page

---

src/components/Header.jsx
src/styles/main.scss

Update logo to read Sinopia

---

__tests__/sinopiaSearch.test.js
src/sinopiaSearch.js

Add the group field to the search query

---

cypress/integration/end2end.spec.js
cypress/integration/helpAndResources.spec.js
src/components/Header.jsx
src/styles/header.scss
src/styles/main.scss

Update style for page navigation tabs

---

src/components/ViewResourceModal.jsx
src/components/search/SearchResultRows.jsx

Fixes #3110 - make edit icon consistent with design change made in #2853

use new pencil icon for edits in all locations

---

package-lock.json
package.json

Upgrade style-loader to 3.3.0

---

cypress/integration/leftNav.spec.js
src/components/editor/leftNav/ActivePanelPropertyNav.jsx
src/components/editor/leftNav/PanelPropertyNav.jsx
src/components/editor/leftNav/PresenceIndicator.jsx
src/components/editor/leftNav/PropertySubNav.jsx
src/components/editor/leftNav/SubjectSubNav.jsx
src/styles/resourceNav.scss

Replace the check on the left nav headings with a circle

---

package-lock.json
package.json

Remove file-loader because it is unused

---

static/authorityConfig.json

Adding configs for locvocabs

---

__tests__/feature/editing/transfer.test.js

Increase timeouts for transfer test.

---

__tests__/components/App.test.js
__tests__/components/search/Search.test.js
__tests__/feature/dashboard.test.js
__tests__/feature/editing/changeGroups.test.js
__tests__/feature/editing/transfer.test.js
__tests__/feature/editing/viewGroups.test.js
__tests__/feature/loadResource.test.js
__tests__/feature/search.test.js
__tests__/feature/searchAndViewResource.test.js
__tests__/feature/userPermissions.test.js
__tests__/testUtilities/stateUtils.js
cypress/integration/end2end.spec.js
cypress/integration/helpAndResources.spec.js
src/components/Header.jsx
src/components/search/HeaderSearch.jsx
src/components/search/Search.jsx
src/hooks/useSearch.js
src/styles/header.scss

Moves search to nav.

---

__tests__/feature/editorPreview.test.js
src/components/editor/preview/ResourceDisplay.jsx

Speed up test.

---

src/components/home/NewsItem.jsx

Update NewsItem with latest.

---

src/components/App.jsx
src/components/ResourceTemplateChoiceModal.jsx
src/components/editor/GroupChoiceModal.jsx
src/components/editor/actions/CloseResourceModal.jsx
src/components/editor/inputs/InputLang.jsx
src/components/editor/preview/EditorPreviewModal.jsx
src/components/editor/preview/PreviewModal.jsx
src/hooks/useLeftNav.js
src/selectors/modals.js

Changes modal selectors to reduce rerenders.

---

__tests__/feature/searchAndPreviewResource.test.js
src/components/editor/property/NestedProperty.jsx
src/components/editor/property/NestedResource.jsx

Suppress empty resources and properties from the preview

---

src/GraphBuilder.js

Remove unused toTurtle() method.

---

src/components/home/NewsItem.jsx

Updated NewsItem.

---

static/authorityConfig.json

Add Publisher Cities lookup

---

src/components/ResourceTemplateChoiceModal.jsx
src/components/editor/GroupChoiceModal.jsx
src/components/editor/leftNav/DiffModal.jsx
src/styles/main.scss

Fix modal by getting rid of extraneous styles

---

src/components/buttons/CopyButton.jsx

Fix the title of the copy icon

---

src/utilities/QuestioningAuthority.js

Import may not needed and causes problems
Localhost

remove unnecessary import

---

__tests__/actionCreators/search.test.js
__tests__/components/search/Search.test.js
__tests__/utilities/QuestioningAuthority.test.js
package-lock.json
package.json
src/lib/apidoc.json
src/utilities/QuestioningAuthority.js

This reverts commit 40c0d9a43cfd6a8ff5aa22717a70a443911577f5.
This change broke QA.

Revert "Replace swagger-based QA client with simple fetch calls"

---

src/components/editor/inputs/InputURIValue.jsx
src/components/editor/property/PropertyURI.jsx

Change the input alignment for inputURI

---

package-lock.json
package.json

Remove reselect.

---

__tests__/__template_fixtures__/TitleNote.json
__tests__/__template_fixtures__/testing_dupe_properties.json
__tests__/actionCreators/resources.loadResource.test.js
__tests__/actionCreators/resources.newResource.test.js
__tests__/actionCreators/resources.newResourceFromDataset.test.js
__tests__/actionCreators/templateValidationHelpers.test.js
__tests__/actionCreators/templates.test.js
__tests__/feature/loadResource.test.js
__tests__/testUtilities/fixtureLoaderHelper.js
__tests__/testUtilities/resourceBuilderUtils.js
__tests__/testUtilities/stateResourceBuilderUtils.js
src/TemplatesBuilder.js
src/actionCreators/templateValidationHelpers.js
src/actionCreators/templates.js
src/utilities/Utilities.js

closes #3221
Better modeling.
Unit

Allow duplicate property templates with different classes.

---

server.js

Fixes #3339
See subject.
CI
None

Replace deprecated express body parsing

---

src/components/App.jsx
src/components/dashboard/Dashboard.jsx
src/components/editor/Editor.jsx
src/components/exports/Exports.jsx
src/components/home/LoginPanel.jsx
src/components/search/QASearchResults.jsx
src/components/search/Search.jsx
src/components/templates/ResourceTemplate.jsx
src/reducers/resources.js
src/utilities/errorKeyFactory.js

This fixes an open handle issue in tests.

Moves error keys into own utility file.

---

.circleci/config.yml
package-lock.json
package.json

Upgrade JSON-LD library

---

__tests__/feature/editing/editorRouting.test.js

Add waitfor to editorRoutingTest

---

Dockerfile.cypress
package-lock.json
package.json

Upgrades cypress.

---

.circleci/config.yml

Increases timeout when running tests.

---

__tests__/feature/editing/changeGroups.test.js
__tests__/feature/editing/versionsDiff.test.js
__tests__/reducers/resources.test.js
src/components/vocabulary/Vocab.js
src/reducers/resourceHelpers.js

http not https.

---

__tests__/components/App.test.js
__tests__/feature/metrics/viewResourceMetrics.test.js
__tests__/feature/metrics/viewTemplateMetrics.test.js
__tests__/feature/metrics/viewUserMetrics.test.js
__tests__/sinopiaApi.test.js
__tests__/sinopiaMetrics.test.js
src/components/App.jsx
src/components/Header.jsx
src/components/metrics/CountCard.jsx
src/components/metrics/MetricsWrapper.jsx
src/components/metrics/ResourceMetrics.jsx
src/components/metrics/TemplateMetrics.jsx
src/components/metrics/UserMetrics.jsx
src/hooks/useMetric.js
src/sinopiaApi.js
src/sinopiaMetrics.js
src/utilities/SinopiaApiHelper.js
src/utilities/errorKeyFactory.js

Adds display for initial metrics.

---

__tests__/reducers/errors.test.js
__tests__/reducers/index.test.js
__tests__/reducers/modals.test.js
src/actions/modals.js
src/reducers/index.js
src/reducers/modals.js
src/selectors/modals.js
src/store.js

* Consistency with other state conventions.
* Remove unused state.

Refactors modal state.

---

__tests__/reducers/modals.test.js
src/actions/modals.js
src/components/editor/Editor.jsx
src/components/editor/inputs/InputLang.jsx
src/components/editor/inputs/LanguageButton.jsx
src/reducers/index.js
src/reducers/modals.js
src/selectors/modals.js
src/store.js

One modal is more efficient than one modal per input.
Unit

Move to a singleton InputLang modal.

---

__tests__/actionCreators/relationships.test.js
__tests__/actionCreators/search.test.js
__tests__/feature/searchAndPreviewResource.test.js
__tests__/feature/searchAndViewRelationships.test.js
__tests__/reducers/relationships.test.js
__tests__/reducers/search.test.js
__tests__/selectors/relationships.test.js
__tests__/selectors/search.test.js
__tests__/testUtilities/fixtureLoaderHelper.js
src/actionCreators/relationships.js
src/actionCreators/search.js
src/actions/relationships.js
src/actions/resources.js
src/components/editor/actions/MarcButton.jsx
src/components/editor/actions/TransferButtons.jsx
src/components/search/QASearchResults.jsx
src/components/search/RelationshipResults.jsx
src/components/search/SearchResultRow.jsx
src/components/search/SinopiaSearchResults.jsx
src/reducers/index.js
src/reducers/relationships.js
src/reducers/search.js
src/selectors/relationships.js
src/selectors/search.js
src/store.js
src/styles/main.scss
src/utilities/Bibframe.js

closes #3269
Easier discovery of BF resources.

Display relationships in search results.

---

README.md
__tests__/feature/editing/editingLanguage.test.js
__tests__/reducers/languages.test.js
__tests__/reducers/resources.test.js
__tests__/testUtilities/stateResourceBuilderUtils.js
src/actions/languages.js
src/components/editor/inputs/InputLang.jsx
src/components/editor/inputs/InputLiteralOrURI.jsx
src/components/editor/inputs/InputLookupValue.jsx
src/reducers/index.js
src/reducers/languages.js
src/reducers/resourceHelpers.js
src/reducers/resources.js
src/selectors/languages.js
src/utilities/Language.js
src/utilities/valueFactory.js

closes #3372
Less boilerplate for catalogers.

Allow selecting a default language for a resource.

---

src/components/home/NewsItem.jsx

Updated news item.

---

__tests__/reducers/resources.test.js
src/reducers/resourceHelpers.js

closes #3388
Correct behavior.

Mark resource as changed when URI changes.

---

__tests__/feature/editing/editingLiteral.test.js
__tests__/feature/editing/editingUri.test.js
__tests__/reducers/resources.test.js
src/actions/resources.js
src/components/editor/inputs/InputLiteralValue.jsx
src/components/editor/inputs/InputURIValue.jsx
src/hooks/useResourcHasChanged.js
src/reducers/index.js
src/reducers/resources.js

Improve enabling of Save button.

---

__tests__/sinopiaApi.test.js
src/sinopiaApi.js

closes #3393
@michelleif prefers non-broken.

Fixes fetchResourceVersions.

---

__tests__/feature/metrics/viewResourceMetrics.test.js
__tests__/feature/metrics/viewTemplateMetrics.test.js
__tests__/sinopiaMetrics.test.js
src/components/metrics/CountCard.jsx
src/components/metrics/DateRangeFilter.jsx
src/components/metrics/GroupFilter.jsx
src/components/metrics/MetricsWrapper.jsx
src/components/metrics/ResourceCountMetric.jsx
src/components/metrics/ResourceCreatedCountMetric.jsx
src/components/metrics/ResourceMetrics.jsx
src/components/metrics/TemplateCountMetric.jsx
src/components/metrics/TemplateCreatedCountMetric.jsx
src/components/metrics/TemplateMetrics.jsx
src/hooks/useMetric.js
src/sinopiaMetrics.js
src/utilities/SinopiaApiHelper.js

refs #3379
Provide additional metrics.

Template and resource creation metrics

---

__tests__/actionCreators/languages.test.js
__tests__/feature/editing/editingLanguage.test.js
__tests__/selectors/languages.test.js
__tests__/testUtilities/stateUtils.js
src/actionCreators/languages.js

Fix code for ALA Transliteration scheme.

---

__tests__/feature/metrics/viewTemplateMetrics.test.js
src/components/metrics/CountCard.jsx
src/components/metrics/ResourceCountMetric.jsx
src/components/metrics/ResourceCreatedCountMetric.jsx
src/components/metrics/TemplateCountMetric.jsx
src/components/metrics/TemplateCreatedCountMetric.jsx
src/components/metrics/UserMetrics.jsx
src/hooks/useMetric.js
src/styles/main.scss

Adds help text for metrics.

---

__tests__/feature/metrics/viewResourceMetrics.test.js
__tests__/feature/metrics/viewTemplateMetrics.test.js
__tests__/sinopiaMetrics.test.js
src/components/metrics/ResourceEditedCountMetric.jsx
src/components/metrics/ResourceMetrics.jsx
src/components/metrics/TemplateEditedCountMetric.jsx
src/components/metrics/TemplateMetrics.jsx
src/sinopiaMetrics.js

Edited count metric

---

__tests__/feature/editing/requestMARC.test.js
__tests__/feature/searchAndPreviewResource.test.js
__tests__/reducers/errors.test.js
__tests__/reducers/index.test.js
__tests__/reducers/modals.test.js
src/actions/modals.js
src/components/alerts/ContextAlert.jsx
src/components/dashboard/Dashboard.jsx
src/components/editor/Editor.jsx
src/components/editor/actions/MarcButton.jsx
src/components/editor/actions/MarcModal.jsx
src/components/editor/actions/SaveAndPublishButton.jsx
src/components/search/SinopiaSearchResults.jsx
src/reducers/index.js
src/reducers/modals.js
src/selectors/modals.js
src/store.js

Refactors MARC button.

---

__tests__/feature/editing/viewRelationships.test.js
src/components/editor/ResourceComponent.jsx
src/components/editor/ResourceTitle.jsx

Prefix the title with the BF class

---

__tests__/feature/metrics/viewTemplateMetrics.test.js
__tests__/sinopiaMetrics.test.js
src/components/InputTemplate.jsx
src/components/ResourceTemplateChoiceModal.jsx
src/components/metrics/TemplateFilter.jsx
src/components/metrics/TemplateMetrics.jsx
src/components/metrics/TemplateUsageCountMetric.jsx
src/sinopiaMetrics.js

Display template usage metrics.

---

__tests__/actionCreators/templateValidationHelpers.test.js
src/actionCreators/templateValidationHelpers.js

Fix error message for suppressible property.

---

__tests__/feature/editing/editingClass.test.js
src/components/editor/property/ResourceClass.jsx

Changes class selector to checkboxes.

---

src/components/editor/property/ResourceClass.jsx

Tweak layout of resource classes.

---

__tests__/__template_fixtures__/ld4p_RT_bf2_RareMat_RBMS.json
__tests__/__template_fixtures__/uber_template1.json
cypress/fixtures/uber_template1.txt

Updates test templates to new URI defaults.

---

__tests__/TemplatesBuilder.test.js
__tests__/actionCreators/templateValidationHelpers.test.js
src/TemplatesBuilder.js
src/actionCreators/templateValidationHelpers.js
src/actionCreators/templates.js
src/components/vocabulary/Vocab.js
static/authorityConfig.json
static/literalPropertyAttribute.json
static/templates/rt_literal_property_attrs_doc.json
static/templates/rt_property_template_doc.json

Add a new literal data type for user ID default

---

__tests__/TemplatesBuilder.test.js
__tests__/utilities/Utilities.test.js
src/TemplatesBuilder.js
src/components/metrics/DateRangeFilter.jsx
src/components/vocabulary/Vocab.js
src/utilities/Utilities.js
static/literalPropertyAttribute.json

closes #3358
Less cataloger boilerplate.

Adds date literal default.

---

src/components/search/RelationshipResults.jsx
src/components/search/SinopiaSearchResults.jsx

Fix alignment of relationships nested table.

---

__tests__/feature/editing/editingLanguage.test.js
__tests__/sinopiaApi.test.js
src/actionCreators/languages.js
src/components/editor/inputs/InputLang.jsx
src/selectors/languages.js
src/sinopiaApi.js

refs #3416
Less work for catalogers.

Provide language suggestions.

---

__tests__/TemplatesBuilder.test.js
src/TemplatesBuilder.js

closes #3428
I love JS.
Local.

Fix template builder bug.

---

static/authorityConfig.json
static/searchConfig.json

Follows the context definitions in [Indexing Spreadsheet](https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit#gid=502967565)

Add ShareVDE PCC authority

---

__tests__/feature/editing/requestMARC.test.js
__tests__/feature/editing/saveResource.test.js
__tests__/feature/searchAndPreviewResource.test.js
src/components/ClipboardButton.jsx
src/components/editor/ResourceURIMessage.jsx
src/components/editor/actions/MarcModal.jsx
src/components/editor/preview/RDFDisplay.jsx

Adds additional copy to clipboards.

---

__tests__/feature/search.test.js
__tests__/reducers/search.test.js
src/actions/search.js
src/components/search/HeaderSearch.jsx
src/reducers/index.js
src/reducers/search.js
src/selectors/search.js
src/store.js

Maintains header search state when changing pages.

---

__tests__/feature/searchAndOpenTemplate.test.js
src/components/templates/ResourceTemplate.jsx
src/components/templates/ResourceTemplateRow.jsx

Adds view to template results.

---

src/styles/resourceTabs.scss

closes #3451
I didn't get it right the first time.
Local

Tweaks to nav tab CSS.

---

__tests__/TemplatesBuilder.test.js
__tests__/utilities/Utilities.test.js
package-lock.json
package.json
src/TemplatesBuilder.js
src/utilities/Utilities.js

closes #3437
So that the user gets the correct default date.

Uses local timezone when setting default date.

---

src/components/home/NewsItem.jsx

Update news item.

---

src/components/metrics/DateRangeFilter.jsx
src/components/metrics/GroupFilter.jsx
src/components/metrics/TemplateFilter.jsx

Adjust spacing in metrics filters.

---

__tests__/GraphBuilder.test.js
src/GraphBuilder.js
src/components/search/Search.jsx
src/components/search/SinopiaSearchResults.jsx

Add subclasses to RDF for nested resources.

---

src/components/editor/UnusedRDFDisplay.jsx

Only show unused RDF for current resource.

---

static/authorityConfig.json

Fulfills request for authority LOC Cultural Heritage Organizations.

add authority LOC Cultural Heritage Organizations

---

package-lock.json
package.json

Version 3.16.2

---

package-lock.json
package.json

Version 3.16.4

---

package-lock.json
package.json

Dependency updates.
`package.json` and `package-lock.json

Version 3.16.6

---

package-lock.json
package.json

Version 3.16.8

---

package-lock.json
package.json

Dependency updates for a new version
n/a

Version 3.16.9

---

package-lock.json
package.json

Version 3.16.10

---

package-lock.json
package.json

Version 3.16.11

---

package-lock.json
package.json

Version 3.16.12

---

package-lock.json
package.json

Version 3.16.13

---

package-lock.json
package.json

Version 3.16.14

---

__tests__/Config.test.js
__tests__/utilities/QuestioningAuthority.test.js
src/Config.js

Fixes #3505 
Unit and integration tests
n/a

Increase value so that QA and Sinopia defaults are the same

---

static/authorityConfig.json

Fixes https://github.com/LD4P/sinopia/issues/328
Fixes #3512 
Unit and integration tests
`static/authorityConfig.json`

Adds Norway local and QA authorities

---

package-lock.json
package.json

Dependency updates and new authorities
unit and integration tests

Version 3.16.15

---

package-lock.json
package.json

Version 3.16.16

---

package-lock.json
package.json

Version 3.16.17

---

package-lock.json
package.json

Version 3.16.19

---

package-lock.json
package.json

Version 3.16.20

---

package-lock.json
package.json

Version 3.16.21

---

package-lock.json
package.json

Version 3.16.23

---

package-lock.json
package.json

n/a
`package.json` and `package-lock.json`.

Version 3.16.24

---

package-lock.json
package.json

Version 3.16.25

---

package-lock.json
package.json

Version 3.16.26

---

package-lock.json
package.json

Version 3.16.27

---

package-lock.json
package.json

Version 3.16.28

---

package-lock.json
package.json

Version 3.15.29

---

package-lock.json
package.json

Version 3.16.30

---

README.md

Add missing step to README.

---

package-lock.json
package.json

Includes dependency updates
n/a

Version 3.17.0

---

.eslintrc.js

Remove cruft from eslintrc.

---

.circleci/config.yml
README.md
__tests__/actionCreators/history.test.js
__tests__/actionCreators/resources.loadResource.test.js
__tests__/actionCreators/resources.newResource.test.js
__tests__/actionCreators/resources.newResourceCopy.test.js
__tests__/actionCreators/resources.test.js
__tests__/feature/dashboard.test.js
__tests__/feature/editing/editingLiteral.test.js
__tests__/feature/searchAndPreviewResource.test.js
__tests__/sinopiaApi.test.js
__tests__/testUtilities/fixtureLoaderHelper.js
__tests__/testUtilities/resolver.js
package-lock.json
package.json
src/sinopiaApi.js
webpack.config.js

Tests were not running reliably local and in CI.

Tweaks so that tests run reliably local and in CI.

---

package-lock.json
package.json

Version 3.17.1

---

package-lock.json
package.json

Version 3.17.5

---

package-lock.json
package.json

n/a
`package.json` and ``package-lock.json`

Version 3.17.6

---

package-lock.json
package.json

Dependency updates/version update
n/a

Version 3.17.7

---

package-lock.json
package.json

Version 3.17.8

---

package-lock.json
package.json

Version 3.17.9

---

package-lock.json
package.json

Version 3.17.10

---

package-lock.json
package.json

Version 3.17.11

---

package-lock.json
package.json

Version 3.17.12

---

package-lock.json
package.json

Version 3.17.13

---

__tests__/feature/userPermissions.test.js
static/authorityConfig.json

Adding MARC countries to QA at the request of Nancy Lorimer.

Adding MARC Countries for PCC profiles

---

package-lock.json
package.json

Version 3.17.15

---

package-lock.json
package.json

Version 3.17.16

---

package-lock.json
package.json

Version 3.17.17

---

package-lock.json
package.json

Version 3.17.18

---

package-lock.json
package.json

Version 3.17.19

---

package-lock.json
package.json

Version 3.17.20

---

package-lock.json
package.json

Version 3.17.21

---

package-lock.json
package.json

Version 3.17.22

---

package-lock.json
package.json

Version 3.17.23

---

package-lock.json
package.json

Version 3.17.24

---

package-lock.json
package.json

Version 3.17.25

---

package-lock.json
package.json

Version 3.17.27

---

package-lock.json
package.json

Version 3.17.28

---

package-lock.json
package.json

Version 3.17.29

---

package-lock.json
package.json

Version 3.17.30

---

package-lock.json
package.json

Version 3.17.32

---

package-lock.json
package.json

Version 3.17.34

---

static/authorityConfig.json

Rda authority config

---

package-lock.json
package.json

Version 3.17.36

---

package-lock.json
package.json

Version 3.17.37

---

package-lock.json
package.json

Version 3.17.38

---

package-lock.json
package.json

Version 3.17.39

---

package-lock.json
package.json

Version 3.17.40

---

package-lock.json
package.json

Version 3.17.41

---

package-lock.json
package.json

Version 3.17.42

---

package-lock.json
package.json

Version 3.17.43

---

package-lock.json
package.json

Version 3.17.44

---

package-lock.json
package.json

Version 3.17.45

---

package-lock.json
package.json

Version 3.17.47

---

package-lock.json
package.json

Version 3.17.48

---

package-lock.json
package.json

Version 3.17.50

---

package-lock.json
package.json

Version 3.17.51

---

static/authorityConfig.json

QA is attempting to add more direct lookups to move away from caching.

Adding QA Geonames Direct Lookup

---

package-lock.json
package.json

Version 3.17.52

---

package-lock.json
package.json

Version 3.17.53

---

package-lock.json
package.json

Version 3.17.54

---

package-lock.json
package.json

Version 3.17.55

---

package-lock.json
package.json

Version 3.17.56

---

package-lock.json
package.json

Version 3.17.57

---

package-lock.json
package.json

Version 3.17.58

---

package-lock.json
package.json

Version 3.17.59

---

package-lock.json
package.json

Version 3.17.60

---

package-lock.json
package.json

Version 3.17.61

---

package-lock.json
package.json

Version 3.17.62

---

static/authorityConfig.json

Fix copy and paste error

---

package-lock.json
package.json

Version 3.17.63

---

package-lock.json
package.json

Version 3.17.64

---

package-lock.json
package.json

Version 3.17.65

---

package-lock.json
package.json

Version 3.17.66

---

static/authorityConfig.json

Adding LOC Direct Lookups as first step to removing cached lookups.

LOC Names Direct Lookups

---

static/authorityConfig.json

Hoping these updates will point to the QA endpoints correctly.

Fixing nonLDLookup lookups

---

package-lock.json
package.json

Version 3.17.67

---

package-lock.json
package.json

Version 3.17.68

---

__tests__/feature/editing/editingLookup.test.js
__tests__/feature/editing/editingUri.test.js
__tests__/feature/editing/transfer.test.js
__tests__/feature/newResourceTemplate.test.js
__tests__/feature/userPermissions.test.js

Adjust timeouts

---

package-lock.json
package.json

Version 3.17.69

---

__tests__/__template_fixtures__/Instance.json
__tests__/__template_fixtures__/Work.json
__tests__/__template_fixtures__/WorkTitle.json
__tests__/actionCreators/resources.newResource.test.js
__tests__/actionCreators/resources.test.js
__tests__/feature/editing/editingLookup.test.js
__tests__/selectors/resources.test.js
__tests__/testUtilities/fixtureLoaderHelper.js
__tests__/testUtilities/stateUtils.js
src/actionCreators/resourceHelpers.js
src/actionCreators/resources.js
src/components/editor/property/ResourceList.jsx
src/selectors/resources.js

closes #3762
Cataloger convenience.

Derive work titles from instances.

---

package-lock.json
package.json

Version 3.17.70

---

package-lock.json
package.json

Version 3.17.71

---

package-lock.json
package.json

Version 3.17.74

---

package-lock.json
package.json

Version 3.17.75

---

package-lock.json
package.json

Version 3.17.76

---

package-lock.json
package.json

Version 3.17.77

---

package-lock.json
package.json

Version 3.17.79

---

package-lock.json
package.json

Version 3.17.80

---

package-lock.json
package.json

Version 3.17.81

---

package-lock.json
package.json

Version 3.17.82

---

package-lock.json
package.json

Version 3.17.84

---

package-lock.json
package.json

Version 3.17.83

---

static/authorityConfig.json

This lookup didn't follow the pattern of the others.

Fixing typo

---

package-lock.json
package.json

Version 3.17.85

---

package-lock.json
package.json

Version 3.17.86

---

package-lock.json
package.json

Version 3.17.87

---

package-lock.json
package.json

Version 3.17.89

---

package-lock.json
package.json

Version 3.17.90

---

package-lock.json
package.json

n/a
`package.json` `package-lock.json`

Version 3.17.91

---

package-lock.json
package.json

Version 3.17.92

---

package-lock.json
package.json

Version 3.17.93

---

package-lock.json
package.json

Version 3.17.94

---

package-lock.json
package.json

Version 3.17.95

---

package-lock.json
package.json

Version 3.17.96

---

package-lock.json
package.json

Version 3.17.98

---

package-lock.json
package.json

Version 3.17.99

---

package-lock.json
package.json

Version 3.17.100

---

package-lock.json
package.json

Version 3.17.101

---

package-lock.json
package.json

Version 3.17.102

---

package-lock.json
package.json

Version 3.17.103

---

__tests__/sinopiaSearch.test.js
src/Config.js

See https://github.com/LD4P/sinopia_editor/pull/3859

Removed the deprecated type part from the search URLs

---

package-lock.json
package.json

Version 3.17.104

---

package-lock.json
package.json

Version 3.17.105

---

package-lock.json
package.json

Version 3.17.106

---

package-lock.json
package.json

Version 3.17.108

---

package-lock.json
package.json

Version 3.17.109

---

package-lock.json
package.json

Version 3.17.110

---

package-lock.json
package.json

Version 3.17.111

---

package-lock.json
package.json

Version 3.17.112

---

package-lock.json
package.json

Version 3.17.113

---

src/Config.js

Added JMU group - see ticket #3875 
N/A
N/A

Update Config.js - jmu (james madison)

---

src/Config.js

Update Config.js - brandeis added ils config

---

package-lock.json
package.json

Version 3.17.114

---

package-lock.json
package.json

Version 3.17.115

---

.github/ISSUE_TEMPLATE/sinopia-alma-integration-request.md

Added region variables step to the request form
n/a
n/a

Update sinopia-alma-integration-request.md - added region variable

---

package-lock.json
package.json

Version 3.17.116

---

package-lock.json
package.json

Version 3.17.119

---

src/Config.js

University of Toronto is requesting a Sinopia / Alma integration

Update Config.js - add utoronto to ils group

---

package-lock.json
package.json

Version 3.17.120

---

package-lock.json
package.json

Version 3.17.121

---

package-lock.json
package.json

Version 3.17.122

---

package-lock.json
package.json

Version 3.17.125

---

src/Config.js

Adding University of Central Florida to ILS group list
Sai Deng at University of Central Florida requests Alma/Sinopia integration. See Issue #3924 
n/a
config.js

Update Config.js - adding UCF

---

package-lock.json
package.json

Version 3.17.126

---

package-lock.json
package.json

Version 3.17.128

---

package-lock.json
package.json

Version 3.17.129

---

package-lock.json
package.json

Version 3.17.130

---

package-lock.json
package.json

Version 3.17.131

---

package-lock.json
package.json

Version 3.17.132

---

package-lock.json
package.json

Version 3.17.133

---

package-lock.json
package.json

Version 3.17.134

---

package-lock.json
package.json

Version 3.17.135

---

package-lock.json
package.json

Version 3.17.137

---

package-lock.json
package.json

Version 3.17.138

---

package-lock.json
package.json

Version 3.17.139

---

package-lock.json
package.json

Version 3.17.140

---

package-lock.json
package.json

Version 3.17.142

---

package-lock.json
package.json

Version 3.17.144

---

package-lock.json
package.json

Version 3.17.149

---

package-lock.json
package.json

Version 3.17.150

---

package-lock.json
package.json

Version 3.17.151

---

package-lock.json
package.json

Version 3.17.153

---

package-lock.json
package.json

Version 3.17.155

---

package-lock.json
package.json

Version 3.17.156

---

package-lock.json
package.json

Version 3.17.157

---

package-lock.json
package.json

Version 3.17.158
